/* eslint-disable */
/* GENERATED by idl/codegen/generate_streams.sh — DO NOT EDIT.
 * Source: idl/download_service.proto
 * Template: idl/codegen/templates/ts_async_iterable.njk
 *
 * Provides an AsyncIterable<DownloadProgress> client
 * over an in-process server-streaming callback. The transport ("how a token
 * arrives in the JS heap") is platform-specific:
 *   - React Native: a Nitro HybridObject method whose callback fires once
 *     per server-streamed message.
 *   - Web: an Emscripten-emscripten Module.addFunction() callback.
 *
 * The platform adapter provides the `subscribe(req, onMessage, onError, onDone)`
 * function; this generated wrapper turns it into an AsyncIterable.
 */

import { streamFactory, type StreamTransport } from "./_streamFactory";
import type { DownloadSubscribeRequest } from "../download_service";
import type { DownloadProgress } from "../download_service";

export interface DownloadStreamTransport extends StreamTransport<DownloadSubscribeRequest, DownloadProgress> {}

export function subscribeDownload(
    transport: DownloadStreamTransport,
    req: DownloadSubscribeRequest,
): AsyncIterable<DownloadProgress> {
    return streamFactory(transport, req);
}
