/* eslint-disable */
/* GENERATED by idl/codegen/generate_streams.sh — DO NOT EDIT.
 * Source: idl/llm_service.proto
 * Template: idl/codegen/templates/ts_async_iterable.njk
 *
 * Provides an AsyncIterable<LLMStreamEvent> client
 * over an in-process server-streaming callback. The transport ("how a token
 * arrives in the JS heap") is platform-specific:
 *   - React Native: a Nitro HybridObject method whose callback fires once
 *     per server-streamed message.
 *   - Web: an Emscripten-emscripten Module.addFunction() callback.
 *
 * The platform adapter provides the `subscribe(req, onMessage, onError, onDone)`
 * function; this generated wrapper turns it into an AsyncIterable.
 */

import { streamFactory, type StreamTransport } from "./_streamFactory";
import type { LLMGenerateRequest } from "../llm_service";
import type { LLMStreamEvent } from "../llm_service";

export interface LLMStreamTransport extends StreamTransport<LLMGenerateRequest, LLMStreamEvent> {}

export function generateLLM(
    transport: LLMStreamTransport,
    req: LLMGenerateRequest,
): AsyncIterable<LLMStreamEvent> {
    return streamFactory(transport, req);
}
