/* eslint-disable */
/* GENERATED by idl/codegen/generate_streams.sh — DO NOT EDIT.
 * Source: idl/sdk_events.proto
 * Template: idl/codegen/templates/ts_async_iterable.njk
 *
 * Provides an AsyncIterable<SDKEvent> client
 * over an in-process server-streaming callback. The transport ("how a token
 * arrives in the JS heap") is platform-specific:
 *   - React Native: a Nitro HybridObject method whose callback fires once
 *     per server-streamed message.
 *   - Web: an Emscripten-emscripten Module.addFunction() callback.
 *
 * The platform adapter provides the `subscribe(req, onMessage, onError, onDone)`
 * function; this generated wrapper turns it into an AsyncIterable.
 */

import { streamFactory, type StreamTransport } from "./_streamFactory";
import type { SDKEventSubscribeRequest } from "../sdk_events";
import type { SDKEvent } from "../sdk_events";

export interface SDKEventsStreamTransport extends StreamTransport<SDKEventSubscribeRequest, SDKEvent> {}

export function subscribeSDKEvents(
    transport: SDKEventsStreamTransport,
    req: SDKEventSubscribeRequest,
): AsyncIterable<SDKEvent> {
    return streamFactory(transport, req);
}
