/* eslint-disable */
/* GENERATED by idl/codegen/generate_streams.sh — DO NOT EDIT.
 * Source: idl/structured_output.proto
 * Template: idl/codegen/templates/ts_async_iterable.njk
 *
 * Provides an AsyncIterable<StructuredOutputStreamEvent> client
 * over an in-process server-streaming callback. The transport ("how a token
 * arrives in the JS heap") is platform-specific:
 *   - React Native: a Nitro HybridObject method whose callback fires once
 *     per server-streamed message.
 *   - Web: an Emscripten-emscripten Module.addFunction() callback.
 *
 * The platform adapter provides the `subscribe(req, onMessage, onError, onDone)`
 * function; this generated wrapper turns it into an AsyncIterable.
 */

import { streamFactory, type StreamTransport } from "./_streamFactory";
import type { StructuredOutputRequest } from "../structured_output";
import type { StructuredOutputStreamEvent } from "../structured_output";

export interface StructuredOutputStreamTransport extends StreamTransport<StructuredOutputRequest, StructuredOutputStreamEvent> {}

export function generatestreamStructuredOutput(
    transport: StructuredOutputStreamTransport,
    req: StructuredOutputRequest,
): AsyncIterable<StructuredOutputStreamEvent> {
    return streamFactory(transport, req);
}
