/* eslint-disable */
/* GENERATED by idl/codegen/generate_streams.sh — DO NOT EDIT.
 * Source: idl/tts_options.proto
 * Template: idl/codegen/templates/ts_async_iterable.njk
 *
 * Provides an AsyncIterable<TTSStreamEvent> client
 * over an in-process server-streaming callback. The transport ("how a token
 * arrives in the JS heap") is platform-specific:
 *   - React Native: a Nitro HybridObject method whose callback fires once
 *     per server-streamed message.
 *   - Web: an Emscripten-emscripten Module.addFunction() callback.
 *
 * The platform adapter provides the `subscribe(req, onMessage, onError, onDone)`
 * function; this generated wrapper turns it into an AsyncIterable.
 */

import { streamFactory, type StreamTransport } from "./_streamFactory";
import type { TTSSynthesisRequest } from "../tts_options";
import type { TTSStreamEvent } from "../tts_options";

export interface TTSStreamTransport extends StreamTransport<TTSSynthesisRequest, TTSStreamEvent> {}

export function streamTTS(
    transport: TTSStreamTransport,
    req: TTSSynthesisRequest,
): AsyncIterable<TTSStreamEvent> {
    return streamFactory(transport, req);
}
