// GENERATED by idl/codegen/generate_ts_convenience.py — DO NOT EDIT.
//
// Source: idl/logging.proto
//
// Convenience helpers derived from RunAnywhere's `rac_*` proto
// annotations (see idl/rac_options.proto):
//   * `<enumName>WireString`         (rac_wire_string)
//   * `<enumName>FromWireString`     (reverse of rac_wire_string)
//   * `<enumName>DisplayName`        (rac_display_name)
//   * `<enumName>AnalyticsKey`       (rac_analytics_key)
//   * `<msgName>Defaults`            (rac_default)
//   * `validate<MsgName>`            (rac_required / rac_min / rac_max /
//                                     rac_min_float / rac_max_float)

/* eslint-disable */

import { LogLevel, LoggingConfiguration } from '../logging';

export const logLevelWireString = (e: LogLevel): string => {
  switch (e) {
    case LogLevel.LOG_LEVEL_TRACE:
      return 'trace';
    case LogLevel.LOG_LEVEL_DEBUG:
      return 'debug';
    case LogLevel.LOG_LEVEL_INFO:
      return 'info';
    case LogLevel.LOG_LEVEL_WARNING:
      return 'warning';
    case LogLevel.LOG_LEVEL_ERROR:
      return 'error';
    case LogLevel.LOG_LEVEL_FATAL:
      return 'fatal';
    default:
      return '';
  }
};

export const logLevelFromWireString = (s: string): LogLevel | undefined => {
  switch (s.toLowerCase()) {
    case 'trace':
      return LogLevel.LOG_LEVEL_TRACE;
    case 'debug':
      return LogLevel.LOG_LEVEL_DEBUG;
    case 'info':
      return LogLevel.LOG_LEVEL_INFO;
    case 'warning':
      return LogLevel.LOG_LEVEL_WARNING;
    case 'error':
      return LogLevel.LOG_LEVEL_ERROR;
    case 'fatal':
      return LogLevel.LOG_LEVEL_FATAL;
    default:
      return undefined;
  }
};

export const logLevelDisplayName = (e: LogLevel): string => {
  switch (e) {
    case LogLevel.LOG_LEVEL_TRACE:
      return 'Trace';
    case LogLevel.LOG_LEVEL_DEBUG:
      return 'Debug';
    case LogLevel.LOG_LEVEL_INFO:
      return 'Info';
    case LogLevel.LOG_LEVEL_WARNING:
      return 'Warning';
    case LogLevel.LOG_LEVEL_ERROR:
      return 'Error';
    case LogLevel.LOG_LEVEL_FATAL:
      return 'Fatal';
    default:
      return '';
  }
};

export const loggingConfigurationDefaults = (): LoggingConfiguration => ({
  enableLocalLogging: true,
  minLogLevel: 0,
  includeSourceLocation: false,
  includeDeviceMetadata: false,
  enableRemoteLogging: false,
});
