// GENERATED by idl/codegen/generate_ts_convenience.py — DO NOT EDIT.
//
// Source: idl/model_types.proto
//
// Convenience helpers derived from RunAnywhere's `rac_*` proto
// annotations (see idl/rac_options.proto):
//   * `<enumName>WireString`         (rac_wire_string)
//   * `<enumName>FromWireString`     (reverse of rac_wire_string)
//   * `<enumName>DisplayName`        (rac_display_name)
//   * `<enumName>AnalyticsKey`       (rac_analytics_key)
//   * `<msgName>Defaults`            (rac_default)
//   * `validate<MsgName>`            (rac_required / rac_min / rac_max /
//                                     rac_min_float / rac_max_float)

/* eslint-disable */

import { ArchiveStructure, AudioFormat, ModelCategory, ModelSource, SDKEnvironment } from '../model_types';

export const audioFormatWireString = (e: AudioFormat): string => {
  switch (e) {
    case AudioFormat.AUDIO_FORMAT_UNSPECIFIED:
      return 'unspecified';
    case AudioFormat.AUDIO_FORMAT_PCM:
      return 'pcm';
    case AudioFormat.AUDIO_FORMAT_WAV:
      return 'wav';
    case AudioFormat.AUDIO_FORMAT_MP3:
      return 'mp3';
    case AudioFormat.AUDIO_FORMAT_OPUS:
      return 'opus';
    case AudioFormat.AUDIO_FORMAT_AAC:
      return 'aac';
    case AudioFormat.AUDIO_FORMAT_FLAC:
      return 'flac';
    case AudioFormat.AUDIO_FORMAT_OGG:
      return 'ogg';
    case AudioFormat.AUDIO_FORMAT_M4A:
      return 'm4a';
    case AudioFormat.AUDIO_FORMAT_PCM_S16LE:
      return 'pcm_s16le';
    default:
      return '';
  }
};

export const audioFormatFromWireString = (s: string): AudioFormat | undefined => {
  switch (s.toLowerCase()) {
    case 'unspecified':
      return AudioFormat.AUDIO_FORMAT_UNSPECIFIED;
    case 'pcm':
      return AudioFormat.AUDIO_FORMAT_PCM;
    case 'wav':
      return AudioFormat.AUDIO_FORMAT_WAV;
    case 'mp3':
      return AudioFormat.AUDIO_FORMAT_MP3;
    case 'opus':
      return AudioFormat.AUDIO_FORMAT_OPUS;
    case 'aac':
      return AudioFormat.AUDIO_FORMAT_AAC;
    case 'flac':
      return AudioFormat.AUDIO_FORMAT_FLAC;
    case 'ogg':
      return AudioFormat.AUDIO_FORMAT_OGG;
    case 'm4a':
      return AudioFormat.AUDIO_FORMAT_M4A;
    case 'pcm_s16le':
      return AudioFormat.AUDIO_FORMAT_PCM_S16LE;
    default:
      return undefined;
  }
};

export const modelCategoryWireString = (e: ModelCategory): string => {
  switch (e) {
    case ModelCategory.MODEL_CATEGORY_UNSPECIFIED:
      return 'unspecified';
    case ModelCategory.MODEL_CATEGORY_LANGUAGE:
      return 'language';
    case ModelCategory.MODEL_CATEGORY_SPEECH_RECOGNITION:
      return 'speech-recognition';
    case ModelCategory.MODEL_CATEGORY_SPEECH_SYNTHESIS:
      return 'speech-synthesis';
    case ModelCategory.MODEL_CATEGORY_VISION:
      return 'vision';
    case ModelCategory.MODEL_CATEGORY_IMAGE_GENERATION:
      return 'image-generation';
    case ModelCategory.MODEL_CATEGORY_MULTIMODAL:
      return 'multimodal';
    case ModelCategory.MODEL_CATEGORY_AUDIO:
      return 'audio';
    case ModelCategory.MODEL_CATEGORY_EMBEDDING:
      return 'embedding';
    case ModelCategory.MODEL_CATEGORY_VOICE_ACTIVITY_DETECTION:
      return 'voice-activity-detection';
    default:
      return '';
  }
};

export const modelCategoryFromWireString = (s: string): ModelCategory | undefined => {
  switch (s.toLowerCase()) {
    case 'unspecified':
      return ModelCategory.MODEL_CATEGORY_UNSPECIFIED;
    case 'language':
      return ModelCategory.MODEL_CATEGORY_LANGUAGE;
    case 'speech-recognition':
      return ModelCategory.MODEL_CATEGORY_SPEECH_RECOGNITION;
    case 'speech-synthesis':
      return ModelCategory.MODEL_CATEGORY_SPEECH_SYNTHESIS;
    case 'vision':
      return ModelCategory.MODEL_CATEGORY_VISION;
    case 'image-generation':
      return ModelCategory.MODEL_CATEGORY_IMAGE_GENERATION;
    case 'multimodal':
      return ModelCategory.MODEL_CATEGORY_MULTIMODAL;
    case 'audio':
      return ModelCategory.MODEL_CATEGORY_AUDIO;
    case 'embedding':
      return ModelCategory.MODEL_CATEGORY_EMBEDDING;
    case 'voice-activity-detection':
      return ModelCategory.MODEL_CATEGORY_VOICE_ACTIVITY_DETECTION;
    default:
      return undefined;
  }
};

export const sDKEnvironmentWireString = (e: SDKEnvironment): string => {
  switch (e) {
    case SDKEnvironment.SDK_ENVIRONMENT_UNSPECIFIED:
      return 'unspecified';
    case SDKEnvironment.SDK_ENVIRONMENT_DEVELOPMENT:
      return 'development';
    case SDKEnvironment.SDK_ENVIRONMENT_STAGING:
      return 'staging';
    case SDKEnvironment.SDK_ENVIRONMENT_PRODUCTION:
      return 'production';
    default:
      return '';
  }
};

export const sDKEnvironmentFromWireString = (s: string): SDKEnvironment | undefined => {
  switch (s.toLowerCase()) {
    case 'unspecified':
      return SDKEnvironment.SDK_ENVIRONMENT_UNSPECIFIED;
    case 'development':
      return SDKEnvironment.SDK_ENVIRONMENT_DEVELOPMENT;
    case 'staging':
      return SDKEnvironment.SDK_ENVIRONMENT_STAGING;
    case 'production':
      return SDKEnvironment.SDK_ENVIRONMENT_PRODUCTION;
    default:
      return undefined;
  }
};

export const modelSourceWireString = (e: ModelSource): string => {
  switch (e) {
    case ModelSource.MODEL_SOURCE_UNSPECIFIED:
      return 'unspecified';
    case ModelSource.MODEL_SOURCE_REMOTE:
      return 'remote';
    case ModelSource.MODEL_SOURCE_LOCAL:
      return 'local';
    case ModelSource.MODEL_SOURCE_BUILT_IN:
      return 'built-in';
    default:
      return '';
  }
};

export const modelSourceFromWireString = (s: string): ModelSource | undefined => {
  switch (s.toLowerCase()) {
    case 'unspecified':
      return ModelSource.MODEL_SOURCE_UNSPECIFIED;
    case 'remote':
      return ModelSource.MODEL_SOURCE_REMOTE;
    case 'local':
      return ModelSource.MODEL_SOURCE_LOCAL;
    case 'built-in':
      return ModelSource.MODEL_SOURCE_BUILT_IN;
    default:
      return undefined;
  }
};

export const archiveStructureWireString = (e: ArchiveStructure): string => {
  switch (e) {
    case ArchiveStructure.ARCHIVE_STRUCTURE_UNSPECIFIED:
      return 'unspecified';
    case ArchiveStructure.ARCHIVE_STRUCTURE_SINGLE_FILE_NESTED:
      return 'singleFileNested';
    case ArchiveStructure.ARCHIVE_STRUCTURE_DIRECTORY_BASED:
      return 'directoryBased';
    case ArchiveStructure.ARCHIVE_STRUCTURE_NESTED_DIRECTORY:
      return 'nestedDirectory';
    case ArchiveStructure.ARCHIVE_STRUCTURE_UNKNOWN:
      return 'unknown';
    default:
      return '';
  }
};

export const archiveStructureFromWireString = (s: string): ArchiveStructure | undefined => {
  switch (s.toLowerCase()) {
    case 'unspecified':
      return ArchiveStructure.ARCHIVE_STRUCTURE_UNSPECIFIED;
    case 'singlefilenested':
      return ArchiveStructure.ARCHIVE_STRUCTURE_SINGLE_FILE_NESTED;
    case 'directorybased':
      return ArchiveStructure.ARCHIVE_STRUCTURE_DIRECTORY_BASED;
    case 'nesteddirectory':
      return ArchiveStructure.ARCHIVE_STRUCTURE_NESTED_DIRECTORY;
    case 'unknown':
      return ArchiveStructure.ARCHIVE_STRUCTURE_UNKNOWN;
    default:
      return undefined;
  }
};
