#!/usr/bin/env bash
# Sync canonical commons solution YAMLs into a generated Kotlin module.
#
# Reads sdk/runanywhere-commons/examples/solutions/{voice_agent,rag}.yaml and
# emits app/src/main/java/.../solutions/SolutionsYaml.kt so the Solutions
# screen never embeds drift-prone inline copies.
#
#   bash scripts/sync-solutions-yamls.sh            # regenerate
#   bash scripts/sync-solutions-yamls.sh --check    # fail if out of date
#
# Editing the generated file is forbidden; modify the commons YAMLs instead.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
REPO_ROOT="$(cd "${APP_DIR}/../../.." && pwd)"
SOLUTIONS_DIR="${REPO_ROOT}/sdk/runanywhere-commons/examples/solutions"
OUTPUT_FILE="${APP_DIR}/app/src/main/java/com/runanywhere/runanywhereai/ui/screens/solutions/SolutionsYaml.kt"

for f in voice_agent.yaml rag.yaml; do
    if [ ! -f "${SOLUTIONS_DIR}/${f}" ]; then
        echo "error: commons solution YAML not found: ${SOLUTIONS_DIR}/${f}" >&2
        exit 1
    fi
    if grep -q '"""' "${SOLUTIONS_DIR}/${f}" || grep -q '[$]' "${SOLUTIONS_DIR}/${f}"; then
        echo "error: ${SOLUTIONS_DIR}/${f} contains a token that must be escaped before embedding in a Kotlin raw string." >&2
        exit 1
    fi
done

mkdir -p "$(dirname "${OUTPUT_FILE}")"

TMP_FILE="$(mktemp)"
trap 'rm -f "${TMP_FILE}"' EXIT

{
    echo "package com.runanywhere.runanywhereai.ui.screens.solutions"
    echo ""
    echo "// AUTO-GENERATED by examples/android/RunAnywhereAI/scripts/sync-solutions-yamls.sh"
    echo "// Do not edit by hand. Source of truth: sdk/runanywhere-commons/examples/solutions/*.yaml"
    echo "// Regenerate via \`bash scripts/sync-solutions-yamls.sh\`."
    echo "object SolutionsYaml {"
    echo ""
    echo "    // Sourced from sdk/runanywhere-commons/examples/solutions/voice_agent.yaml"
    echo '    const val VOICE_AGENT = """'
    cat "${SOLUTIONS_DIR}/voice_agent.yaml"
    echo '"""'
    echo ""
    echo "    // Sourced from sdk/runanywhere-commons/examples/solutions/rag.yaml"
    echo '    const val RAG = """'
    cat "${SOLUTIONS_DIR}/rag.yaml"
    echo '"""'
    echo "}"
} > "${TMP_FILE}"

if [ "${1:-}" = "--check" ]; then
    if ! diff -q "${TMP_FILE}" "${OUTPUT_FILE}" >/dev/null 2>&1; then
        echo "error: ${OUTPUT_FILE} is out of sync with commons solution YAMLs." >&2
        echo "       Run: bash examples/android/RunAnywhereAI/scripts/sync-solutions-yamls.sh" >&2
        exit 1
    fi
    echo "SolutionsYaml.kt is in sync."
    exit 0
fi

mv "${TMP_FILE}" "${OUTPUT_FILE}"
trap - EXIT
echo "wrote ${OUTPUT_FILE}"
