#!/usr/bin/env bash
# Sync canonical commons solution YAMLs into a generated Dart library.
#
# Mirrors examples/ios/RunAnywhereAI/scripts/sync-solutions-yamls.sh and
# examples/react-native/RunAnywhereAI/scripts/sync-solutions-yamls.js:
# reads sdk/runanywhere-commons/examples/solutions/{voice_agent,rag}.yaml and
# emits lib/generated/solutions_yaml.dart so the Solutions screen never
# embeds drift-prone inline copies.
#
#   bash scripts/sync-solutions-yamls.sh            # regenerate
#   bash scripts/sync-solutions-yamls.sh --check    # fail if out of date (CI)
#
# Editing the generated file is forbidden; modify the commons YAMLs instead.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
REPO_ROOT="$(cd "${APP_DIR}/../../.." && pwd)"
SOLUTIONS_DIR="${REPO_ROOT}/sdk/runanywhere-commons/examples/solutions"
OUTPUT_FILE="${APP_DIR}/lib/generated/solutions_yaml.dart"

for f in voice_agent.yaml rag.yaml; do
    if [ ! -f "${SOLUTIONS_DIR}/${f}" ]; then
        echo "error: commons solution YAML not found: ${SOLUTIONS_DIR}/${f}" >&2
        exit 1
    fi
done

mkdir -p "$(dirname "${OUTPUT_FILE}")"

TMP_FILE="$(mktemp)"
trap 'rm -f "${TMP_FILE}"' EXIT

{
    echo "// AUTO-GENERATED by examples/flutter/RunAnywhereAI/scripts/sync-solutions-yamls.sh"
    echo "// Do not edit by hand. Source of truth: sdk/runanywhere-commons/examples/solutions/*.yaml"
    echo "// Regenerate via \`bash scripts/sync-solutions-yamls.sh\`."
    echo ""
    echo "abstract final class SolutionsYaml {"
    echo "  // Sourced from sdk/runanywhere-commons/examples/solutions/voice_agent.yaml"
    echo "  static const String voiceAgent = r'''"
    cat "${SOLUTIONS_DIR}/voice_agent.yaml"
    echo "''';"
    echo ""
    echo "  // Sourced from sdk/runanywhere-commons/examples/solutions/rag.yaml"
    echo "  static const String rag = r'''"
    cat "${SOLUTIONS_DIR}/rag.yaml"
    echo "''';"
    echo "}"
} > "${TMP_FILE}"

if [ "${1:-}" = "--check" ]; then
    if ! diff -q "${TMP_FILE}" "${OUTPUT_FILE}" >/dev/null 2>&1; then
        echo "error: ${OUTPUT_FILE} is out of sync with commons solution YAMLs." >&2
        echo "       Run: bash examples/flutter/RunAnywhereAI/scripts/sync-solutions-yamls.sh" >&2
        exit 1
    fi
    echo "solutions_yaml.dart is in sync."
    exit 0
fi

mv "${TMP_FILE}" "${OUTPUT_FILE}"
trap - EXIT
echo "wrote ${OUTPUT_FILE}"
