package com.runanywhere.runanywhereai.ui.screens.solutions

// AUTO-GENERATED by examples/android/RunAnywhereAI/scripts/sync-solutions-yamls.sh
// Do not edit by hand. Source of truth: sdk/runanywhere-commons/examples/solutions/*.yaml
// Regenerate via `bash scripts/sync-solutions-yamls.sh`.
object SolutionsYaml {

    // Sourced from sdk/runanywhere-commons/examples/solutions/voice_agent.yaml
    const val VOICE_AGENT = """
# RunAnywhere Solution — canonical voice agent.
#
# Matches the VAD → STT → LLM → TTS DAG built by the hand-rolled
# voice_agent_pipeline.cpp; SolutionRunner compiles this YAML into an
# equivalent GraphScheduler graph via PipelineExecutor.
#
# Consumed by rac_solution_create_from_yaml(). The top-level
# `voice_agent:` key selects the SolutionConfig.voice_agent oneof arm;
# field names mirror solutions.proto's VoiceAgentConfig.
#
# Model IDs match the canonical catalog seeded by every example app
# (iOS, Android, Flutter, React Native, Web). This lets all 5 example
# apps feed this file to RunAnywhere.solutions.run without rewriting
# the model identifiers inline.

voice_agent:
  llm_model_id: "smollm2-360m-q8_0"
  stt_model_id: "sherpa-onnx-whisper-tiny.en"
  tts_model_id: "vits-piper-en_US-lessac-medium"
  vad_model_id: "silero-vad"

  sample_rate_hz: 16000
  chunk_ms: 20
  audio_source: "microphone"

  enable_barge_in: true
  barge_in_threshold_ms: 200

  system_prompt: "You are a helpful voice assistant. Keep answers concise."
  max_context_tokens: 4096
  temperature: 0.7

  emit_partials: true
  emit_thoughts: false
"""

    // Sourced from sdk/runanywhere-commons/examples/solutions/rag.yaml
    const val RAG = """
# RunAnywhere Solution — retrieval-augmented generation.
#
# Mirrors the Query → Embed → Retrieve → ContextBuild → LLM DAG T4.6
# landed. SolutionRunner expands this into a PipelineSpec (see
# solution_converter.cpp::expand_rag) and compiles it into a
# GraphScheduler graph.
#
# Model IDs match the canonical catalog seeded by every example app
# (iOS, Android, Flutter, React Native, Web). rerank_model_id is
# intentionally omitted: no example app seeds a reranker, and
# solution_converter.cpp treats an empty rerank_model_id as "skip
# reranking" (only adds it to params when non-empty).

rag:
  embed_model_id: "all-minilm-l6-v2"
  llm_model_id: "smollm2-360m-q8_0"

  vector_store: "usearch"
  vector_store_path: "/tmp/ra-rag.usearch"

  retrieve_k: 24
  rerank_top: 6

  bm25_k1: 1.2
  bm25_b: 0.75
  rrf_k: 60

  prompt_template: "Use the context below to answer.\n\nContext:\n{{context}}\n\nQuestion: {{query}}"
"""
}
