// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.35.1
// source: device_info.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "runanywhere.v1";

export interface DeviceInfo {
  /** e.g. "iPhone16,2", "Pixel 8 Pro". */
  deviceModel: string;
  /** User-facing device name. */
  deviceName: string;
  /** "ios" | "android" | "macos" | "web" | ... */
  platform: string;
  osVersion: string;
  /** "phone" | "tablet" | "desktop" | ... */
  formFactor: string;
  /** "arm64" | "x86_64" | "wasm32" | ... */
  architecture: string;
  /** e.g. "Apple A17 Pro". */
  chipName: string;
  /** Bytes. */
  totalMemory: number;
  /** Bytes. */
  availableMemory: number;
  hasNeuralEngine: boolean;
  neuralEngineCores: number;
  gpuFamily: string;
  /** 0.0–1.0; unset when unavailable. */
  batteryLevel?:
    | number
    | undefined;
  /** "charging" | "unplugged" | "full" | ... */
  batteryState?: string | undefined;
  isLowPowerMode: boolean;
  coreCount: number;
  performanceCores: number;
  efficiencyCores: number;
  deviceFingerprint?:
    | string
    | undefined;
  /**
   * Platform-specific fields that are not part of the cross-SDK core
   * (e.g. web: "has_webgpu", "has_shared_array_buffer"; android: "manufacturer",
   * "android_api_level", "os_build_id", ...).
   */
  platformExtras: { [key: string]: string };
}

export interface DeviceInfo_PlatformExtrasEntry {
  key: string;
  value: string;
}

function createBaseDeviceInfo(): DeviceInfo {
  return {
    deviceModel: "",
    deviceName: "",
    platform: "",
    osVersion: "",
    formFactor: "",
    architecture: "",
    chipName: "",
    totalMemory: 0,
    availableMemory: 0,
    hasNeuralEngine: false,
    neuralEngineCores: 0,
    gpuFamily: "",
    batteryLevel: undefined,
    batteryState: undefined,
    isLowPowerMode: false,
    coreCount: 0,
    performanceCores: 0,
    efficiencyCores: 0,
    deviceFingerprint: undefined,
    platformExtras: {},
  };
}

export const DeviceInfo: MessageFns<DeviceInfo> = {
  encode(message: DeviceInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.deviceModel !== "") {
      writer.uint32(10).string(message.deviceModel);
    }
    if (message.deviceName !== "") {
      writer.uint32(18).string(message.deviceName);
    }
    if (message.platform !== "") {
      writer.uint32(26).string(message.platform);
    }
    if (message.osVersion !== "") {
      writer.uint32(34).string(message.osVersion);
    }
    if (message.formFactor !== "") {
      writer.uint32(42).string(message.formFactor);
    }
    if (message.architecture !== "") {
      writer.uint32(50).string(message.architecture);
    }
    if (message.chipName !== "") {
      writer.uint32(58).string(message.chipName);
    }
    if (message.totalMemory !== 0) {
      writer.uint32(64).int64(message.totalMemory);
    }
    if (message.availableMemory !== 0) {
      writer.uint32(72).int64(message.availableMemory);
    }
    if (message.hasNeuralEngine !== false) {
      writer.uint32(80).bool(message.hasNeuralEngine);
    }
    if (message.neuralEngineCores !== 0) {
      writer.uint32(88).int32(message.neuralEngineCores);
    }
    if (message.gpuFamily !== "") {
      writer.uint32(98).string(message.gpuFamily);
    }
    if (message.batteryLevel !== undefined) {
      writer.uint32(109).float(message.batteryLevel);
    }
    if (message.batteryState !== undefined) {
      writer.uint32(114).string(message.batteryState);
    }
    if (message.isLowPowerMode !== false) {
      writer.uint32(120).bool(message.isLowPowerMode);
    }
    if (message.coreCount !== 0) {
      writer.uint32(128).int32(message.coreCount);
    }
    if (message.performanceCores !== 0) {
      writer.uint32(136).int32(message.performanceCores);
    }
    if (message.efficiencyCores !== 0) {
      writer.uint32(144).int32(message.efficiencyCores);
    }
    if (message.deviceFingerprint !== undefined) {
      writer.uint32(154).string(message.deviceFingerprint);
    }
    globalThis.Object.entries(message.platformExtras).forEach(([key, value]: [string, string]) => {
      DeviceInfo_PlatformExtrasEntry.encode({ key: key as any, value }, writer.uint32(162).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeviceInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeviceInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.deviceModel = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.deviceName = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.platform = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.osVersion = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.formFactor = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.architecture = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.chipName = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.totalMemory = longToNumber(reader.int64());
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.availableMemory = longToNumber(reader.int64());
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.hasNeuralEngine = reader.bool();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.neuralEngineCores = reader.int32();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.gpuFamily = reader.string();
          continue;
        }
        case 13: {
          if (tag !== 109) {
            break;
          }

          message.batteryLevel = reader.float();
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          message.batteryState = reader.string();
          continue;
        }
        case 15: {
          if (tag !== 120) {
            break;
          }

          message.isLowPowerMode = reader.bool();
          continue;
        }
        case 16: {
          if (tag !== 128) {
            break;
          }

          message.coreCount = reader.int32();
          continue;
        }
        case 17: {
          if (tag !== 136) {
            break;
          }

          message.performanceCores = reader.int32();
          continue;
        }
        case 18: {
          if (tag !== 144) {
            break;
          }

          message.efficiencyCores = reader.int32();
          continue;
        }
        case 19: {
          if (tag !== 154) {
            break;
          }

          message.deviceFingerprint = reader.string();
          continue;
        }
        case 20: {
          if (tag !== 162) {
            break;
          }

          const entry20 = DeviceInfo_PlatformExtrasEntry.decode(reader, reader.uint32());
          if (entry20.value !== undefined) {
            message.platformExtras[entry20.key] = entry20.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeviceInfo {
    return {
      deviceModel: isSet(object.deviceModel)
        ? globalThis.String(object.deviceModel)
        : isSet(object.device_model)
        ? globalThis.String(object.device_model)
        : "",
      deviceName: isSet(object.deviceName)
        ? globalThis.String(object.deviceName)
        : isSet(object.device_name)
        ? globalThis.String(object.device_name)
        : "",
      platform: isSet(object.platform) ? globalThis.String(object.platform) : "",
      osVersion: isSet(object.osVersion)
        ? globalThis.String(object.osVersion)
        : isSet(object.os_version)
        ? globalThis.String(object.os_version)
        : "",
      formFactor: isSet(object.formFactor)
        ? globalThis.String(object.formFactor)
        : isSet(object.form_factor)
        ? globalThis.String(object.form_factor)
        : "",
      architecture: isSet(object.architecture) ? globalThis.String(object.architecture) : "",
      chipName: isSet(object.chipName)
        ? globalThis.String(object.chipName)
        : isSet(object.chip_name)
        ? globalThis.String(object.chip_name)
        : "",
      totalMemory: isSet(object.totalMemory)
        ? globalThis.Number(object.totalMemory)
        : isSet(object.total_memory)
        ? globalThis.Number(object.total_memory)
        : 0,
      availableMemory: isSet(object.availableMemory)
        ? globalThis.Number(object.availableMemory)
        : isSet(object.available_memory)
        ? globalThis.Number(object.available_memory)
        : 0,
      hasNeuralEngine: isSet(object.hasNeuralEngine)
        ? globalThis.Boolean(object.hasNeuralEngine)
        : isSet(object.has_neural_engine)
        ? globalThis.Boolean(object.has_neural_engine)
        : false,
      neuralEngineCores: isSet(object.neuralEngineCores)
        ? globalThis.Number(object.neuralEngineCores)
        : isSet(object.neural_engine_cores)
        ? globalThis.Number(object.neural_engine_cores)
        : 0,
      gpuFamily: isSet(object.gpuFamily)
        ? globalThis.String(object.gpuFamily)
        : isSet(object.gpu_family)
        ? globalThis.String(object.gpu_family)
        : "",
      batteryLevel: isSet(object.batteryLevel)
        ? globalThis.Number(object.batteryLevel)
        : isSet(object.battery_level)
        ? globalThis.Number(object.battery_level)
        : undefined,
      batteryState: isSet(object.batteryState)
        ? globalThis.String(object.batteryState)
        : isSet(object.battery_state)
        ? globalThis.String(object.battery_state)
        : undefined,
      isLowPowerMode: isSet(object.isLowPowerMode)
        ? globalThis.Boolean(object.isLowPowerMode)
        : isSet(object.is_low_power_mode)
        ? globalThis.Boolean(object.is_low_power_mode)
        : false,
      coreCount: isSet(object.coreCount)
        ? globalThis.Number(object.coreCount)
        : isSet(object.core_count)
        ? globalThis.Number(object.core_count)
        : 0,
      performanceCores: isSet(object.performanceCores)
        ? globalThis.Number(object.performanceCores)
        : isSet(object.performance_cores)
        ? globalThis.Number(object.performance_cores)
        : 0,
      efficiencyCores: isSet(object.efficiencyCores)
        ? globalThis.Number(object.efficiencyCores)
        : isSet(object.efficiency_cores)
        ? globalThis.Number(object.efficiency_cores)
        : 0,
      deviceFingerprint: isSet(object.deviceFingerprint)
        ? globalThis.String(object.deviceFingerprint)
        : isSet(object.device_fingerprint)
        ? globalThis.String(object.device_fingerprint)
        : undefined,
      platformExtras: isObject(object.platformExtras)
        ? (globalThis.Object.entries(object.platformExtras) as [string, any][]).reduce(
          (acc: { [key: string]: string }, [key, value]: [string, any]) => {
            acc[key] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : isObject(object.platform_extras)
        ? (globalThis.Object.entries(object.platform_extras) as [string, any][]).reduce(
          (acc: { [key: string]: string }, [key, value]: [string, any]) => {
            acc[key] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : {},
    };
  },

  toJSON(message: DeviceInfo): unknown {
    const obj: any = {};
    if (message.deviceModel !== "") {
      obj.deviceModel = message.deviceModel;
    }
    if (message.deviceName !== "") {
      obj.deviceName = message.deviceName;
    }
    if (message.platform !== "") {
      obj.platform = message.platform;
    }
    if (message.osVersion !== "") {
      obj.osVersion = message.osVersion;
    }
    if (message.formFactor !== "") {
      obj.formFactor = message.formFactor;
    }
    if (message.architecture !== "") {
      obj.architecture = message.architecture;
    }
    if (message.chipName !== "") {
      obj.chipName = message.chipName;
    }
    if (message.totalMemory !== 0) {
      obj.totalMemory = Math.round(message.totalMemory);
    }
    if (message.availableMemory !== 0) {
      obj.availableMemory = Math.round(message.availableMemory);
    }
    if (message.hasNeuralEngine !== false) {
      obj.hasNeuralEngine = message.hasNeuralEngine;
    }
    if (message.neuralEngineCores !== 0) {
      obj.neuralEngineCores = Math.round(message.neuralEngineCores);
    }
    if (message.gpuFamily !== "") {
      obj.gpuFamily = message.gpuFamily;
    }
    if (message.batteryLevel !== undefined) {
      obj.batteryLevel = message.batteryLevel;
    }
    if (message.batteryState !== undefined) {
      obj.batteryState = message.batteryState;
    }
    if (message.isLowPowerMode !== false) {
      obj.isLowPowerMode = message.isLowPowerMode;
    }
    if (message.coreCount !== 0) {
      obj.coreCount = Math.round(message.coreCount);
    }
    if (message.performanceCores !== 0) {
      obj.performanceCores = Math.round(message.performanceCores);
    }
    if (message.efficiencyCores !== 0) {
      obj.efficiencyCores = Math.round(message.efficiencyCores);
    }
    if (message.deviceFingerprint !== undefined) {
      obj.deviceFingerprint = message.deviceFingerprint;
    }
    if (message.platformExtras) {
      const entries = globalThis.Object.entries(message.platformExtras) as [string, string][];
      if (entries.length > 0) {
        obj.platformExtras = {};
        entries.forEach(([k, v]) => {
          obj.platformExtras[k] = v;
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeviceInfo>, I>>(base?: I): DeviceInfo {
    return DeviceInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeviceInfo>, I>>(object: I): DeviceInfo {
    const message = createBaseDeviceInfo();
    message.deviceModel = object.deviceModel ?? "";
    message.deviceName = object.deviceName ?? "";
    message.platform = object.platform ?? "";
    message.osVersion = object.osVersion ?? "";
    message.formFactor = object.formFactor ?? "";
    message.architecture = object.architecture ?? "";
    message.chipName = object.chipName ?? "";
    message.totalMemory = object.totalMemory ?? 0;
    message.availableMemory = object.availableMemory ?? 0;
    message.hasNeuralEngine = object.hasNeuralEngine ?? false;
    message.neuralEngineCores = object.neuralEngineCores ?? 0;
    message.gpuFamily = object.gpuFamily ?? "";
    message.batteryLevel = object.batteryLevel ?? undefined;
    message.batteryState = object.batteryState ?? undefined;
    message.isLowPowerMode = object.isLowPowerMode ?? false;
    message.coreCount = object.coreCount ?? 0;
    message.performanceCores = object.performanceCores ?? 0;
    message.efficiencyCores = object.efficiencyCores ?? 0;
    message.deviceFingerprint = object.deviceFingerprint ?? undefined;
    message.platformExtras = (globalThis.Object.entries(object.platformExtras ?? {}) as [string, string][]).reduce(
      (acc: { [key: string]: string }, [key, value]: [string, string]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    return message;
  },
};

function createBaseDeviceInfo_PlatformExtrasEntry(): DeviceInfo_PlatformExtrasEntry {
  return { key: "", value: "" };
}

export const DeviceInfo_PlatformExtrasEntry: MessageFns<DeviceInfo_PlatformExtrasEntry> = {
  encode(message: DeviceInfo_PlatformExtrasEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeviceInfo_PlatformExtrasEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeviceInfo_PlatformExtrasEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeviceInfo_PlatformExtrasEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: DeviceInfo_PlatformExtrasEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeviceInfo_PlatformExtrasEntry>, I>>(base?: I): DeviceInfo_PlatformExtrasEntry {
    return DeviceInfo_PlatformExtrasEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeviceInfo_PlatformExtrasEntry>, I>>(
    object: I,
  ): DeviceInfo_PlatformExtrasEntry {
    const message = createBaseDeviceInfo_PlatformExtrasEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
