// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.35.1
// source: plugin_loader.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "runanywhere.v1";

/**
 * A loaded/registered plugin. `path` is empty for plugins the native registry
 * reports by name only (it does not persist load paths) — proto3 string
 * default "" matches the current `path: ""` placeholder.
 */
export interface PluginInfo {
  name: string;
  path: string;
}

/** Result of the plugin-list bridge calls (registeredNames / listLoaded). */
export interface PluginInfoList {
  plugins: PluginInfo[];
}

function createBasePluginInfo(): PluginInfo {
  return { name: "", path: "" };
}

export const PluginInfo: MessageFns<PluginInfo> = {
  encode(message: PluginInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.path !== "") {
      writer.uint32(18).string(message.path);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PluginInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePluginInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.path = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PluginInfo {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      path: isSet(object.path) ? globalThis.String(object.path) : "",
    };
  },

  toJSON(message: PluginInfo): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.path !== "") {
      obj.path = message.path;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PluginInfo>, I>>(base?: I): PluginInfo {
    return PluginInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PluginInfo>, I>>(object: I): PluginInfo {
    const message = createBasePluginInfo();
    message.name = object.name ?? "";
    message.path = object.path ?? "";
    return message;
  },
};

function createBasePluginInfoList(): PluginInfoList {
  return { plugins: [] };
}

export const PluginInfoList: MessageFns<PluginInfoList> = {
  encode(message: PluginInfoList, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.plugins) {
      PluginInfo.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PluginInfoList {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePluginInfoList();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.plugins.push(PluginInfo.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PluginInfoList {
    return {
      plugins: globalThis.Array.isArray(object?.plugins) ? object.plugins.map((e: any) => PluginInfo.fromJSON(e)) : [],
    };
  },

  toJSON(message: PluginInfoList): unknown {
    const obj: any = {};
    if (message.plugins?.length) {
      obj.plugins = message.plugins.map((e) => PluginInfo.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PluginInfoList>, I>>(base?: I): PluginInfoList {
    return PluginInfoList.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PluginInfoList>, I>>(object: I): PluginInfoList {
    const message = createBasePluginInfoList();
    message.plugins = object.plugins?.map((e) => PluginInfo.fromPartial(e)) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
