// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.35.1
// source: rac_options.proto

/* eslint-disable */

export const protobufPackage = "runanywhere.v1";
