// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.35.1
// source: router.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { InferenceFramework, inferenceFrameworkFromJSON, inferenceFrameworkToJSON } from "./model_types";
import { SDKComponent, sDKComponentFromJSON, sDKComponentToJSON } from "./sdk_events";

export const protobufPackage = "runanywhere.v1";

/**
 * ---------------------------------------------------------------------------
 * Request: ask commons which frameworks can serve a given SDK component.
 * Maps to the engine-router plugin registry (not the model registry); this
 * answers "which engines CAN run this capability on this host" independent
 * of whether any matching model has been registered yet.
 * ---------------------------------------------------------------------------
 */
export interface FrameworksForCapabilityRequest {
  component: SDKComponent;
}

/**
 * ---------------------------------------------------------------------------
 * Response: ordered list of inference frameworks. Ordering matches the
 * engine-router's priority-descending scan of registered plugins for the
 * primitive(s) mapped from `component`. Duplicates are removed while
 * preserving first-seen order.
 * ---------------------------------------------------------------------------
 */
export interface FrameworksForCapabilityResponse {
  frameworks: InferenceFramework[];
}

function createBaseFrameworksForCapabilityRequest(): FrameworksForCapabilityRequest {
  return { component: 0 };
}

export const FrameworksForCapabilityRequest: MessageFns<FrameworksForCapabilityRequest> = {
  encode(message: FrameworksForCapabilityRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.component !== 0) {
      writer.uint32(8).int32(message.component);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FrameworksForCapabilityRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFrameworksForCapabilityRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.component = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FrameworksForCapabilityRequest {
    return { component: isSet(object.component) ? sDKComponentFromJSON(object.component) : 0 };
  },

  toJSON(message: FrameworksForCapabilityRequest): unknown {
    const obj: any = {};
    if (message.component !== 0) {
      obj.component = sDKComponentToJSON(message.component);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FrameworksForCapabilityRequest>, I>>(base?: I): FrameworksForCapabilityRequest {
    return FrameworksForCapabilityRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FrameworksForCapabilityRequest>, I>>(
    object: I,
  ): FrameworksForCapabilityRequest {
    const message = createBaseFrameworksForCapabilityRequest();
    message.component = object.component ?? 0;
    return message;
  },
};

function createBaseFrameworksForCapabilityResponse(): FrameworksForCapabilityResponse {
  return { frameworks: [] };
}

export const FrameworksForCapabilityResponse: MessageFns<FrameworksForCapabilityResponse> = {
  encode(message: FrameworksForCapabilityResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    writer.uint32(10).fork();
    for (const v of message.frameworks) {
      writer.int32(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FrameworksForCapabilityResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFrameworksForCapabilityResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag === 8) {
            message.frameworks.push(reader.int32() as any);

            continue;
          }

          if (tag === 10) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.frameworks.push(reader.int32() as any);
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FrameworksForCapabilityResponse {
    return {
      frameworks: globalThis.Array.isArray(object?.frameworks)
        ? object.frameworks.map((e: any) => inferenceFrameworkFromJSON(e))
        : [],
    };
  },

  toJSON(message: FrameworksForCapabilityResponse): unknown {
    const obj: any = {};
    if (message.frameworks?.length) {
      obj.frameworks = message.frameworks.map((e) => inferenceFrameworkToJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FrameworksForCapabilityResponse>, I>>(base?: I): FrameworksForCapabilityResponse {
    return FrameworksForCapabilityResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FrameworksForCapabilityResponse>, I>>(
    object: I,
  ): FrameworksForCapabilityResponse {
    const message = createBaseFrameworksForCapabilityResponse();
    message.frameworks = object.frameworks?.map((e) => e) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
