// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.35.1
// source: storage_types.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "runanywhere.v1";

/**
 * ---------------------------------------------------------------------------
 * NPU chipset detected on the host device. Used to drive vendor-NPU
 * model-download URL selection and runtime backend wiring.
 * ---------------------------------------------------------------------------
 */
export enum NPUChip {
  NPU_CHIP_UNSPECIFIED = 0,
  /** NPU_CHIP_NONE - No NPU detected on this device */
  NPU_CHIP_NONE = 1,
  /** NPU_CHIP_APPLE_NEURAL_ENGINE - Apple Neural Engine (A-series / M-series) */
  NPU_CHIP_APPLE_NEURAL_ENGINE = 2,
  /** NPU_CHIP_QUALCOMM_HEXAGON - Snapdragon 8 Elite, 8 Elite Gen 5, etc. */
  NPU_CHIP_QUALCOMM_HEXAGON = 3,
  /** NPU_CHIP_MEDIATEK_APU - MediaTek Dimensity APU */
  NPU_CHIP_MEDIATEK_APU = 4,
  /** NPU_CHIP_GOOGLE_TPU - Pixel Tensor / TPU */
  NPU_CHIP_GOOGLE_TPU = 5,
  /** NPU_CHIP_INTEL_NPU - Intel Core Ultra NPU */
  NPU_CHIP_INTEL_NPU = 6,
  /** NPU_CHIP_OTHER - Detected NPU but vendor unmapped */
  NPU_CHIP_OTHER = 99,
  UNRECOGNIZED = -1,
}

export function nPUChipFromJSON(object: any): NPUChip {
  switch (object) {
    case 0:
    case "NPU_CHIP_UNSPECIFIED":
      return NPUChip.NPU_CHIP_UNSPECIFIED;
    case 1:
    case "NPU_CHIP_NONE":
      return NPUChip.NPU_CHIP_NONE;
    case 2:
    case "NPU_CHIP_APPLE_NEURAL_ENGINE":
      return NPUChip.NPU_CHIP_APPLE_NEURAL_ENGINE;
    case 3:
    case "NPU_CHIP_QUALCOMM_HEXAGON":
      return NPUChip.NPU_CHIP_QUALCOMM_HEXAGON;
    case 4:
    case "NPU_CHIP_MEDIATEK_APU":
      return NPUChip.NPU_CHIP_MEDIATEK_APU;
    case 5:
    case "NPU_CHIP_GOOGLE_TPU":
      return NPUChip.NPU_CHIP_GOOGLE_TPU;
    case 6:
    case "NPU_CHIP_INTEL_NPU":
      return NPUChip.NPU_CHIP_INTEL_NPU;
    case 99:
    case "NPU_CHIP_OTHER":
      return NPUChip.NPU_CHIP_OTHER;
    case -1:
    case "UNRECOGNIZED":
    default:
      return NPUChip.UNRECOGNIZED;
  }
}

export function nPUChipToJSON(object: NPUChip): string {
  switch (object) {
    case NPUChip.NPU_CHIP_UNSPECIFIED:
      return "NPU_CHIP_UNSPECIFIED";
    case NPUChip.NPU_CHIP_NONE:
      return "NPU_CHIP_NONE";
    case NPUChip.NPU_CHIP_APPLE_NEURAL_ENGINE:
      return "NPU_CHIP_APPLE_NEURAL_ENGINE";
    case NPUChip.NPU_CHIP_QUALCOMM_HEXAGON:
      return "NPU_CHIP_QUALCOMM_HEXAGON";
    case NPUChip.NPU_CHIP_MEDIATEK_APU:
      return "NPU_CHIP_MEDIATEK_APU";
    case NPUChip.NPU_CHIP_GOOGLE_TPU:
      return "NPU_CHIP_GOOGLE_TPU";
    case NPUChip.NPU_CHIP_INTEL_NPU:
      return "NPU_CHIP_INTEL_NPU";
    case NPUChip.NPU_CHIP_OTHER:
      return "NPU_CHIP_OTHER";
    case NPUChip.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/**
 * ---------------------------------------------------------------------------
 * Whole-device storage capacity. Reported by the platform OS (e.g. iOS
 * `URLResourceKey.volumeAvailableCapacity*`, Android `StatFs`, browser
 * `navigator.storage.estimate()`).
 *
 * `used_percent` is materialized rather than computed at the receiver so
 * every binding (Swift, Kotlin, Dart, RN, Web) reports the same number even
 * when total_bytes == 0 (in which case used_percent MUST be 0.0).
 *
 * Sources pre-IDL: see header drift table.
 * ---------------------------------------------------------------------------
 */
export interface DeviceStorageInfo {
  totalBytes: number;
  freeBytes: number;
  usedBytes: number;
  /** 0.0 — 100.0; 0.0 if total_bytes == 0 */
  usedPercent: number;
}

/**
 * ---------------------------------------------------------------------------
 * Per-app storage breakdown by directory type. Mirrors the iOS notion of
 * Documents / Caches / Application Support; on Android these map to
 * filesDir / cacheDir / a stable app-support sub-directory; on Web they map
 * to OPFS / FSAccess buckets (collapsed to documents_bytes by default).
 *
 * Sources pre-IDL: see header drift table.
 * ---------------------------------------------------------------------------
 */
export interface AppStorageInfo {
  documentsBytes: number;
  cacheBytes: number;
  appSupportBytes: number;
  totalBytes: number;
}

/**
 * ---------------------------------------------------------------------------
 * On-disk metrics for a single downloaded model. The full ModelInfo is *not*
 * embedded here — callers cross-reference `model_id` against ModelInfo from
 * model_types.proto. This avoids circular embeds and keeps the wire payload
 * for storage queries small.
 *
 * `last_used_ms` supports LRU presentation and eviction without another type
 * round-trip.
 *
 * Sources pre-IDL: see header drift table.
 * ---------------------------------------------------------------------------
 */
export interface ModelStorageMetrics {
  modelId: string;
  sizeOnDiskBytes: number;
  /** Unix epoch ms of last load */
  lastUsedMs?: number | undefined;
}

/**
 * ---------------------------------------------------------------------------
 * Aggregate storage view: device capacity + app footprint + per-model rows.
 * `total_models` and `total_models_bytes` are denormalized for receivers that
 * would otherwise re-iterate `models` to compute them (Web binding, RN host).
 *
 * Sources pre-IDL: see header drift table.
 * ---------------------------------------------------------------------------
 */
export interface StorageInfo {
  app?: AppStorageInfo | undefined;
  device?: DeviceStorageInfo | undefined;
  models: ModelStorageMetrics[];
  totalModels: number;
  totalModelsBytes: number;
}

/**
 * ---------------------------------------------------------------------------
 * Result of a "do I have room to download X bytes?" probe. SDKs use this to
 * pre-flight `downloadModel(...)` and surface user-facing warnings (e.g.
 * "you only have 1.2 GB free; this model needs 4 GB").
 *
 * `warning_message` and `recommendation` are independently optional —
 * `warning_message` describes the current shortfall, `recommendation`
 * suggests an action (delete cache, free models, etc.).
 *
 * Sources pre-IDL: see header drift table.
 * ---------------------------------------------------------------------------
 */
export interface StorageAvailability {
  isAvailable: boolean;
  requiredBytes: number;
  availableBytes: number;
  warningMessage?: string | undefined;
  recommendation?: string | undefined;
  shortfallBytes: number;
  requiredToAvailableRatio: number;
}

export interface StorageInfoRequest {
  includeDevice: boolean;
  includeApp: boolean;
  includeModels: boolean;
  includeCache: boolean;
}

export interface StorageInfoResult {
  success: boolean;
  info?: StorageInfo | undefined;
  errorMessage: string;
  warnings: string[];
}

export interface StorageAvailabilityRequest {
  modelId: string;
  requiredBytes: number;
  safetyMargin: number;
  includeExistingModelBytes: boolean;
  includeDeletePlan: boolean;
  allowCacheReclamation: boolean;
}

export interface StorageAvailabilityResult {
  success: boolean;
  availability?: StorageAvailability | undefined;
  warnings: string[];
  errorMessage: string;
  deletePlan?: StorageDeletePlan | undefined;
}

export interface StorageDeletePlanRequest {
  modelIds: string[];
  requiredBytes: number;
  includeCache: boolean;
  oldestFirst: boolean;
  allowLoadedModels: boolean;
  includeDownloadPartials: boolean;
}

export interface StorageDeleteCandidate {
  modelId: string;
  reclaimableBytes: number;
  lastUsedMs?: number | undefined;
  isLoaded: boolean;
  localPath: string;
  requiresUnload: boolean;
  requiresPlatformDelete: boolean;
  storageKey: string;
}

export interface StorageDeletePlan {
  canReclaimRequiredBytes: boolean;
  requiredBytes: number;
  reclaimableBytes: number;
  candidates: StorageDeleteCandidate[];
  warnings: string[];
  errorMessage: string;
  requiresUnload: boolean;
  requiresPlatformDelete: boolean;
  candidateCount: number;
}

export interface StorageDeleteRequest {
  modelIds: string[];
  deleteFiles: boolean;
  clearRegistryPaths: boolean;
  unloadIfLoaded: boolean;
  dryRun: boolean;
  plan?: StorageDeletePlan | undefined;
  requirePlanMatch: boolean;
  allowPlatformDelete: boolean;
}

export interface StorageDeleteResult {
  success: boolean;
  deletedBytes: number;
  deletedModelIds: string[];
  failedModelIds: string[];
  warnings: string[];
  errorMessage: string;
  skippedModelIds: string[];
  dryRun: boolean;
  registryUpdated: boolean;
  filesDeleted: boolean;
}

function createBaseDeviceStorageInfo(): DeviceStorageInfo {
  return { totalBytes: 0, freeBytes: 0, usedBytes: 0, usedPercent: 0 };
}

export const DeviceStorageInfo: MessageFns<DeviceStorageInfo> = {
  encode(message: DeviceStorageInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.totalBytes !== 0) {
      writer.uint32(8).int64(message.totalBytes);
    }
    if (message.freeBytes !== 0) {
      writer.uint32(16).int64(message.freeBytes);
    }
    if (message.usedBytes !== 0) {
      writer.uint32(24).int64(message.usedBytes);
    }
    if (message.usedPercent !== 0) {
      writer.uint32(37).float(message.usedPercent);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeviceStorageInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeviceStorageInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.totalBytes = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.freeBytes = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.usedBytes = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 37) {
            break;
          }

          message.usedPercent = reader.float();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeviceStorageInfo {
    return {
      totalBytes: isSet(object.totalBytes)
        ? globalThis.Number(object.totalBytes)
        : isSet(object.total_bytes)
        ? globalThis.Number(object.total_bytes)
        : 0,
      freeBytes: isSet(object.freeBytes)
        ? globalThis.Number(object.freeBytes)
        : isSet(object.free_bytes)
        ? globalThis.Number(object.free_bytes)
        : 0,
      usedBytes: isSet(object.usedBytes)
        ? globalThis.Number(object.usedBytes)
        : isSet(object.used_bytes)
        ? globalThis.Number(object.used_bytes)
        : 0,
      usedPercent: isSet(object.usedPercent)
        ? globalThis.Number(object.usedPercent)
        : isSet(object.used_percent)
        ? globalThis.Number(object.used_percent)
        : 0,
    };
  },

  toJSON(message: DeviceStorageInfo): unknown {
    const obj: any = {};
    if (message.totalBytes !== 0) {
      obj.totalBytes = Math.round(message.totalBytes);
    }
    if (message.freeBytes !== 0) {
      obj.freeBytes = Math.round(message.freeBytes);
    }
    if (message.usedBytes !== 0) {
      obj.usedBytes = Math.round(message.usedBytes);
    }
    if (message.usedPercent !== 0) {
      obj.usedPercent = message.usedPercent;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeviceStorageInfo>, I>>(base?: I): DeviceStorageInfo {
    return DeviceStorageInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeviceStorageInfo>, I>>(object: I): DeviceStorageInfo {
    const message = createBaseDeviceStorageInfo();
    message.totalBytes = object.totalBytes ?? 0;
    message.freeBytes = object.freeBytes ?? 0;
    message.usedBytes = object.usedBytes ?? 0;
    message.usedPercent = object.usedPercent ?? 0;
    return message;
  },
};

function createBaseAppStorageInfo(): AppStorageInfo {
  return { documentsBytes: 0, cacheBytes: 0, appSupportBytes: 0, totalBytes: 0 };
}

export const AppStorageInfo: MessageFns<AppStorageInfo> = {
  encode(message: AppStorageInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.documentsBytes !== 0) {
      writer.uint32(8).int64(message.documentsBytes);
    }
    if (message.cacheBytes !== 0) {
      writer.uint32(16).int64(message.cacheBytes);
    }
    if (message.appSupportBytes !== 0) {
      writer.uint32(24).int64(message.appSupportBytes);
    }
    if (message.totalBytes !== 0) {
      writer.uint32(32).int64(message.totalBytes);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AppStorageInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAppStorageInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.documentsBytes = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.cacheBytes = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.appSupportBytes = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.totalBytes = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AppStorageInfo {
    return {
      documentsBytes: isSet(object.documentsBytes)
        ? globalThis.Number(object.documentsBytes)
        : isSet(object.documents_bytes)
        ? globalThis.Number(object.documents_bytes)
        : 0,
      cacheBytes: isSet(object.cacheBytes)
        ? globalThis.Number(object.cacheBytes)
        : isSet(object.cache_bytes)
        ? globalThis.Number(object.cache_bytes)
        : 0,
      appSupportBytes: isSet(object.appSupportBytes)
        ? globalThis.Number(object.appSupportBytes)
        : isSet(object.app_support_bytes)
        ? globalThis.Number(object.app_support_bytes)
        : 0,
      totalBytes: isSet(object.totalBytes)
        ? globalThis.Number(object.totalBytes)
        : isSet(object.total_bytes)
        ? globalThis.Number(object.total_bytes)
        : 0,
    };
  },

  toJSON(message: AppStorageInfo): unknown {
    const obj: any = {};
    if (message.documentsBytes !== 0) {
      obj.documentsBytes = Math.round(message.documentsBytes);
    }
    if (message.cacheBytes !== 0) {
      obj.cacheBytes = Math.round(message.cacheBytes);
    }
    if (message.appSupportBytes !== 0) {
      obj.appSupportBytes = Math.round(message.appSupportBytes);
    }
    if (message.totalBytes !== 0) {
      obj.totalBytes = Math.round(message.totalBytes);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AppStorageInfo>, I>>(base?: I): AppStorageInfo {
    return AppStorageInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AppStorageInfo>, I>>(object: I): AppStorageInfo {
    const message = createBaseAppStorageInfo();
    message.documentsBytes = object.documentsBytes ?? 0;
    message.cacheBytes = object.cacheBytes ?? 0;
    message.appSupportBytes = object.appSupportBytes ?? 0;
    message.totalBytes = object.totalBytes ?? 0;
    return message;
  },
};

function createBaseModelStorageMetrics(): ModelStorageMetrics {
  return { modelId: "", sizeOnDiskBytes: 0, lastUsedMs: undefined };
}

export const ModelStorageMetrics: MessageFns<ModelStorageMetrics> = {
  encode(message: ModelStorageMetrics, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.modelId !== "") {
      writer.uint32(10).string(message.modelId);
    }
    if (message.sizeOnDiskBytes !== 0) {
      writer.uint32(16).int64(message.sizeOnDiskBytes);
    }
    if (message.lastUsedMs !== undefined) {
      writer.uint32(24).int64(message.lastUsedMs);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ModelStorageMetrics {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseModelStorageMetrics();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.modelId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.sizeOnDiskBytes = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.lastUsedMs = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ModelStorageMetrics {
    return {
      modelId: isSet(object.modelId)
        ? globalThis.String(object.modelId)
        : isSet(object.model_id)
        ? globalThis.String(object.model_id)
        : "",
      sizeOnDiskBytes: isSet(object.sizeOnDiskBytes)
        ? globalThis.Number(object.sizeOnDiskBytes)
        : isSet(object.size_on_disk_bytes)
        ? globalThis.Number(object.size_on_disk_bytes)
        : 0,
      lastUsedMs: isSet(object.lastUsedMs)
        ? globalThis.Number(object.lastUsedMs)
        : isSet(object.last_used_ms)
        ? globalThis.Number(object.last_used_ms)
        : undefined,
    };
  },

  toJSON(message: ModelStorageMetrics): unknown {
    const obj: any = {};
    if (message.modelId !== "") {
      obj.modelId = message.modelId;
    }
    if (message.sizeOnDiskBytes !== 0) {
      obj.sizeOnDiskBytes = Math.round(message.sizeOnDiskBytes);
    }
    if (message.lastUsedMs !== undefined) {
      obj.lastUsedMs = Math.round(message.lastUsedMs);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ModelStorageMetrics>, I>>(base?: I): ModelStorageMetrics {
    return ModelStorageMetrics.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ModelStorageMetrics>, I>>(object: I): ModelStorageMetrics {
    const message = createBaseModelStorageMetrics();
    message.modelId = object.modelId ?? "";
    message.sizeOnDiskBytes = object.sizeOnDiskBytes ?? 0;
    message.lastUsedMs = object.lastUsedMs ?? undefined;
    return message;
  },
};

function createBaseStorageInfo(): StorageInfo {
  return { app: undefined, device: undefined, models: [], totalModels: 0, totalModelsBytes: 0 };
}

export const StorageInfo: MessageFns<StorageInfo> = {
  encode(message: StorageInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.app !== undefined) {
      AppStorageInfo.encode(message.app, writer.uint32(10).fork()).join();
    }
    if (message.device !== undefined) {
      DeviceStorageInfo.encode(message.device, writer.uint32(18).fork()).join();
    }
    for (const v of message.models) {
      ModelStorageMetrics.encode(v!, writer.uint32(26).fork()).join();
    }
    if (message.totalModels !== 0) {
      writer.uint32(32).int32(message.totalModels);
    }
    if (message.totalModelsBytes !== 0) {
      writer.uint32(40).int64(message.totalModelsBytes);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StorageInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStorageInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.app = AppStorageInfo.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.device = DeviceStorageInfo.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.models.push(ModelStorageMetrics.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.totalModels = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.totalModelsBytes = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StorageInfo {
    return {
      app: isSet(object.app) ? AppStorageInfo.fromJSON(object.app) : undefined,
      device: isSet(object.device) ? DeviceStorageInfo.fromJSON(object.device) : undefined,
      models: globalThis.Array.isArray(object?.models)
        ? object.models.map((e: any) => ModelStorageMetrics.fromJSON(e))
        : [],
      totalModels: isSet(object.totalModels)
        ? globalThis.Number(object.totalModels)
        : isSet(object.total_models)
        ? globalThis.Number(object.total_models)
        : 0,
      totalModelsBytes: isSet(object.totalModelsBytes)
        ? globalThis.Number(object.totalModelsBytes)
        : isSet(object.total_models_bytes)
        ? globalThis.Number(object.total_models_bytes)
        : 0,
    };
  },

  toJSON(message: StorageInfo): unknown {
    const obj: any = {};
    if (message.app !== undefined) {
      obj.app = AppStorageInfo.toJSON(message.app);
    }
    if (message.device !== undefined) {
      obj.device = DeviceStorageInfo.toJSON(message.device);
    }
    if (message.models?.length) {
      obj.models = message.models.map((e) => ModelStorageMetrics.toJSON(e));
    }
    if (message.totalModels !== 0) {
      obj.totalModels = Math.round(message.totalModels);
    }
    if (message.totalModelsBytes !== 0) {
      obj.totalModelsBytes = Math.round(message.totalModelsBytes);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StorageInfo>, I>>(base?: I): StorageInfo {
    return StorageInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StorageInfo>, I>>(object: I): StorageInfo {
    const message = createBaseStorageInfo();
    message.app = (object.app !== undefined && object.app !== null)
      ? AppStorageInfo.fromPartial(object.app)
      : undefined;
    message.device = (object.device !== undefined && object.device !== null)
      ? DeviceStorageInfo.fromPartial(object.device)
      : undefined;
    message.models = object.models?.map((e) => ModelStorageMetrics.fromPartial(e)) || [];
    message.totalModels = object.totalModels ?? 0;
    message.totalModelsBytes = object.totalModelsBytes ?? 0;
    return message;
  },
};

function createBaseStorageAvailability(): StorageAvailability {
  return {
    isAvailable: false,
    requiredBytes: 0,
    availableBytes: 0,
    warningMessage: undefined,
    recommendation: undefined,
    shortfallBytes: 0,
    requiredToAvailableRatio: 0,
  };
}

export const StorageAvailability: MessageFns<StorageAvailability> = {
  encode(message: StorageAvailability, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.isAvailable !== false) {
      writer.uint32(8).bool(message.isAvailable);
    }
    if (message.requiredBytes !== 0) {
      writer.uint32(16).int64(message.requiredBytes);
    }
    if (message.availableBytes !== 0) {
      writer.uint32(24).int64(message.availableBytes);
    }
    if (message.warningMessage !== undefined) {
      writer.uint32(34).string(message.warningMessage);
    }
    if (message.recommendation !== undefined) {
      writer.uint32(42).string(message.recommendation);
    }
    if (message.shortfallBytes !== 0) {
      writer.uint32(48).int64(message.shortfallBytes);
    }
    if (message.requiredToAvailableRatio !== 0) {
      writer.uint32(61).float(message.requiredToAvailableRatio);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StorageAvailability {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStorageAvailability();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.isAvailable = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.requiredBytes = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.availableBytes = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.warningMessage = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.recommendation = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.shortfallBytes = longToNumber(reader.int64());
          continue;
        }
        case 7: {
          if (tag !== 61) {
            break;
          }

          message.requiredToAvailableRatio = reader.float();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StorageAvailability {
    return {
      isAvailable: isSet(object.isAvailable)
        ? globalThis.Boolean(object.isAvailable)
        : isSet(object.is_available)
        ? globalThis.Boolean(object.is_available)
        : false,
      requiredBytes: isSet(object.requiredBytes)
        ? globalThis.Number(object.requiredBytes)
        : isSet(object.required_bytes)
        ? globalThis.Number(object.required_bytes)
        : 0,
      availableBytes: isSet(object.availableBytes)
        ? globalThis.Number(object.availableBytes)
        : isSet(object.available_bytes)
        ? globalThis.Number(object.available_bytes)
        : 0,
      warningMessage: isSet(object.warningMessage)
        ? globalThis.String(object.warningMessage)
        : isSet(object.warning_message)
        ? globalThis.String(object.warning_message)
        : undefined,
      recommendation: isSet(object.recommendation) ? globalThis.String(object.recommendation) : undefined,
      shortfallBytes: isSet(object.shortfallBytes)
        ? globalThis.Number(object.shortfallBytes)
        : isSet(object.shortfall_bytes)
        ? globalThis.Number(object.shortfall_bytes)
        : 0,
      requiredToAvailableRatio: isSet(object.requiredToAvailableRatio)
        ? globalThis.Number(object.requiredToAvailableRatio)
        : isSet(object.required_to_available_ratio)
        ? globalThis.Number(object.required_to_available_ratio)
        : 0,
    };
  },

  toJSON(message: StorageAvailability): unknown {
    const obj: any = {};
    if (message.isAvailable !== false) {
      obj.isAvailable = message.isAvailable;
    }
    if (message.requiredBytes !== 0) {
      obj.requiredBytes = Math.round(message.requiredBytes);
    }
    if (message.availableBytes !== 0) {
      obj.availableBytes = Math.round(message.availableBytes);
    }
    if (message.warningMessage !== undefined) {
      obj.warningMessage = message.warningMessage;
    }
    if (message.recommendation !== undefined) {
      obj.recommendation = message.recommendation;
    }
    if (message.shortfallBytes !== 0) {
      obj.shortfallBytes = Math.round(message.shortfallBytes);
    }
    if (message.requiredToAvailableRatio !== 0) {
      obj.requiredToAvailableRatio = message.requiredToAvailableRatio;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StorageAvailability>, I>>(base?: I): StorageAvailability {
    return StorageAvailability.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StorageAvailability>, I>>(object: I): StorageAvailability {
    const message = createBaseStorageAvailability();
    message.isAvailable = object.isAvailable ?? false;
    message.requiredBytes = object.requiredBytes ?? 0;
    message.availableBytes = object.availableBytes ?? 0;
    message.warningMessage = object.warningMessage ?? undefined;
    message.recommendation = object.recommendation ?? undefined;
    message.shortfallBytes = object.shortfallBytes ?? 0;
    message.requiredToAvailableRatio = object.requiredToAvailableRatio ?? 0;
    return message;
  },
};

function createBaseStorageInfoRequest(): StorageInfoRequest {
  return { includeDevice: false, includeApp: false, includeModels: false, includeCache: false };
}

export const StorageInfoRequest: MessageFns<StorageInfoRequest> = {
  encode(message: StorageInfoRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.includeDevice !== false) {
      writer.uint32(8).bool(message.includeDevice);
    }
    if (message.includeApp !== false) {
      writer.uint32(16).bool(message.includeApp);
    }
    if (message.includeModels !== false) {
      writer.uint32(24).bool(message.includeModels);
    }
    if (message.includeCache !== false) {
      writer.uint32(32).bool(message.includeCache);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StorageInfoRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStorageInfoRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.includeDevice = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.includeApp = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.includeModels = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.includeCache = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StorageInfoRequest {
    return {
      includeDevice: isSet(object.includeDevice)
        ? globalThis.Boolean(object.includeDevice)
        : isSet(object.include_device)
        ? globalThis.Boolean(object.include_device)
        : false,
      includeApp: isSet(object.includeApp)
        ? globalThis.Boolean(object.includeApp)
        : isSet(object.include_app)
        ? globalThis.Boolean(object.include_app)
        : false,
      includeModels: isSet(object.includeModels)
        ? globalThis.Boolean(object.includeModels)
        : isSet(object.include_models)
        ? globalThis.Boolean(object.include_models)
        : false,
      includeCache: isSet(object.includeCache)
        ? globalThis.Boolean(object.includeCache)
        : isSet(object.include_cache)
        ? globalThis.Boolean(object.include_cache)
        : false,
    };
  },

  toJSON(message: StorageInfoRequest): unknown {
    const obj: any = {};
    if (message.includeDevice !== false) {
      obj.includeDevice = message.includeDevice;
    }
    if (message.includeApp !== false) {
      obj.includeApp = message.includeApp;
    }
    if (message.includeModels !== false) {
      obj.includeModels = message.includeModels;
    }
    if (message.includeCache !== false) {
      obj.includeCache = message.includeCache;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StorageInfoRequest>, I>>(base?: I): StorageInfoRequest {
    return StorageInfoRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StorageInfoRequest>, I>>(object: I): StorageInfoRequest {
    const message = createBaseStorageInfoRequest();
    message.includeDevice = object.includeDevice ?? false;
    message.includeApp = object.includeApp ?? false;
    message.includeModels = object.includeModels ?? false;
    message.includeCache = object.includeCache ?? false;
    return message;
  },
};

function createBaseStorageInfoResult(): StorageInfoResult {
  return { success: false, info: undefined, errorMessage: "", warnings: [] };
}

export const StorageInfoResult: MessageFns<StorageInfoResult> = {
  encode(message: StorageInfoResult, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.info !== undefined) {
      StorageInfo.encode(message.info, writer.uint32(18).fork()).join();
    }
    if (message.errorMessage !== "") {
      writer.uint32(26).string(message.errorMessage);
    }
    for (const v of message.warnings) {
      writer.uint32(34).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StorageInfoResult {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStorageInfoResult();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.info = StorageInfo.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.errorMessage = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.warnings.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StorageInfoResult {
    return {
      success: isSet(object.success) ? globalThis.Boolean(object.success) : false,
      info: isSet(object.info) ? StorageInfo.fromJSON(object.info) : undefined,
      errorMessage: isSet(object.errorMessage)
        ? globalThis.String(object.errorMessage)
        : isSet(object.error_message)
        ? globalThis.String(object.error_message)
        : "",
      warnings: globalThis.Array.isArray(object?.warnings) ? object.warnings.map((e: any) => globalThis.String(e)) : [],
    };
  },

  toJSON(message: StorageInfoResult): unknown {
    const obj: any = {};
    if (message.success !== false) {
      obj.success = message.success;
    }
    if (message.info !== undefined) {
      obj.info = StorageInfo.toJSON(message.info);
    }
    if (message.errorMessage !== "") {
      obj.errorMessage = message.errorMessage;
    }
    if (message.warnings?.length) {
      obj.warnings = message.warnings;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StorageInfoResult>, I>>(base?: I): StorageInfoResult {
    return StorageInfoResult.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StorageInfoResult>, I>>(object: I): StorageInfoResult {
    const message = createBaseStorageInfoResult();
    message.success = object.success ?? false;
    message.info = (object.info !== undefined && object.info !== null)
      ? StorageInfo.fromPartial(object.info)
      : undefined;
    message.errorMessage = object.errorMessage ?? "";
    message.warnings = object.warnings?.map((e) => e) || [];
    return message;
  },
};

function createBaseStorageAvailabilityRequest(): StorageAvailabilityRequest {
  return {
    modelId: "",
    requiredBytes: 0,
    safetyMargin: 0,
    includeExistingModelBytes: false,
    includeDeletePlan: false,
    allowCacheReclamation: false,
  };
}

export const StorageAvailabilityRequest: MessageFns<StorageAvailabilityRequest> = {
  encode(message: StorageAvailabilityRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.modelId !== "") {
      writer.uint32(10).string(message.modelId);
    }
    if (message.requiredBytes !== 0) {
      writer.uint32(16).int64(message.requiredBytes);
    }
    if (message.safetyMargin !== 0) {
      writer.uint32(25).double(message.safetyMargin);
    }
    if (message.includeExistingModelBytes !== false) {
      writer.uint32(32).bool(message.includeExistingModelBytes);
    }
    if (message.includeDeletePlan !== false) {
      writer.uint32(40).bool(message.includeDeletePlan);
    }
    if (message.allowCacheReclamation !== false) {
      writer.uint32(48).bool(message.allowCacheReclamation);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StorageAvailabilityRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStorageAvailabilityRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.modelId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.requiredBytes = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 25) {
            break;
          }

          message.safetyMargin = reader.double();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.includeExistingModelBytes = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.includeDeletePlan = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.allowCacheReclamation = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StorageAvailabilityRequest {
    return {
      modelId: isSet(object.modelId)
        ? globalThis.String(object.modelId)
        : isSet(object.model_id)
        ? globalThis.String(object.model_id)
        : "",
      requiredBytes: isSet(object.requiredBytes)
        ? globalThis.Number(object.requiredBytes)
        : isSet(object.required_bytes)
        ? globalThis.Number(object.required_bytes)
        : 0,
      safetyMargin: isSet(object.safetyMargin)
        ? globalThis.Number(object.safetyMargin)
        : isSet(object.safety_margin)
        ? globalThis.Number(object.safety_margin)
        : 0,
      includeExistingModelBytes: isSet(object.includeExistingModelBytes)
        ? globalThis.Boolean(object.includeExistingModelBytes)
        : isSet(object.include_existing_model_bytes)
        ? globalThis.Boolean(object.include_existing_model_bytes)
        : false,
      includeDeletePlan: isSet(object.includeDeletePlan)
        ? globalThis.Boolean(object.includeDeletePlan)
        : isSet(object.include_delete_plan)
        ? globalThis.Boolean(object.include_delete_plan)
        : false,
      allowCacheReclamation: isSet(object.allowCacheReclamation)
        ? globalThis.Boolean(object.allowCacheReclamation)
        : isSet(object.allow_cache_reclamation)
        ? globalThis.Boolean(object.allow_cache_reclamation)
        : false,
    };
  },

  toJSON(message: StorageAvailabilityRequest): unknown {
    const obj: any = {};
    if (message.modelId !== "") {
      obj.modelId = message.modelId;
    }
    if (message.requiredBytes !== 0) {
      obj.requiredBytes = Math.round(message.requiredBytes);
    }
    if (message.safetyMargin !== 0) {
      obj.safetyMargin = message.safetyMargin;
    }
    if (message.includeExistingModelBytes !== false) {
      obj.includeExistingModelBytes = message.includeExistingModelBytes;
    }
    if (message.includeDeletePlan !== false) {
      obj.includeDeletePlan = message.includeDeletePlan;
    }
    if (message.allowCacheReclamation !== false) {
      obj.allowCacheReclamation = message.allowCacheReclamation;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StorageAvailabilityRequest>, I>>(base?: I): StorageAvailabilityRequest {
    return StorageAvailabilityRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StorageAvailabilityRequest>, I>>(object: I): StorageAvailabilityRequest {
    const message = createBaseStorageAvailabilityRequest();
    message.modelId = object.modelId ?? "";
    message.requiredBytes = object.requiredBytes ?? 0;
    message.safetyMargin = object.safetyMargin ?? 0;
    message.includeExistingModelBytes = object.includeExistingModelBytes ?? false;
    message.includeDeletePlan = object.includeDeletePlan ?? false;
    message.allowCacheReclamation = object.allowCacheReclamation ?? false;
    return message;
  },
};

function createBaseStorageAvailabilityResult(): StorageAvailabilityResult {
  return { success: false, availability: undefined, warnings: [], errorMessage: "", deletePlan: undefined };
}

export const StorageAvailabilityResult: MessageFns<StorageAvailabilityResult> = {
  encode(message: StorageAvailabilityResult, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.availability !== undefined) {
      StorageAvailability.encode(message.availability, writer.uint32(18).fork()).join();
    }
    for (const v of message.warnings) {
      writer.uint32(26).string(v!);
    }
    if (message.errorMessage !== "") {
      writer.uint32(34).string(message.errorMessage);
    }
    if (message.deletePlan !== undefined) {
      StorageDeletePlan.encode(message.deletePlan, writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StorageAvailabilityResult {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStorageAvailabilityResult();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.availability = StorageAvailability.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.warnings.push(reader.string());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.errorMessage = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.deletePlan = StorageDeletePlan.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StorageAvailabilityResult {
    return {
      success: isSet(object.success) ? globalThis.Boolean(object.success) : false,
      availability: isSet(object.availability) ? StorageAvailability.fromJSON(object.availability) : undefined,
      warnings: globalThis.Array.isArray(object?.warnings) ? object.warnings.map((e: any) => globalThis.String(e)) : [],
      errorMessage: isSet(object.errorMessage)
        ? globalThis.String(object.errorMessage)
        : isSet(object.error_message)
        ? globalThis.String(object.error_message)
        : "",
      deletePlan: isSet(object.deletePlan)
        ? StorageDeletePlan.fromJSON(object.deletePlan)
        : isSet(object.delete_plan)
        ? StorageDeletePlan.fromJSON(object.delete_plan)
        : undefined,
    };
  },

  toJSON(message: StorageAvailabilityResult): unknown {
    const obj: any = {};
    if (message.success !== false) {
      obj.success = message.success;
    }
    if (message.availability !== undefined) {
      obj.availability = StorageAvailability.toJSON(message.availability);
    }
    if (message.warnings?.length) {
      obj.warnings = message.warnings;
    }
    if (message.errorMessage !== "") {
      obj.errorMessage = message.errorMessage;
    }
    if (message.deletePlan !== undefined) {
      obj.deletePlan = StorageDeletePlan.toJSON(message.deletePlan);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StorageAvailabilityResult>, I>>(base?: I): StorageAvailabilityResult {
    return StorageAvailabilityResult.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StorageAvailabilityResult>, I>>(object: I): StorageAvailabilityResult {
    const message = createBaseStorageAvailabilityResult();
    message.success = object.success ?? false;
    message.availability = (object.availability !== undefined && object.availability !== null)
      ? StorageAvailability.fromPartial(object.availability)
      : undefined;
    message.warnings = object.warnings?.map((e) => e) || [];
    message.errorMessage = object.errorMessage ?? "";
    message.deletePlan = (object.deletePlan !== undefined && object.deletePlan !== null)
      ? StorageDeletePlan.fromPartial(object.deletePlan)
      : undefined;
    return message;
  },
};

function createBaseStorageDeletePlanRequest(): StorageDeletePlanRequest {
  return {
    modelIds: [],
    requiredBytes: 0,
    includeCache: false,
    oldestFirst: false,
    allowLoadedModels: false,
    includeDownloadPartials: false,
  };
}

export const StorageDeletePlanRequest: MessageFns<StorageDeletePlanRequest> = {
  encode(message: StorageDeletePlanRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.modelIds) {
      writer.uint32(10).string(v!);
    }
    if (message.requiredBytes !== 0) {
      writer.uint32(16).int64(message.requiredBytes);
    }
    if (message.includeCache !== false) {
      writer.uint32(24).bool(message.includeCache);
    }
    if (message.oldestFirst !== false) {
      writer.uint32(32).bool(message.oldestFirst);
    }
    if (message.allowLoadedModels !== false) {
      writer.uint32(40).bool(message.allowLoadedModels);
    }
    if (message.includeDownloadPartials !== false) {
      writer.uint32(48).bool(message.includeDownloadPartials);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StorageDeletePlanRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStorageDeletePlanRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.modelIds.push(reader.string());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.requiredBytes = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.includeCache = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.oldestFirst = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.allowLoadedModels = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.includeDownloadPartials = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StorageDeletePlanRequest {
    return {
      modelIds: globalThis.Array.isArray(object?.modelIds)
        ? object.modelIds.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.model_ids)
        ? object.model_ids.map((e: any) => globalThis.String(e))
        : [],
      requiredBytes: isSet(object.requiredBytes)
        ? globalThis.Number(object.requiredBytes)
        : isSet(object.required_bytes)
        ? globalThis.Number(object.required_bytes)
        : 0,
      includeCache: isSet(object.includeCache)
        ? globalThis.Boolean(object.includeCache)
        : isSet(object.include_cache)
        ? globalThis.Boolean(object.include_cache)
        : false,
      oldestFirst: isSet(object.oldestFirst)
        ? globalThis.Boolean(object.oldestFirst)
        : isSet(object.oldest_first)
        ? globalThis.Boolean(object.oldest_first)
        : false,
      allowLoadedModels: isSet(object.allowLoadedModels)
        ? globalThis.Boolean(object.allowLoadedModels)
        : isSet(object.allow_loaded_models)
        ? globalThis.Boolean(object.allow_loaded_models)
        : false,
      includeDownloadPartials: isSet(object.includeDownloadPartials)
        ? globalThis.Boolean(object.includeDownloadPartials)
        : isSet(object.include_download_partials)
        ? globalThis.Boolean(object.include_download_partials)
        : false,
    };
  },

  toJSON(message: StorageDeletePlanRequest): unknown {
    const obj: any = {};
    if (message.modelIds?.length) {
      obj.modelIds = message.modelIds;
    }
    if (message.requiredBytes !== 0) {
      obj.requiredBytes = Math.round(message.requiredBytes);
    }
    if (message.includeCache !== false) {
      obj.includeCache = message.includeCache;
    }
    if (message.oldestFirst !== false) {
      obj.oldestFirst = message.oldestFirst;
    }
    if (message.allowLoadedModels !== false) {
      obj.allowLoadedModels = message.allowLoadedModels;
    }
    if (message.includeDownloadPartials !== false) {
      obj.includeDownloadPartials = message.includeDownloadPartials;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StorageDeletePlanRequest>, I>>(base?: I): StorageDeletePlanRequest {
    return StorageDeletePlanRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StorageDeletePlanRequest>, I>>(object: I): StorageDeletePlanRequest {
    const message = createBaseStorageDeletePlanRequest();
    message.modelIds = object.modelIds?.map((e) => e) || [];
    message.requiredBytes = object.requiredBytes ?? 0;
    message.includeCache = object.includeCache ?? false;
    message.oldestFirst = object.oldestFirst ?? false;
    message.allowLoadedModels = object.allowLoadedModels ?? false;
    message.includeDownloadPartials = object.includeDownloadPartials ?? false;
    return message;
  },
};

function createBaseStorageDeleteCandidate(): StorageDeleteCandidate {
  return {
    modelId: "",
    reclaimableBytes: 0,
    lastUsedMs: undefined,
    isLoaded: false,
    localPath: "",
    requiresUnload: false,
    requiresPlatformDelete: false,
    storageKey: "",
  };
}

export const StorageDeleteCandidate: MessageFns<StorageDeleteCandidate> = {
  encode(message: StorageDeleteCandidate, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.modelId !== "") {
      writer.uint32(10).string(message.modelId);
    }
    if (message.reclaimableBytes !== 0) {
      writer.uint32(16).int64(message.reclaimableBytes);
    }
    if (message.lastUsedMs !== undefined) {
      writer.uint32(24).int64(message.lastUsedMs);
    }
    if (message.isLoaded !== false) {
      writer.uint32(32).bool(message.isLoaded);
    }
    if (message.localPath !== "") {
      writer.uint32(42).string(message.localPath);
    }
    if (message.requiresUnload !== false) {
      writer.uint32(48).bool(message.requiresUnload);
    }
    if (message.requiresPlatformDelete !== false) {
      writer.uint32(56).bool(message.requiresPlatformDelete);
    }
    if (message.storageKey !== "") {
      writer.uint32(66).string(message.storageKey);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StorageDeleteCandidate {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStorageDeleteCandidate();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.modelId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.reclaimableBytes = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.lastUsedMs = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.isLoaded = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.localPath = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.requiresUnload = reader.bool();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.requiresPlatformDelete = reader.bool();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.storageKey = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StorageDeleteCandidate {
    return {
      modelId: isSet(object.modelId)
        ? globalThis.String(object.modelId)
        : isSet(object.model_id)
        ? globalThis.String(object.model_id)
        : "",
      reclaimableBytes: isSet(object.reclaimableBytes)
        ? globalThis.Number(object.reclaimableBytes)
        : isSet(object.reclaimable_bytes)
        ? globalThis.Number(object.reclaimable_bytes)
        : 0,
      lastUsedMs: isSet(object.lastUsedMs)
        ? globalThis.Number(object.lastUsedMs)
        : isSet(object.last_used_ms)
        ? globalThis.Number(object.last_used_ms)
        : undefined,
      isLoaded: isSet(object.isLoaded)
        ? globalThis.Boolean(object.isLoaded)
        : isSet(object.is_loaded)
        ? globalThis.Boolean(object.is_loaded)
        : false,
      localPath: isSet(object.localPath)
        ? globalThis.String(object.localPath)
        : isSet(object.local_path)
        ? globalThis.String(object.local_path)
        : "",
      requiresUnload: isSet(object.requiresUnload)
        ? globalThis.Boolean(object.requiresUnload)
        : isSet(object.requires_unload)
        ? globalThis.Boolean(object.requires_unload)
        : false,
      requiresPlatformDelete: isSet(object.requiresPlatformDelete)
        ? globalThis.Boolean(object.requiresPlatformDelete)
        : isSet(object.requires_platform_delete)
        ? globalThis.Boolean(object.requires_platform_delete)
        : false,
      storageKey: isSet(object.storageKey)
        ? globalThis.String(object.storageKey)
        : isSet(object.storage_key)
        ? globalThis.String(object.storage_key)
        : "",
    };
  },

  toJSON(message: StorageDeleteCandidate): unknown {
    const obj: any = {};
    if (message.modelId !== "") {
      obj.modelId = message.modelId;
    }
    if (message.reclaimableBytes !== 0) {
      obj.reclaimableBytes = Math.round(message.reclaimableBytes);
    }
    if (message.lastUsedMs !== undefined) {
      obj.lastUsedMs = Math.round(message.lastUsedMs);
    }
    if (message.isLoaded !== false) {
      obj.isLoaded = message.isLoaded;
    }
    if (message.localPath !== "") {
      obj.localPath = message.localPath;
    }
    if (message.requiresUnload !== false) {
      obj.requiresUnload = message.requiresUnload;
    }
    if (message.requiresPlatformDelete !== false) {
      obj.requiresPlatformDelete = message.requiresPlatformDelete;
    }
    if (message.storageKey !== "") {
      obj.storageKey = message.storageKey;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StorageDeleteCandidate>, I>>(base?: I): StorageDeleteCandidate {
    return StorageDeleteCandidate.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StorageDeleteCandidate>, I>>(object: I): StorageDeleteCandidate {
    const message = createBaseStorageDeleteCandidate();
    message.modelId = object.modelId ?? "";
    message.reclaimableBytes = object.reclaimableBytes ?? 0;
    message.lastUsedMs = object.lastUsedMs ?? undefined;
    message.isLoaded = object.isLoaded ?? false;
    message.localPath = object.localPath ?? "";
    message.requiresUnload = object.requiresUnload ?? false;
    message.requiresPlatformDelete = object.requiresPlatformDelete ?? false;
    message.storageKey = object.storageKey ?? "";
    return message;
  },
};

function createBaseStorageDeletePlan(): StorageDeletePlan {
  return {
    canReclaimRequiredBytes: false,
    requiredBytes: 0,
    reclaimableBytes: 0,
    candidates: [],
    warnings: [],
    errorMessage: "",
    requiresUnload: false,
    requiresPlatformDelete: false,
    candidateCount: 0,
  };
}

export const StorageDeletePlan: MessageFns<StorageDeletePlan> = {
  encode(message: StorageDeletePlan, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.canReclaimRequiredBytes !== false) {
      writer.uint32(8).bool(message.canReclaimRequiredBytes);
    }
    if (message.requiredBytes !== 0) {
      writer.uint32(16).int64(message.requiredBytes);
    }
    if (message.reclaimableBytes !== 0) {
      writer.uint32(24).int64(message.reclaimableBytes);
    }
    for (const v of message.candidates) {
      StorageDeleteCandidate.encode(v!, writer.uint32(34).fork()).join();
    }
    for (const v of message.warnings) {
      writer.uint32(42).string(v!);
    }
    if (message.errorMessage !== "") {
      writer.uint32(50).string(message.errorMessage);
    }
    if (message.requiresUnload !== false) {
      writer.uint32(56).bool(message.requiresUnload);
    }
    if (message.requiresPlatformDelete !== false) {
      writer.uint32(64).bool(message.requiresPlatformDelete);
    }
    if (message.candidateCount !== 0) {
      writer.uint32(72).int32(message.candidateCount);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StorageDeletePlan {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStorageDeletePlan();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.canReclaimRequiredBytes = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.requiredBytes = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.reclaimableBytes = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.candidates.push(StorageDeleteCandidate.decode(reader, reader.uint32()));
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.warnings.push(reader.string());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.errorMessage = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.requiresUnload = reader.bool();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.requiresPlatformDelete = reader.bool();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.candidateCount = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StorageDeletePlan {
    return {
      canReclaimRequiredBytes: isSet(object.canReclaimRequiredBytes)
        ? globalThis.Boolean(object.canReclaimRequiredBytes)
        : isSet(object.can_reclaim_required_bytes)
        ? globalThis.Boolean(object.can_reclaim_required_bytes)
        : false,
      requiredBytes: isSet(object.requiredBytes)
        ? globalThis.Number(object.requiredBytes)
        : isSet(object.required_bytes)
        ? globalThis.Number(object.required_bytes)
        : 0,
      reclaimableBytes: isSet(object.reclaimableBytes)
        ? globalThis.Number(object.reclaimableBytes)
        : isSet(object.reclaimable_bytes)
        ? globalThis.Number(object.reclaimable_bytes)
        : 0,
      candidates: globalThis.Array.isArray(object?.candidates)
        ? object.candidates.map((e: any) => StorageDeleteCandidate.fromJSON(e))
        : [],
      warnings: globalThis.Array.isArray(object?.warnings)
        ? object.warnings.map((e: any) => globalThis.String(e))
        : [],
      errorMessage: isSet(object.errorMessage)
        ? globalThis.String(object.errorMessage)
        : isSet(object.error_message)
        ? globalThis.String(object.error_message)
        : "",
      requiresUnload: isSet(object.requiresUnload)
        ? globalThis.Boolean(object.requiresUnload)
        : isSet(object.requires_unload)
        ? globalThis.Boolean(object.requires_unload)
        : false,
      requiresPlatformDelete: isSet(object.requiresPlatformDelete)
        ? globalThis.Boolean(object.requiresPlatformDelete)
        : isSet(object.requires_platform_delete)
        ? globalThis.Boolean(object.requires_platform_delete)
        : false,
      candidateCount: isSet(object.candidateCount)
        ? globalThis.Number(object.candidateCount)
        : isSet(object.candidate_count)
        ? globalThis.Number(object.candidate_count)
        : 0,
    };
  },

  toJSON(message: StorageDeletePlan): unknown {
    const obj: any = {};
    if (message.canReclaimRequiredBytes !== false) {
      obj.canReclaimRequiredBytes = message.canReclaimRequiredBytes;
    }
    if (message.requiredBytes !== 0) {
      obj.requiredBytes = Math.round(message.requiredBytes);
    }
    if (message.reclaimableBytes !== 0) {
      obj.reclaimableBytes = Math.round(message.reclaimableBytes);
    }
    if (message.candidates?.length) {
      obj.candidates = message.candidates.map((e) => StorageDeleteCandidate.toJSON(e));
    }
    if (message.warnings?.length) {
      obj.warnings = message.warnings;
    }
    if (message.errorMessage !== "") {
      obj.errorMessage = message.errorMessage;
    }
    if (message.requiresUnload !== false) {
      obj.requiresUnload = message.requiresUnload;
    }
    if (message.requiresPlatformDelete !== false) {
      obj.requiresPlatformDelete = message.requiresPlatformDelete;
    }
    if (message.candidateCount !== 0) {
      obj.candidateCount = Math.round(message.candidateCount);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StorageDeletePlan>, I>>(base?: I): StorageDeletePlan {
    return StorageDeletePlan.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StorageDeletePlan>, I>>(object: I): StorageDeletePlan {
    const message = createBaseStorageDeletePlan();
    message.canReclaimRequiredBytes = object.canReclaimRequiredBytes ?? false;
    message.requiredBytes = object.requiredBytes ?? 0;
    message.reclaimableBytes = object.reclaimableBytes ?? 0;
    message.candidates = object.candidates?.map((e) => StorageDeleteCandidate.fromPartial(e)) || [];
    message.warnings = object.warnings?.map((e) => e) || [];
    message.errorMessage = object.errorMessage ?? "";
    message.requiresUnload = object.requiresUnload ?? false;
    message.requiresPlatformDelete = object.requiresPlatformDelete ?? false;
    message.candidateCount = object.candidateCount ?? 0;
    return message;
  },
};

function createBaseStorageDeleteRequest(): StorageDeleteRequest {
  return {
    modelIds: [],
    deleteFiles: false,
    clearRegistryPaths: false,
    unloadIfLoaded: false,
    dryRun: false,
    plan: undefined,
    requirePlanMatch: false,
    allowPlatformDelete: false,
  };
}

export const StorageDeleteRequest: MessageFns<StorageDeleteRequest> = {
  encode(message: StorageDeleteRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.modelIds) {
      writer.uint32(10).string(v!);
    }
    if (message.deleteFiles !== false) {
      writer.uint32(16).bool(message.deleteFiles);
    }
    if (message.clearRegistryPaths !== false) {
      writer.uint32(24).bool(message.clearRegistryPaths);
    }
    if (message.unloadIfLoaded !== false) {
      writer.uint32(32).bool(message.unloadIfLoaded);
    }
    if (message.dryRun !== false) {
      writer.uint32(40).bool(message.dryRun);
    }
    if (message.plan !== undefined) {
      StorageDeletePlan.encode(message.plan, writer.uint32(50).fork()).join();
    }
    if (message.requirePlanMatch !== false) {
      writer.uint32(56).bool(message.requirePlanMatch);
    }
    if (message.allowPlatformDelete !== false) {
      writer.uint32(64).bool(message.allowPlatformDelete);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StorageDeleteRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStorageDeleteRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.modelIds.push(reader.string());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.deleteFiles = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.clearRegistryPaths = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.unloadIfLoaded = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.dryRun = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.plan = StorageDeletePlan.decode(reader, reader.uint32());
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.requirePlanMatch = reader.bool();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.allowPlatformDelete = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StorageDeleteRequest {
    return {
      modelIds: globalThis.Array.isArray(object?.modelIds)
        ? object.modelIds.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.model_ids)
        ? object.model_ids.map((e: any) => globalThis.String(e))
        : [],
      deleteFiles: isSet(object.deleteFiles)
        ? globalThis.Boolean(object.deleteFiles)
        : isSet(object.delete_files)
        ? globalThis.Boolean(object.delete_files)
        : false,
      clearRegistryPaths: isSet(object.clearRegistryPaths)
        ? globalThis.Boolean(object.clearRegistryPaths)
        : isSet(object.clear_registry_paths)
        ? globalThis.Boolean(object.clear_registry_paths)
        : false,
      unloadIfLoaded: isSet(object.unloadIfLoaded)
        ? globalThis.Boolean(object.unloadIfLoaded)
        : isSet(object.unload_if_loaded)
        ? globalThis.Boolean(object.unload_if_loaded)
        : false,
      dryRun: isSet(object.dryRun)
        ? globalThis.Boolean(object.dryRun)
        : isSet(object.dry_run)
        ? globalThis.Boolean(object.dry_run)
        : false,
      plan: isSet(object.plan) ? StorageDeletePlan.fromJSON(object.plan) : undefined,
      requirePlanMatch: isSet(object.requirePlanMatch)
        ? globalThis.Boolean(object.requirePlanMatch)
        : isSet(object.require_plan_match)
        ? globalThis.Boolean(object.require_plan_match)
        : false,
      allowPlatformDelete: isSet(object.allowPlatformDelete)
        ? globalThis.Boolean(object.allowPlatformDelete)
        : isSet(object.allow_platform_delete)
        ? globalThis.Boolean(object.allow_platform_delete)
        : false,
    };
  },

  toJSON(message: StorageDeleteRequest): unknown {
    const obj: any = {};
    if (message.modelIds?.length) {
      obj.modelIds = message.modelIds;
    }
    if (message.deleteFiles !== false) {
      obj.deleteFiles = message.deleteFiles;
    }
    if (message.clearRegistryPaths !== false) {
      obj.clearRegistryPaths = message.clearRegistryPaths;
    }
    if (message.unloadIfLoaded !== false) {
      obj.unloadIfLoaded = message.unloadIfLoaded;
    }
    if (message.dryRun !== false) {
      obj.dryRun = message.dryRun;
    }
    if (message.plan !== undefined) {
      obj.plan = StorageDeletePlan.toJSON(message.plan);
    }
    if (message.requirePlanMatch !== false) {
      obj.requirePlanMatch = message.requirePlanMatch;
    }
    if (message.allowPlatformDelete !== false) {
      obj.allowPlatformDelete = message.allowPlatformDelete;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StorageDeleteRequest>, I>>(base?: I): StorageDeleteRequest {
    return StorageDeleteRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StorageDeleteRequest>, I>>(object: I): StorageDeleteRequest {
    const message = createBaseStorageDeleteRequest();
    message.modelIds = object.modelIds?.map((e) => e) || [];
    message.deleteFiles = object.deleteFiles ?? false;
    message.clearRegistryPaths = object.clearRegistryPaths ?? false;
    message.unloadIfLoaded = object.unloadIfLoaded ?? false;
    message.dryRun = object.dryRun ?? false;
    message.plan = (object.plan !== undefined && object.plan !== null)
      ? StorageDeletePlan.fromPartial(object.plan)
      : undefined;
    message.requirePlanMatch = object.requirePlanMatch ?? false;
    message.allowPlatformDelete = object.allowPlatformDelete ?? false;
    return message;
  },
};

function createBaseStorageDeleteResult(): StorageDeleteResult {
  return {
    success: false,
    deletedBytes: 0,
    deletedModelIds: [],
    failedModelIds: [],
    warnings: [],
    errorMessage: "",
    skippedModelIds: [],
    dryRun: false,
    registryUpdated: false,
    filesDeleted: false,
  };
}

export const StorageDeleteResult: MessageFns<StorageDeleteResult> = {
  encode(message: StorageDeleteResult, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.deletedBytes !== 0) {
      writer.uint32(16).int64(message.deletedBytes);
    }
    for (const v of message.deletedModelIds) {
      writer.uint32(26).string(v!);
    }
    for (const v of message.failedModelIds) {
      writer.uint32(34).string(v!);
    }
    for (const v of message.warnings) {
      writer.uint32(42).string(v!);
    }
    if (message.errorMessage !== "") {
      writer.uint32(50).string(message.errorMessage);
    }
    for (const v of message.skippedModelIds) {
      writer.uint32(58).string(v!);
    }
    if (message.dryRun !== false) {
      writer.uint32(64).bool(message.dryRun);
    }
    if (message.registryUpdated !== false) {
      writer.uint32(72).bool(message.registryUpdated);
    }
    if (message.filesDeleted !== false) {
      writer.uint32(80).bool(message.filesDeleted);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StorageDeleteResult {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStorageDeleteResult();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.deletedBytes = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.deletedModelIds.push(reader.string());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.failedModelIds.push(reader.string());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.warnings.push(reader.string());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.errorMessage = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.skippedModelIds.push(reader.string());
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.dryRun = reader.bool();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.registryUpdated = reader.bool();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.filesDeleted = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StorageDeleteResult {
    return {
      success: isSet(object.success) ? globalThis.Boolean(object.success) : false,
      deletedBytes: isSet(object.deletedBytes)
        ? globalThis.Number(object.deletedBytes)
        : isSet(object.deleted_bytes)
        ? globalThis.Number(object.deleted_bytes)
        : 0,
      deletedModelIds: globalThis.Array.isArray(object?.deletedModelIds)
        ? object.deletedModelIds.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.deleted_model_ids)
        ? object.deleted_model_ids.map((e: any) => globalThis.String(e))
        : [],
      failedModelIds: globalThis.Array.isArray(object?.failedModelIds)
        ? object.failedModelIds.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.failed_model_ids)
        ? object.failed_model_ids.map((e: any) => globalThis.String(e))
        : [],
      warnings: globalThis.Array.isArray(object?.warnings) ? object.warnings.map((e: any) => globalThis.String(e)) : [],
      errorMessage: isSet(object.errorMessage)
        ? globalThis.String(object.errorMessage)
        : isSet(object.error_message)
        ? globalThis.String(object.error_message)
        : "",
      skippedModelIds: globalThis.Array.isArray(object?.skippedModelIds)
        ? object.skippedModelIds.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.skipped_model_ids)
        ? object.skipped_model_ids.map((e: any) => globalThis.String(e))
        : [],
      dryRun: isSet(object.dryRun)
        ? globalThis.Boolean(object.dryRun)
        : isSet(object.dry_run)
        ? globalThis.Boolean(object.dry_run)
        : false,
      registryUpdated: isSet(object.registryUpdated)
        ? globalThis.Boolean(object.registryUpdated)
        : isSet(object.registry_updated)
        ? globalThis.Boolean(object.registry_updated)
        : false,
      filesDeleted: isSet(object.filesDeleted)
        ? globalThis.Boolean(object.filesDeleted)
        : isSet(object.files_deleted)
        ? globalThis.Boolean(object.files_deleted)
        : false,
    };
  },

  toJSON(message: StorageDeleteResult): unknown {
    const obj: any = {};
    if (message.success !== false) {
      obj.success = message.success;
    }
    if (message.deletedBytes !== 0) {
      obj.deletedBytes = Math.round(message.deletedBytes);
    }
    if (message.deletedModelIds?.length) {
      obj.deletedModelIds = message.deletedModelIds;
    }
    if (message.failedModelIds?.length) {
      obj.failedModelIds = message.failedModelIds;
    }
    if (message.warnings?.length) {
      obj.warnings = message.warnings;
    }
    if (message.errorMessage !== "") {
      obj.errorMessage = message.errorMessage;
    }
    if (message.skippedModelIds?.length) {
      obj.skippedModelIds = message.skippedModelIds;
    }
    if (message.dryRun !== false) {
      obj.dryRun = message.dryRun;
    }
    if (message.registryUpdated !== false) {
      obj.registryUpdated = message.registryUpdated;
    }
    if (message.filesDeleted !== false) {
      obj.filesDeleted = message.filesDeleted;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StorageDeleteResult>, I>>(base?: I): StorageDeleteResult {
    return StorageDeleteResult.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StorageDeleteResult>, I>>(object: I): StorageDeleteResult {
    const message = createBaseStorageDeleteResult();
    message.success = object.success ?? false;
    message.deletedBytes = object.deletedBytes ?? 0;
    message.deletedModelIds = object.deletedModelIds?.map((e) => e) || [];
    message.failedModelIds = object.failedModelIds?.map((e) => e) || [];
    message.warnings = object.warnings?.map((e) => e) || [];
    message.errorMessage = object.errorMessage ?? "";
    message.skippedModelIds = object.skippedModelIds?.map((e) => e) || [];
    message.dryRun = object.dryRun ?? false;
    message.registryUpdated = object.registryUpdated ?? false;
    message.filesDeleted = object.filesDeleted ?? false;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
