// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.35.1
// source: stt_options.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  AudioFormat,
  audioFormatFromJSON,
  audioFormatToJSON,
  InferenceFramework,
  inferenceFrameworkFromJSON,
  inferenceFrameworkToJSON,
} from "./model_types";

export const protobufPackage = "runanywhere.v1";

/**
 * ---------------------------------------------------------------------------
 * STT language hint. Sources pre-IDL:
 *   Swift  STTConfiguration default = "en-US", STTOptions default = "en"
 *   Kotlin STTConfiguration default = "en-US", STTOptions default = "en"
 *   Dart   STTOptions language nullable; auto-detect when null
 *   RN     STTOptions.language?: string (free-form)
 *   Web    STTTranscribeOptions.language?: string (free-form)
 *   C ABI  RAC_STT_DEFAULT_LANGUAGE = "en"
 * Free-form BCP-47 strings are collapsed to base language codes here.
 * AUTO is the explicit "detect from audio" sentinel; UNSPECIFIED falls
 * back to the backend default (typically "en").
 * ---------------------------------------------------------------------------
 * `rac_wire_string` annotations expose the BCP-47 base code for each value via
 * the codegen-generated `wireString` accessor (see idl/rac_options.proto and
 * idl/codegen/generate_swift_convenience.py). Swift SDK `bcp47Code` is sourced
 * from this annotation; the unspecified case falls back to "" by default.
 */
export enum STTLanguage {
  STT_LANGUAGE_UNSPECIFIED = 0,
  /** STT_LANGUAGE_AUTO - Auto-detect from audio */
  STT_LANGUAGE_AUTO = 1,
  STT_LANGUAGE_EN = 2,
  STT_LANGUAGE_ES = 3,
  STT_LANGUAGE_FR = 4,
  STT_LANGUAGE_DE = 5,
  STT_LANGUAGE_ZH = 6,
  STT_LANGUAGE_JA = 7,
  STT_LANGUAGE_KO = 8,
  STT_LANGUAGE_IT = 9,
  STT_LANGUAGE_PT = 10,
  STT_LANGUAGE_AR = 11,
  STT_LANGUAGE_RU = 12,
  STT_LANGUAGE_HI = 13,
  UNRECOGNIZED = -1,
}

export function sTTLanguageFromJSON(object: any): STTLanguage {
  switch (object) {
    case 0:
    case "STT_LANGUAGE_UNSPECIFIED":
      return STTLanguage.STT_LANGUAGE_UNSPECIFIED;
    case 1:
    case "STT_LANGUAGE_AUTO":
      return STTLanguage.STT_LANGUAGE_AUTO;
    case 2:
    case "STT_LANGUAGE_EN":
      return STTLanguage.STT_LANGUAGE_EN;
    case 3:
    case "STT_LANGUAGE_ES":
      return STTLanguage.STT_LANGUAGE_ES;
    case 4:
    case "STT_LANGUAGE_FR":
      return STTLanguage.STT_LANGUAGE_FR;
    case 5:
    case "STT_LANGUAGE_DE":
      return STTLanguage.STT_LANGUAGE_DE;
    case 6:
    case "STT_LANGUAGE_ZH":
      return STTLanguage.STT_LANGUAGE_ZH;
    case 7:
    case "STT_LANGUAGE_JA":
      return STTLanguage.STT_LANGUAGE_JA;
    case 8:
    case "STT_LANGUAGE_KO":
      return STTLanguage.STT_LANGUAGE_KO;
    case 9:
    case "STT_LANGUAGE_IT":
      return STTLanguage.STT_LANGUAGE_IT;
    case 10:
    case "STT_LANGUAGE_PT":
      return STTLanguage.STT_LANGUAGE_PT;
    case 11:
    case "STT_LANGUAGE_AR":
      return STTLanguage.STT_LANGUAGE_AR;
    case 12:
    case "STT_LANGUAGE_RU":
      return STTLanguage.STT_LANGUAGE_RU;
    case 13:
    case "STT_LANGUAGE_HI":
      return STTLanguage.STT_LANGUAGE_HI;
    case -1:
    case "UNRECOGNIZED":
    default:
      return STTLanguage.UNRECOGNIZED;
  }
}

export function sTTLanguageToJSON(object: STTLanguage): string {
  switch (object) {
    case STTLanguage.STT_LANGUAGE_UNSPECIFIED:
      return "STT_LANGUAGE_UNSPECIFIED";
    case STTLanguage.STT_LANGUAGE_AUTO:
      return "STT_LANGUAGE_AUTO";
    case STTLanguage.STT_LANGUAGE_EN:
      return "STT_LANGUAGE_EN";
    case STTLanguage.STT_LANGUAGE_ES:
      return "STT_LANGUAGE_ES";
    case STTLanguage.STT_LANGUAGE_FR:
      return "STT_LANGUAGE_FR";
    case STTLanguage.STT_LANGUAGE_DE:
      return "STT_LANGUAGE_DE";
    case STTLanguage.STT_LANGUAGE_ZH:
      return "STT_LANGUAGE_ZH";
    case STTLanguage.STT_LANGUAGE_JA:
      return "STT_LANGUAGE_JA";
    case STTLanguage.STT_LANGUAGE_KO:
      return "STT_LANGUAGE_KO";
    case STTLanguage.STT_LANGUAGE_IT:
      return "STT_LANGUAGE_IT";
    case STTLanguage.STT_LANGUAGE_PT:
      return "STT_LANGUAGE_PT";
    case STTLanguage.STT_LANGUAGE_AR:
      return "STT_LANGUAGE_AR";
    case STTLanguage.STT_LANGUAGE_RU:
      return "STT_LANGUAGE_RU";
    case STTLanguage.STT_LANGUAGE_HI:
      return "STT_LANGUAGE_HI";
    case STTLanguage.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum STTAudioEncoding {
  STT_AUDIO_ENCODING_UNSPECIFIED = 0,
  STT_AUDIO_ENCODING_PCM_S16_LE = 1,
  STT_AUDIO_ENCODING_PCM_F32_LE = 2,
  /** STT_AUDIO_ENCODING_CONTAINER - WAV/MP3/FLAC/etc.; see AudioFormat. */
  STT_AUDIO_ENCODING_CONTAINER = 3,
  UNRECOGNIZED = -1,
}

export function sTTAudioEncodingFromJSON(object: any): STTAudioEncoding {
  switch (object) {
    case 0:
    case "STT_AUDIO_ENCODING_UNSPECIFIED":
      return STTAudioEncoding.STT_AUDIO_ENCODING_UNSPECIFIED;
    case 1:
    case "STT_AUDIO_ENCODING_PCM_S16_LE":
      return STTAudioEncoding.STT_AUDIO_ENCODING_PCM_S16_LE;
    case 2:
    case "STT_AUDIO_ENCODING_PCM_F32_LE":
      return STTAudioEncoding.STT_AUDIO_ENCODING_PCM_F32_LE;
    case 3:
    case "STT_AUDIO_ENCODING_CONTAINER":
      return STTAudioEncoding.STT_AUDIO_ENCODING_CONTAINER;
    case -1:
    case "UNRECOGNIZED":
    default:
      return STTAudioEncoding.UNRECOGNIZED;
  }
}

export function sTTAudioEncodingToJSON(object: STTAudioEncoding): string {
  switch (object) {
    case STTAudioEncoding.STT_AUDIO_ENCODING_UNSPECIFIED:
      return "STT_AUDIO_ENCODING_UNSPECIFIED";
    case STTAudioEncoding.STT_AUDIO_ENCODING_PCM_S16_LE:
      return "STT_AUDIO_ENCODING_PCM_S16_LE";
    case STTAudioEncoding.STT_AUDIO_ENCODING_PCM_F32_LE:
      return "STT_AUDIO_ENCODING_PCM_F32_LE";
    case STTAudioEncoding.STT_AUDIO_ENCODING_CONTAINER:
      return "STT_AUDIO_ENCODING_CONTAINER";
    case STTAudioEncoding.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum STTStreamEventKind {
  STT_STREAM_EVENT_KIND_UNSPECIFIED = 0,
  STT_STREAM_EVENT_KIND_STARTED = 1,
  STT_STREAM_EVENT_KIND_PARTIAL = 2,
  STT_STREAM_EVENT_KIND_FINAL = 3,
  STT_STREAM_EVENT_KIND_ENDPOINT = 4,
  STT_STREAM_EVENT_KIND_ERROR = 5,
  UNRECOGNIZED = -1,
}

export function sTTStreamEventKindFromJSON(object: any): STTStreamEventKind {
  switch (object) {
    case 0:
    case "STT_STREAM_EVENT_KIND_UNSPECIFIED":
      return STTStreamEventKind.STT_STREAM_EVENT_KIND_UNSPECIFIED;
    case 1:
    case "STT_STREAM_EVENT_KIND_STARTED":
      return STTStreamEventKind.STT_STREAM_EVENT_KIND_STARTED;
    case 2:
    case "STT_STREAM_EVENT_KIND_PARTIAL":
      return STTStreamEventKind.STT_STREAM_EVENT_KIND_PARTIAL;
    case 3:
    case "STT_STREAM_EVENT_KIND_FINAL":
      return STTStreamEventKind.STT_STREAM_EVENT_KIND_FINAL;
    case 4:
    case "STT_STREAM_EVENT_KIND_ENDPOINT":
      return STTStreamEventKind.STT_STREAM_EVENT_KIND_ENDPOINT;
    case 5:
    case "STT_STREAM_EVENT_KIND_ERROR":
      return STTStreamEventKind.STT_STREAM_EVENT_KIND_ERROR;
    case -1:
    case "UNRECOGNIZED":
    default:
      return STTStreamEventKind.UNRECOGNIZED;
  }
}

export function sTTStreamEventKindToJSON(object: STTStreamEventKind): string {
  switch (object) {
    case STTStreamEventKind.STT_STREAM_EVENT_KIND_UNSPECIFIED:
      return "STT_STREAM_EVENT_KIND_UNSPECIFIED";
    case STTStreamEventKind.STT_STREAM_EVENT_KIND_STARTED:
      return "STT_STREAM_EVENT_KIND_STARTED";
    case STTStreamEventKind.STT_STREAM_EVENT_KIND_PARTIAL:
      return "STT_STREAM_EVENT_KIND_PARTIAL";
    case STTStreamEventKind.STT_STREAM_EVENT_KIND_FINAL:
      return "STT_STREAM_EVENT_KIND_FINAL";
    case STTStreamEventKind.STT_STREAM_EVENT_KIND_ENDPOINT:
      return "STT_STREAM_EVENT_KIND_ENDPOINT";
    case STTStreamEventKind.STT_STREAM_EVENT_KIND_ERROR:
      return "STT_STREAM_EVENT_KIND_ERROR";
    case STTStreamEventKind.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/**
 * ---------------------------------------------------------------------------
 * STT component configuration (init-time settings).
 * Sources pre-IDL:
 *   Swift  STTTypes.swift:15           STTConfiguration
 *   Kotlin STTTypes.kt:27              STTConfiguration
 *   Dart   stt_configuration.dart:9    STTConfiguration
 *   C ABI  rac_stt_types.h:76          rac_stt_config_t
 *
 * Note: max_alternatives, enable_punctuation, enable_diarization, and
 * enable_timestamps appear in the pre-IDL configs but are runtime knobs
 * in the canonical model. They live on STTOptions; STTConfiguration
 * keeps only true init-time fields (model id, language, sample rate,
 * VAD toggle, audio format). Producers should mirror runtime knobs into
 * STTOptions when constructing requests.
 * ---------------------------------------------------------------------------
 */
export interface STTConfiguration {
  modelId: string;
  language: STTLanguage;
  sampleRate: number;
  enableVad: boolean;
  audioFormat: AudioFormat;
  /**
   * C ABI / legacy SDK config-level transcription defaults. These may be
   * mirrored into STTOptions by adapters for per-call overrides.
   */
  enablePunctuation: boolean;
  enableDiarization: boolean;
  vocabularyList: string[];
  /** 0 = backend/default */
  maxAlternatives: number;
  enableWordTimestamps: boolean;
  /** Preferred framework for the component. Absent = auto. */
  preferredFramework?:
    | InferenceFramework
    | undefined;
  /**
   * Free-form BCP-47 language tag ("en-US", "pt-BR", etc.) for callers
   * that cannot be represented by STTLanguage's base-code enum.
   */
  languageCode?: string | undefined;
}

/**
 * ---------------------------------------------------------------------------
 * STT runtime transcription options (per-call overrides).
 * Sources pre-IDL:
 *   Swift  STTTypes.swift:64           STTOptions  (10 fields)
 *   Kotlin STTTypes.kt:65              STTOptions  (10 fields)
 *   Dart   generation_types.dart:78    STTOptions  (10 fields)
 *   RN     STTTypes.ts:12              STTOptions  (5 fields, narrower)
 *   Web    STTTypes.ts:25              STTTranscribeOptions (2 fields)
 *   C ABI  rac_stt_types.h:130         rac_stt_options_t (8 fields)
 *
 * Per spec, this canonical message exposes: language, enable_punctuation,
 * enable_diarization, max_speakers, vocabulary_list, enable_word_timestamps,
 * beam_size. Other pre-IDL fields (audio_format, sample_rate, detect_language,
 * preferred_framework) are part of STTConfiguration or implied by
 * STT_LANGUAGE_AUTO.
 * ---------------------------------------------------------------------------
 */
export interface STTOptions {
  language: STTLanguage;
  enablePunctuation: boolean;
  enableDiarization: boolean;
  /** 0 = auto / unset */
  maxSpeakers: number;
  /** Custom vocabulary bias */
  vocabularyList: string[];
  enableWordTimestamps: boolean;
  /** 0 = backend default */
  beamSize: number;
  /**
   * Free-form BCP-47 language tag. When set, consumers should prefer this
   * over the base-language enum above.
   */
  languageCode?:
    | string
    | undefined;
  /**
   * Explicit language auto-detection flag for C ABI parity. Equivalent to
   * language == STT_LANGUAGE_AUTO for generated-only consumers.
   */
  detectLanguage: boolean;
  /** Per-call input audio hints mirrored from rac_stt_options_t. */
  audioFormat: AudioFormat;
  sampleRate: number;
  /** Maximum number of alternatives to return. 0 = backend/default. */
  maxAlternatives: number;
  /** Streaming/endpointer controls. 0 = backend/default. */
  chunkDurationMs: number;
  endpointSilenceMs: number;
  suppressBlank: boolean;
  translateToEnglish: boolean;
}

export interface STTAudioSource {
  audioData?: Uint8Array | undefined;
  fileUri?: string | undefined;
  adapterHandle?: string | undefined;
  encoding: STTAudioEncoding;
  audioFormat: AudioFormat;
  sampleRate: number;
  channels: number;
  bitsPerSample: number;
  durationMs: number;
}

export interface STTTranscriptionRequest {
  requestId: string;
  audio?: STTAudioSource | undefined;
  options?: STTOptions | undefined;
  metadata: { [key: string]: string };
}

export interface STTTranscriptionRequest_MetadataEntry {
  key: string;
  value: string;
}

/**
 * ---------------------------------------------------------------------------
 * Word-level timestamp.
 * Sources pre-IDL:
 *   Swift  STTTypes.swift:260          WordTimestamp (TimeInterval seconds)
 *   Kotlin STTTypes.kt:141             WordTimestamp (Double seconds)
 *   Dart   generation_types.dart:124   WordTimestamp (double seconds, conf?)
 *   RN     STTTypes.ts:55              WordTimestamp (number seconds)
 *   Web    STTTypes.ts:18              STTWord       (number ms)
 *   C ABI  rac_stt_types.h:175         rac_stt_word_t (int64 ms)
 *
 * Canonicalize on int64 *_ms (matches C ABI and Web).
 * ---------------------------------------------------------------------------
 */
export interface WordTimestamp {
  word: string;
  startMs: number;
  endMs: number;
  confidence: number;
  speakerId?: string | undefined;
}

/**
 * ---------------------------------------------------------------------------
 * Alternative transcription hypothesis (n-best).
 * Sources pre-IDL:
 *   Swift  STTTypes.swift:275          TranscriptionAlternative (text, confidence)
 *   Kotlin STTTypes.kt:155             TranscriptionAlternative (text, confidence)
 *   Dart   generation_types.dart:146   TranscriptionAlternative (transcript, confidence)
 *   RN     STTTypes.ts:65              STTAlternative (text, confidence)
 *   C ABI  rac_stt_types.h:320         rac_transcription_alternative_t (text, confidence)
 *
 * Drift: Dart uses `transcript` while everyone else uses `text`. Canonical
 * field name is `text`. Per-word breakdown is OPTIONAL (only some backends
 * emit it for alternatives).
 * ---------------------------------------------------------------------------
 */
export interface TranscriptionAlternative {
  text: string;
  confidence: number;
  words: WordTimestamp[];
}

/**
 * ---------------------------------------------------------------------------
 * Per-pass transcription metadata.
 * Sources pre-IDL:
 *   Swift  STTTypes.swift:241          TranscriptionMetadata (s + computed RTF)
 *   Kotlin STTTypes.kt:124             TranscriptionMetadata (s + computed RTF)
 *   Dart   generation_types.dart:160   TranscriptionMetadata (s + computed RTF)
 *   RN     STTTypes.ts:73              TranscriptionMetadata (s + optional RTF)
 *   C ABI  rac_stt_types.h:297         rac_transcription_metadata_t (ms + RTF)
 *
 * Canonicalize on ms (matches C ABI). real_time_factor is producer-set;
 * consumers may recompute as processing_time_ms / audio_length_ms.
 * ---------------------------------------------------------------------------
 */
export interface TranscriptionMetadata {
  modelId: string;
  processingTimeMs: number;
  audioLengthMs: number;
  realTimeFactor: number;
}

/**
 * ---------------------------------------------------------------------------
 * Final STT output.
 * Sources pre-IDL:
 *   Swift  STTTypes.swift:147          STTOutput (text, conf, words, lang, alts, meta, ts)
 *   Kotlin STTTypes.kt:100             STTOutput (text, conf, words, lang, alts, meta, ts)
 *   Dart   generation_types.dart:218   STTResult / STTOutput (text, conf, durMs, lang, words, alts, meta, ts)
 *   RN     STTTypes.ts:32              STTOutput (text, conf, words, lang, alts, meta)
 *   Web    STTTypes.ts:9               STTTranscriptionResult (text, conf, lang, procMs, words)
 *   C ABI  rac_stt_types.h:338         rac_stt_output_t (text, conf, words, lang, alts, meta, ts_ms)
 *
 * Drift reconciled:
 *   - language: detected language. Promoted to STTLanguage enum.
 *   - durationMs (Dart) / processingTimeMs (Web) → captured in metadata.
 * ---------------------------------------------------------------------------
 */
export interface STTOutput {
  text: string;
  language: STTLanguage;
  confidence: number;
  words: WordTimestamp[];
  alternatives: TranscriptionAlternative[];
  metadata?:
    | TranscriptionMetadata
    | undefined;
  /** Free-form detected language tag, preserving regional variants. */
  languageCode?:
    | string
    | undefined;
  /** Wall-clock output timestamp in milliseconds since Unix epoch. */
  timestampMs: number;
  /**
   * Audio duration in milliseconds for SDKs that expose duration directly.
   * Often duplicates metadata.audio_length_ms.
   */
  durationMs: number;
  /** Diarization summary when available. */
  speakerIds: string[];
  /** Terminal error details for result-envelope APIs. */
  errorMessage?: string | undefined;
  errorCode: number;
  /** Segment index for long-running/streaming transcription. */
  segmentIndex: number;
}

/**
 * ---------------------------------------------------------------------------
 * Streaming partial result emitted during live transcription.
 * Sources pre-IDL:
 *   Dart   generation_types.dart:184   STTPartialResult (transcript, conf, isFinal, lang, ts, alts)
 *   RN     STTTypes.ts:90              STTPartialResult (transcript, conf, ts, lang, alts, isFinal)
 *   C ABI  rac_stt_types.h:240         rac_stt_stream_callback_t (partial_text, is_final)
 *   Web    STTTypes.ts:31              STTStreamCallback (text, isFinal)
 *
 * Canonical minimal shape per spec: text, is_final, stability. Full word
 * timestamps + alternatives flow through STTOutput on the terminal event.
 * `stability` is the Whisper-style hypothesis stability score (0.0-1.0);
 * 0.0 when backend does not provide one.
 * ---------------------------------------------------------------------------
 */
export interface STTPartialResult {
  text: string;
  isFinal: boolean;
  stability: number;
  /** Additional partial-hypothesis fields carried by Dart/RN live streams. */
  confidence: number;
  language: STTLanguage;
  timestampMs: number;
  alternatives: TranscriptionAlternative[];
  languageCode?:
    | string
    | undefined;
  /** Streaming correlation and endpointing metadata. */
  requestId: string;
  segmentIndex: number;
  audioStartMs: number;
  audioEndMs: number;
  finalOutput?: STTOutput | undefined;
}

export interface STTStreamEvent {
  seq: number;
  timestampUs: number;
  requestId: string;
  kind: STTStreamEventKind;
  partial?: STTPartialResult | undefined;
  finalOutput?: STTOutput | undefined;
  errorMessage?: string | undefined;
  errorCode: number;
}

export interface STTServiceState {
  isReady: boolean;
  currentModel?: string | undefined;
  supportsStreaming: boolean;
  supportedLanguageCodes: string[];
  errorMessage?: string | undefined;
  errorCode: number;
}

export interface STTLanguageDetectionResult {
  language: STTLanguage;
  languageCode?: string | undefined;
  confidence: number;
  alternatives: string[];
}

function createBaseSTTConfiguration(): STTConfiguration {
  return {
    modelId: "",
    language: 0,
    sampleRate: 0,
    enableVad: false,
    audioFormat: 0,
    enablePunctuation: false,
    enableDiarization: false,
    vocabularyList: [],
    maxAlternatives: 0,
    enableWordTimestamps: false,
    preferredFramework: undefined,
    languageCode: undefined,
  };
}

export const STTConfiguration: MessageFns<STTConfiguration> = {
  encode(message: STTConfiguration, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.modelId !== "") {
      writer.uint32(10).string(message.modelId);
    }
    if (message.language !== 0) {
      writer.uint32(16).int32(message.language);
    }
    if (message.sampleRate !== 0) {
      writer.uint32(24).int32(message.sampleRate);
    }
    if (message.enableVad !== false) {
      writer.uint32(32).bool(message.enableVad);
    }
    if (message.audioFormat !== 0) {
      writer.uint32(40).int32(message.audioFormat);
    }
    if (message.enablePunctuation !== false) {
      writer.uint32(48).bool(message.enablePunctuation);
    }
    if (message.enableDiarization !== false) {
      writer.uint32(56).bool(message.enableDiarization);
    }
    for (const v of message.vocabularyList) {
      writer.uint32(66).string(v!);
    }
    if (message.maxAlternatives !== 0) {
      writer.uint32(72).int32(message.maxAlternatives);
    }
    if (message.enableWordTimestamps !== false) {
      writer.uint32(80).bool(message.enableWordTimestamps);
    }
    if (message.preferredFramework !== undefined) {
      writer.uint32(88).int32(message.preferredFramework);
    }
    if (message.languageCode !== undefined) {
      writer.uint32(98).string(message.languageCode);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): STTConfiguration {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSTTConfiguration();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.modelId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.language = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.sampleRate = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.enableVad = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.audioFormat = reader.int32() as any;
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.enablePunctuation = reader.bool();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.enableDiarization = reader.bool();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.vocabularyList.push(reader.string());
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.maxAlternatives = reader.int32();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.enableWordTimestamps = reader.bool();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.preferredFramework = reader.int32() as any;
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.languageCode = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): STTConfiguration {
    return {
      modelId: isSet(object.modelId)
        ? globalThis.String(object.modelId)
        : isSet(object.model_id)
        ? globalThis.String(object.model_id)
        : "",
      language: isSet(object.language) ? sTTLanguageFromJSON(object.language) : 0,
      sampleRate: isSet(object.sampleRate)
        ? globalThis.Number(object.sampleRate)
        : isSet(object.sample_rate)
        ? globalThis.Number(object.sample_rate)
        : 0,
      enableVad: isSet(object.enableVad)
        ? globalThis.Boolean(object.enableVad)
        : isSet(object.enable_vad)
        ? globalThis.Boolean(object.enable_vad)
        : false,
      audioFormat: isSet(object.audioFormat)
        ? audioFormatFromJSON(object.audioFormat)
        : isSet(object.audio_format)
        ? audioFormatFromJSON(object.audio_format)
        : 0,
      enablePunctuation: isSet(object.enablePunctuation)
        ? globalThis.Boolean(object.enablePunctuation)
        : isSet(object.enable_punctuation)
        ? globalThis.Boolean(object.enable_punctuation)
        : false,
      enableDiarization: isSet(object.enableDiarization)
        ? globalThis.Boolean(object.enableDiarization)
        : isSet(object.enable_diarization)
        ? globalThis.Boolean(object.enable_diarization)
        : false,
      vocabularyList: globalThis.Array.isArray(object?.vocabularyList)
        ? object.vocabularyList.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.vocabulary_list)
        ? object.vocabulary_list.map((e: any) => globalThis.String(e))
        : [],
      maxAlternatives: isSet(object.maxAlternatives)
        ? globalThis.Number(object.maxAlternatives)
        : isSet(object.max_alternatives)
        ? globalThis.Number(object.max_alternatives)
        : 0,
      enableWordTimestamps: isSet(object.enableWordTimestamps)
        ? globalThis.Boolean(object.enableWordTimestamps)
        : isSet(object.enable_word_timestamps)
        ? globalThis.Boolean(object.enable_word_timestamps)
        : false,
      preferredFramework: isSet(object.preferredFramework)
        ? inferenceFrameworkFromJSON(object.preferredFramework)
        : isSet(object.preferred_framework)
        ? inferenceFrameworkFromJSON(object.preferred_framework)
        : undefined,
      languageCode: isSet(object.languageCode)
        ? globalThis.String(object.languageCode)
        : isSet(object.language_code)
        ? globalThis.String(object.language_code)
        : undefined,
    };
  },

  toJSON(message: STTConfiguration): unknown {
    const obj: any = {};
    if (message.modelId !== "") {
      obj.modelId = message.modelId;
    }
    if (message.language !== 0) {
      obj.language = sTTLanguageToJSON(message.language);
    }
    if (message.sampleRate !== 0) {
      obj.sampleRate = Math.round(message.sampleRate);
    }
    if (message.enableVad !== false) {
      obj.enableVad = message.enableVad;
    }
    if (message.audioFormat !== 0) {
      obj.audioFormat = audioFormatToJSON(message.audioFormat);
    }
    if (message.enablePunctuation !== false) {
      obj.enablePunctuation = message.enablePunctuation;
    }
    if (message.enableDiarization !== false) {
      obj.enableDiarization = message.enableDiarization;
    }
    if (message.vocabularyList?.length) {
      obj.vocabularyList = message.vocabularyList;
    }
    if (message.maxAlternatives !== 0) {
      obj.maxAlternatives = Math.round(message.maxAlternatives);
    }
    if (message.enableWordTimestamps !== false) {
      obj.enableWordTimestamps = message.enableWordTimestamps;
    }
    if (message.preferredFramework !== undefined) {
      obj.preferredFramework = inferenceFrameworkToJSON(message.preferredFramework);
    }
    if (message.languageCode !== undefined) {
      obj.languageCode = message.languageCode;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<STTConfiguration>, I>>(base?: I): STTConfiguration {
    return STTConfiguration.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<STTConfiguration>, I>>(object: I): STTConfiguration {
    const message = createBaseSTTConfiguration();
    message.modelId = object.modelId ?? "";
    message.language = object.language ?? 0;
    message.sampleRate = object.sampleRate ?? 0;
    message.enableVad = object.enableVad ?? false;
    message.audioFormat = object.audioFormat ?? 0;
    message.enablePunctuation = object.enablePunctuation ?? false;
    message.enableDiarization = object.enableDiarization ?? false;
    message.vocabularyList = object.vocabularyList?.map((e) => e) || [];
    message.maxAlternatives = object.maxAlternatives ?? 0;
    message.enableWordTimestamps = object.enableWordTimestamps ?? false;
    message.preferredFramework = object.preferredFramework ?? undefined;
    message.languageCode = object.languageCode ?? undefined;
    return message;
  },
};

function createBaseSTTOptions(): STTOptions {
  return {
    language: 0,
    enablePunctuation: false,
    enableDiarization: false,
    maxSpeakers: 0,
    vocabularyList: [],
    enableWordTimestamps: false,
    beamSize: 0,
    languageCode: undefined,
    detectLanguage: false,
    audioFormat: 0,
    sampleRate: 0,
    maxAlternatives: 0,
    chunkDurationMs: 0,
    endpointSilenceMs: 0,
    suppressBlank: false,
    translateToEnglish: false,
  };
}

export const STTOptions: MessageFns<STTOptions> = {
  encode(message: STTOptions, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.language !== 0) {
      writer.uint32(8).int32(message.language);
    }
    if (message.enablePunctuation !== false) {
      writer.uint32(16).bool(message.enablePunctuation);
    }
    if (message.enableDiarization !== false) {
      writer.uint32(24).bool(message.enableDiarization);
    }
    if (message.maxSpeakers !== 0) {
      writer.uint32(32).int32(message.maxSpeakers);
    }
    for (const v of message.vocabularyList) {
      writer.uint32(42).string(v!);
    }
    if (message.enableWordTimestamps !== false) {
      writer.uint32(48).bool(message.enableWordTimestamps);
    }
    if (message.beamSize !== 0) {
      writer.uint32(56).int32(message.beamSize);
    }
    if (message.languageCode !== undefined) {
      writer.uint32(66).string(message.languageCode);
    }
    if (message.detectLanguage !== false) {
      writer.uint32(72).bool(message.detectLanguage);
    }
    if (message.audioFormat !== 0) {
      writer.uint32(80).int32(message.audioFormat);
    }
    if (message.sampleRate !== 0) {
      writer.uint32(88).int32(message.sampleRate);
    }
    if (message.maxAlternatives !== 0) {
      writer.uint32(96).int32(message.maxAlternatives);
    }
    if (message.chunkDurationMs !== 0) {
      writer.uint32(104).int32(message.chunkDurationMs);
    }
    if (message.endpointSilenceMs !== 0) {
      writer.uint32(112).int32(message.endpointSilenceMs);
    }
    if (message.suppressBlank !== false) {
      writer.uint32(120).bool(message.suppressBlank);
    }
    if (message.translateToEnglish !== false) {
      writer.uint32(128).bool(message.translateToEnglish);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): STTOptions {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSTTOptions();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.language = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.enablePunctuation = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.enableDiarization = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.maxSpeakers = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.vocabularyList.push(reader.string());
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.enableWordTimestamps = reader.bool();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.beamSize = reader.int32();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.languageCode = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.detectLanguage = reader.bool();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.audioFormat = reader.int32() as any;
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.sampleRate = reader.int32();
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.maxAlternatives = reader.int32();
          continue;
        }
        case 13: {
          if (tag !== 104) {
            break;
          }

          message.chunkDurationMs = reader.int32();
          continue;
        }
        case 14: {
          if (tag !== 112) {
            break;
          }

          message.endpointSilenceMs = reader.int32();
          continue;
        }
        case 15: {
          if (tag !== 120) {
            break;
          }

          message.suppressBlank = reader.bool();
          continue;
        }
        case 16: {
          if (tag !== 128) {
            break;
          }

          message.translateToEnglish = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): STTOptions {
    return {
      language: isSet(object.language) ? sTTLanguageFromJSON(object.language) : 0,
      enablePunctuation: isSet(object.enablePunctuation)
        ? globalThis.Boolean(object.enablePunctuation)
        : isSet(object.enable_punctuation)
        ? globalThis.Boolean(object.enable_punctuation)
        : false,
      enableDiarization: isSet(object.enableDiarization)
        ? globalThis.Boolean(object.enableDiarization)
        : isSet(object.enable_diarization)
        ? globalThis.Boolean(object.enable_diarization)
        : false,
      maxSpeakers: isSet(object.maxSpeakers)
        ? globalThis.Number(object.maxSpeakers)
        : isSet(object.max_speakers)
        ? globalThis.Number(object.max_speakers)
        : 0,
      vocabularyList: globalThis.Array.isArray(object?.vocabularyList)
        ? object.vocabularyList.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.vocabulary_list)
        ? object.vocabulary_list.map((e: any) => globalThis.String(e))
        : [],
      enableWordTimestamps: isSet(object.enableWordTimestamps)
        ? globalThis.Boolean(object.enableWordTimestamps)
        : isSet(object.enable_word_timestamps)
        ? globalThis.Boolean(object.enable_word_timestamps)
        : false,
      beamSize: isSet(object.beamSize)
        ? globalThis.Number(object.beamSize)
        : isSet(object.beam_size)
        ? globalThis.Number(object.beam_size)
        : 0,
      languageCode: isSet(object.languageCode)
        ? globalThis.String(object.languageCode)
        : isSet(object.language_code)
        ? globalThis.String(object.language_code)
        : undefined,
      detectLanguage: isSet(object.detectLanguage)
        ? globalThis.Boolean(object.detectLanguage)
        : isSet(object.detect_language)
        ? globalThis.Boolean(object.detect_language)
        : false,
      audioFormat: isSet(object.audioFormat)
        ? audioFormatFromJSON(object.audioFormat)
        : isSet(object.audio_format)
        ? audioFormatFromJSON(object.audio_format)
        : 0,
      sampleRate: isSet(object.sampleRate)
        ? globalThis.Number(object.sampleRate)
        : isSet(object.sample_rate)
        ? globalThis.Number(object.sample_rate)
        : 0,
      maxAlternatives: isSet(object.maxAlternatives)
        ? globalThis.Number(object.maxAlternatives)
        : isSet(object.max_alternatives)
        ? globalThis.Number(object.max_alternatives)
        : 0,
      chunkDurationMs: isSet(object.chunkDurationMs)
        ? globalThis.Number(object.chunkDurationMs)
        : isSet(object.chunk_duration_ms)
        ? globalThis.Number(object.chunk_duration_ms)
        : 0,
      endpointSilenceMs: isSet(object.endpointSilenceMs)
        ? globalThis.Number(object.endpointSilenceMs)
        : isSet(object.endpoint_silence_ms)
        ? globalThis.Number(object.endpoint_silence_ms)
        : 0,
      suppressBlank: isSet(object.suppressBlank)
        ? globalThis.Boolean(object.suppressBlank)
        : isSet(object.suppress_blank)
        ? globalThis.Boolean(object.suppress_blank)
        : false,
      translateToEnglish: isSet(object.translateToEnglish)
        ? globalThis.Boolean(object.translateToEnglish)
        : isSet(object.translate_to_english)
        ? globalThis.Boolean(object.translate_to_english)
        : false,
    };
  },

  toJSON(message: STTOptions): unknown {
    const obj: any = {};
    if (message.language !== 0) {
      obj.language = sTTLanguageToJSON(message.language);
    }
    if (message.enablePunctuation !== false) {
      obj.enablePunctuation = message.enablePunctuation;
    }
    if (message.enableDiarization !== false) {
      obj.enableDiarization = message.enableDiarization;
    }
    if (message.maxSpeakers !== 0) {
      obj.maxSpeakers = Math.round(message.maxSpeakers);
    }
    if (message.vocabularyList?.length) {
      obj.vocabularyList = message.vocabularyList;
    }
    if (message.enableWordTimestamps !== false) {
      obj.enableWordTimestamps = message.enableWordTimestamps;
    }
    if (message.beamSize !== 0) {
      obj.beamSize = Math.round(message.beamSize);
    }
    if (message.languageCode !== undefined) {
      obj.languageCode = message.languageCode;
    }
    if (message.detectLanguage !== false) {
      obj.detectLanguage = message.detectLanguage;
    }
    if (message.audioFormat !== 0) {
      obj.audioFormat = audioFormatToJSON(message.audioFormat);
    }
    if (message.sampleRate !== 0) {
      obj.sampleRate = Math.round(message.sampleRate);
    }
    if (message.maxAlternatives !== 0) {
      obj.maxAlternatives = Math.round(message.maxAlternatives);
    }
    if (message.chunkDurationMs !== 0) {
      obj.chunkDurationMs = Math.round(message.chunkDurationMs);
    }
    if (message.endpointSilenceMs !== 0) {
      obj.endpointSilenceMs = Math.round(message.endpointSilenceMs);
    }
    if (message.suppressBlank !== false) {
      obj.suppressBlank = message.suppressBlank;
    }
    if (message.translateToEnglish !== false) {
      obj.translateToEnglish = message.translateToEnglish;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<STTOptions>, I>>(base?: I): STTOptions {
    return STTOptions.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<STTOptions>, I>>(object: I): STTOptions {
    const message = createBaseSTTOptions();
    message.language = object.language ?? 0;
    message.enablePunctuation = object.enablePunctuation ?? false;
    message.enableDiarization = object.enableDiarization ?? false;
    message.maxSpeakers = object.maxSpeakers ?? 0;
    message.vocabularyList = object.vocabularyList?.map((e) => e) || [];
    message.enableWordTimestamps = object.enableWordTimestamps ?? false;
    message.beamSize = object.beamSize ?? 0;
    message.languageCode = object.languageCode ?? undefined;
    message.detectLanguage = object.detectLanguage ?? false;
    message.audioFormat = object.audioFormat ?? 0;
    message.sampleRate = object.sampleRate ?? 0;
    message.maxAlternatives = object.maxAlternatives ?? 0;
    message.chunkDurationMs = object.chunkDurationMs ?? 0;
    message.endpointSilenceMs = object.endpointSilenceMs ?? 0;
    message.suppressBlank = object.suppressBlank ?? false;
    message.translateToEnglish = object.translateToEnglish ?? false;
    return message;
  },
};

function createBaseSTTAudioSource(): STTAudioSource {
  return {
    audioData: undefined,
    fileUri: undefined,
    adapterHandle: undefined,
    encoding: 0,
    audioFormat: 0,
    sampleRate: 0,
    channels: 0,
    bitsPerSample: 0,
    durationMs: 0,
  };
}

export const STTAudioSource: MessageFns<STTAudioSource> = {
  encode(message: STTAudioSource, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.audioData !== undefined) {
      writer.uint32(10).bytes(message.audioData);
    }
    if (message.fileUri !== undefined) {
      writer.uint32(18).string(message.fileUri);
    }
    if (message.adapterHandle !== undefined) {
      writer.uint32(26).string(message.adapterHandle);
    }
    if (message.encoding !== 0) {
      writer.uint32(32).int32(message.encoding);
    }
    if (message.audioFormat !== 0) {
      writer.uint32(40).int32(message.audioFormat);
    }
    if (message.sampleRate !== 0) {
      writer.uint32(48).int32(message.sampleRate);
    }
    if (message.channels !== 0) {
      writer.uint32(56).int32(message.channels);
    }
    if (message.bitsPerSample !== 0) {
      writer.uint32(64).int32(message.bitsPerSample);
    }
    if (message.durationMs !== 0) {
      writer.uint32(72).int64(message.durationMs);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): STTAudioSource {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSTTAudioSource();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.audioData = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.fileUri = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.adapterHandle = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.encoding = reader.int32() as any;
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.audioFormat = reader.int32() as any;
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.sampleRate = reader.int32();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.channels = reader.int32();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.bitsPerSample = reader.int32();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.durationMs = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): STTAudioSource {
    return {
      audioData: isSet(object.audioData)
        ? bytesFromBase64(object.audioData)
        : isSet(object.audio_data)
        ? bytesFromBase64(object.audio_data)
        : undefined,
      fileUri: isSet(object.fileUri)
        ? globalThis.String(object.fileUri)
        : isSet(object.file_uri)
        ? globalThis.String(object.file_uri)
        : undefined,
      adapterHandle: isSet(object.adapterHandle)
        ? globalThis.String(object.adapterHandle)
        : isSet(object.adapter_handle)
        ? globalThis.String(object.adapter_handle)
        : undefined,
      encoding: isSet(object.encoding) ? sTTAudioEncodingFromJSON(object.encoding) : 0,
      audioFormat: isSet(object.audioFormat)
        ? audioFormatFromJSON(object.audioFormat)
        : isSet(object.audio_format)
        ? audioFormatFromJSON(object.audio_format)
        : 0,
      sampleRate: isSet(object.sampleRate)
        ? globalThis.Number(object.sampleRate)
        : isSet(object.sample_rate)
        ? globalThis.Number(object.sample_rate)
        : 0,
      channels: isSet(object.channels) ? globalThis.Number(object.channels) : 0,
      bitsPerSample: isSet(object.bitsPerSample)
        ? globalThis.Number(object.bitsPerSample)
        : isSet(object.bits_per_sample)
        ? globalThis.Number(object.bits_per_sample)
        : 0,
      durationMs: isSet(object.durationMs)
        ? globalThis.Number(object.durationMs)
        : isSet(object.duration_ms)
        ? globalThis.Number(object.duration_ms)
        : 0,
    };
  },

  toJSON(message: STTAudioSource): unknown {
    const obj: any = {};
    if (message.audioData !== undefined) {
      obj.audioData = base64FromBytes(message.audioData);
    }
    if (message.fileUri !== undefined) {
      obj.fileUri = message.fileUri;
    }
    if (message.adapterHandle !== undefined) {
      obj.adapterHandle = message.adapterHandle;
    }
    if (message.encoding !== 0) {
      obj.encoding = sTTAudioEncodingToJSON(message.encoding);
    }
    if (message.audioFormat !== 0) {
      obj.audioFormat = audioFormatToJSON(message.audioFormat);
    }
    if (message.sampleRate !== 0) {
      obj.sampleRate = Math.round(message.sampleRate);
    }
    if (message.channels !== 0) {
      obj.channels = Math.round(message.channels);
    }
    if (message.bitsPerSample !== 0) {
      obj.bitsPerSample = Math.round(message.bitsPerSample);
    }
    if (message.durationMs !== 0) {
      obj.durationMs = Math.round(message.durationMs);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<STTAudioSource>, I>>(base?: I): STTAudioSource {
    return STTAudioSource.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<STTAudioSource>, I>>(object: I): STTAudioSource {
    const message = createBaseSTTAudioSource();
    message.audioData = object.audioData ?? undefined;
    message.fileUri = object.fileUri ?? undefined;
    message.adapterHandle = object.adapterHandle ?? undefined;
    message.encoding = object.encoding ?? 0;
    message.audioFormat = object.audioFormat ?? 0;
    message.sampleRate = object.sampleRate ?? 0;
    message.channels = object.channels ?? 0;
    message.bitsPerSample = object.bitsPerSample ?? 0;
    message.durationMs = object.durationMs ?? 0;
    return message;
  },
};

function createBaseSTTTranscriptionRequest(): STTTranscriptionRequest {
  return { requestId: "", audio: undefined, options: undefined, metadata: {} };
}

export const STTTranscriptionRequest: MessageFns<STTTranscriptionRequest> = {
  encode(message: STTTranscriptionRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.requestId !== "") {
      writer.uint32(10).string(message.requestId);
    }
    if (message.audio !== undefined) {
      STTAudioSource.encode(message.audio, writer.uint32(18).fork()).join();
    }
    if (message.options !== undefined) {
      STTOptions.encode(message.options, writer.uint32(26).fork()).join();
    }
    globalThis.Object.entries(message.metadata).forEach(([key, value]: [string, string]) => {
      STTTranscriptionRequest_MetadataEntry.encode({ key: key as any, value }, writer.uint32(34).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): STTTranscriptionRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSTTTranscriptionRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.audio = STTAudioSource.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.options = STTOptions.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          const entry4 = STTTranscriptionRequest_MetadataEntry.decode(reader, reader.uint32());
          if (entry4.value !== undefined) {
            message.metadata[entry4.key] = entry4.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): STTTranscriptionRequest {
    return {
      requestId: isSet(object.requestId)
        ? globalThis.String(object.requestId)
        : isSet(object.request_id)
        ? globalThis.String(object.request_id)
        : "",
      audio: isSet(object.audio) ? STTAudioSource.fromJSON(object.audio) : undefined,
      options: isSet(object.options) ? STTOptions.fromJSON(object.options) : undefined,
      metadata: isObject(object.metadata)
        ? (globalThis.Object.entries(object.metadata) as [string, any][]).reduce(
          (acc: { [key: string]: string }, [key, value]: [string, any]) => {
            acc[key] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : {},
    };
  },

  toJSON(message: STTTranscriptionRequest): unknown {
    const obj: any = {};
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.audio !== undefined) {
      obj.audio = STTAudioSource.toJSON(message.audio);
    }
    if (message.options !== undefined) {
      obj.options = STTOptions.toJSON(message.options);
    }
    if (message.metadata) {
      const entries = globalThis.Object.entries(message.metadata) as [string, string][];
      if (entries.length > 0) {
        obj.metadata = {};
        entries.forEach(([k, v]) => {
          obj.metadata[k] = v;
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<STTTranscriptionRequest>, I>>(base?: I): STTTranscriptionRequest {
    return STTTranscriptionRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<STTTranscriptionRequest>, I>>(object: I): STTTranscriptionRequest {
    const message = createBaseSTTTranscriptionRequest();
    message.requestId = object.requestId ?? "";
    message.audio = (object.audio !== undefined && object.audio !== null)
      ? STTAudioSource.fromPartial(object.audio)
      : undefined;
    message.options = (object.options !== undefined && object.options !== null)
      ? STTOptions.fromPartial(object.options)
      : undefined;
    message.metadata = (globalThis.Object.entries(object.metadata ?? {}) as [string, string][]).reduce(
      (acc: { [key: string]: string }, [key, value]: [string, string]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    return message;
  },
};

function createBaseSTTTranscriptionRequest_MetadataEntry(): STTTranscriptionRequest_MetadataEntry {
  return { key: "", value: "" };
}

export const STTTranscriptionRequest_MetadataEntry: MessageFns<STTTranscriptionRequest_MetadataEntry> = {
  encode(message: STTTranscriptionRequest_MetadataEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): STTTranscriptionRequest_MetadataEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSTTTranscriptionRequest_MetadataEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): STTTranscriptionRequest_MetadataEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: STTTranscriptionRequest_MetadataEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<STTTranscriptionRequest_MetadataEntry>, I>>(
    base?: I,
  ): STTTranscriptionRequest_MetadataEntry {
    return STTTranscriptionRequest_MetadataEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<STTTranscriptionRequest_MetadataEntry>, I>>(
    object: I,
  ): STTTranscriptionRequest_MetadataEntry {
    const message = createBaseSTTTranscriptionRequest_MetadataEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseWordTimestamp(): WordTimestamp {
  return { word: "", startMs: 0, endMs: 0, confidence: 0, speakerId: undefined };
}

export const WordTimestamp: MessageFns<WordTimestamp> = {
  encode(message: WordTimestamp, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.word !== "") {
      writer.uint32(10).string(message.word);
    }
    if (message.startMs !== 0) {
      writer.uint32(16).int64(message.startMs);
    }
    if (message.endMs !== 0) {
      writer.uint32(24).int64(message.endMs);
    }
    if (message.confidence !== 0) {
      writer.uint32(37).float(message.confidence);
    }
    if (message.speakerId !== undefined) {
      writer.uint32(42).string(message.speakerId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): WordTimestamp {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWordTimestamp();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.word = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.startMs = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.endMs = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 37) {
            break;
          }

          message.confidence = reader.float();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.speakerId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): WordTimestamp {
    return {
      word: isSet(object.word) ? globalThis.String(object.word) : "",
      startMs: isSet(object.startMs)
        ? globalThis.Number(object.startMs)
        : isSet(object.start_ms)
        ? globalThis.Number(object.start_ms)
        : 0,
      endMs: isSet(object.endMs)
        ? globalThis.Number(object.endMs)
        : isSet(object.end_ms)
        ? globalThis.Number(object.end_ms)
        : 0,
      confidence: isSet(object.confidence) ? globalThis.Number(object.confidence) : 0,
      speakerId: isSet(object.speakerId)
        ? globalThis.String(object.speakerId)
        : isSet(object.speaker_id)
        ? globalThis.String(object.speaker_id)
        : undefined,
    };
  },

  toJSON(message: WordTimestamp): unknown {
    const obj: any = {};
    if (message.word !== "") {
      obj.word = message.word;
    }
    if (message.startMs !== 0) {
      obj.startMs = Math.round(message.startMs);
    }
    if (message.endMs !== 0) {
      obj.endMs = Math.round(message.endMs);
    }
    if (message.confidence !== 0) {
      obj.confidence = message.confidence;
    }
    if (message.speakerId !== undefined) {
      obj.speakerId = message.speakerId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<WordTimestamp>, I>>(base?: I): WordTimestamp {
    return WordTimestamp.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<WordTimestamp>, I>>(object: I): WordTimestamp {
    const message = createBaseWordTimestamp();
    message.word = object.word ?? "";
    message.startMs = object.startMs ?? 0;
    message.endMs = object.endMs ?? 0;
    message.confidence = object.confidence ?? 0;
    message.speakerId = object.speakerId ?? undefined;
    return message;
  },
};

function createBaseTranscriptionAlternative(): TranscriptionAlternative {
  return { text: "", confidence: 0, words: [] };
}

export const TranscriptionAlternative: MessageFns<TranscriptionAlternative> = {
  encode(message: TranscriptionAlternative, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.text !== "") {
      writer.uint32(10).string(message.text);
    }
    if (message.confidence !== 0) {
      writer.uint32(21).float(message.confidence);
    }
    for (const v of message.words) {
      WordTimestamp.encode(v!, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TranscriptionAlternative {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTranscriptionAlternative();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.text = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 21) {
            break;
          }

          message.confidence = reader.float();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.words.push(WordTimestamp.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TranscriptionAlternative {
    return {
      text: isSet(object.text) ? globalThis.String(object.text) : "",
      confidence: isSet(object.confidence) ? globalThis.Number(object.confidence) : 0,
      words: globalThis.Array.isArray(object?.words) ? object.words.map((e: any) => WordTimestamp.fromJSON(e)) : [],
    };
  },

  toJSON(message: TranscriptionAlternative): unknown {
    const obj: any = {};
    if (message.text !== "") {
      obj.text = message.text;
    }
    if (message.confidence !== 0) {
      obj.confidence = message.confidence;
    }
    if (message.words?.length) {
      obj.words = message.words.map((e) => WordTimestamp.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TranscriptionAlternative>, I>>(base?: I): TranscriptionAlternative {
    return TranscriptionAlternative.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TranscriptionAlternative>, I>>(object: I): TranscriptionAlternative {
    const message = createBaseTranscriptionAlternative();
    message.text = object.text ?? "";
    message.confidence = object.confidence ?? 0;
    message.words = object.words?.map((e) => WordTimestamp.fromPartial(e)) || [];
    return message;
  },
};

function createBaseTranscriptionMetadata(): TranscriptionMetadata {
  return { modelId: "", processingTimeMs: 0, audioLengthMs: 0, realTimeFactor: 0 };
}

export const TranscriptionMetadata: MessageFns<TranscriptionMetadata> = {
  encode(message: TranscriptionMetadata, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.modelId !== "") {
      writer.uint32(10).string(message.modelId);
    }
    if (message.processingTimeMs !== 0) {
      writer.uint32(16).int64(message.processingTimeMs);
    }
    if (message.audioLengthMs !== 0) {
      writer.uint32(24).int64(message.audioLengthMs);
    }
    if (message.realTimeFactor !== 0) {
      writer.uint32(37).float(message.realTimeFactor);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TranscriptionMetadata {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTranscriptionMetadata();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.modelId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.processingTimeMs = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.audioLengthMs = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 37) {
            break;
          }

          message.realTimeFactor = reader.float();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TranscriptionMetadata {
    return {
      modelId: isSet(object.modelId)
        ? globalThis.String(object.modelId)
        : isSet(object.model_id)
        ? globalThis.String(object.model_id)
        : "",
      processingTimeMs: isSet(object.processingTimeMs)
        ? globalThis.Number(object.processingTimeMs)
        : isSet(object.processing_time_ms)
        ? globalThis.Number(object.processing_time_ms)
        : 0,
      audioLengthMs: isSet(object.audioLengthMs)
        ? globalThis.Number(object.audioLengthMs)
        : isSet(object.audio_length_ms)
        ? globalThis.Number(object.audio_length_ms)
        : 0,
      realTimeFactor: isSet(object.realTimeFactor)
        ? globalThis.Number(object.realTimeFactor)
        : isSet(object.real_time_factor)
        ? globalThis.Number(object.real_time_factor)
        : 0,
    };
  },

  toJSON(message: TranscriptionMetadata): unknown {
    const obj: any = {};
    if (message.modelId !== "") {
      obj.modelId = message.modelId;
    }
    if (message.processingTimeMs !== 0) {
      obj.processingTimeMs = Math.round(message.processingTimeMs);
    }
    if (message.audioLengthMs !== 0) {
      obj.audioLengthMs = Math.round(message.audioLengthMs);
    }
    if (message.realTimeFactor !== 0) {
      obj.realTimeFactor = message.realTimeFactor;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TranscriptionMetadata>, I>>(base?: I): TranscriptionMetadata {
    return TranscriptionMetadata.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TranscriptionMetadata>, I>>(object: I): TranscriptionMetadata {
    const message = createBaseTranscriptionMetadata();
    message.modelId = object.modelId ?? "";
    message.processingTimeMs = object.processingTimeMs ?? 0;
    message.audioLengthMs = object.audioLengthMs ?? 0;
    message.realTimeFactor = object.realTimeFactor ?? 0;
    return message;
  },
};

function createBaseSTTOutput(): STTOutput {
  return {
    text: "",
    language: 0,
    confidence: 0,
    words: [],
    alternatives: [],
    metadata: undefined,
    languageCode: undefined,
    timestampMs: 0,
    durationMs: 0,
    speakerIds: [],
    errorMessage: undefined,
    errorCode: 0,
    segmentIndex: 0,
  };
}

export const STTOutput: MessageFns<STTOutput> = {
  encode(message: STTOutput, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.text !== "") {
      writer.uint32(10).string(message.text);
    }
    if (message.language !== 0) {
      writer.uint32(16).int32(message.language);
    }
    if (message.confidence !== 0) {
      writer.uint32(29).float(message.confidence);
    }
    for (const v of message.words) {
      WordTimestamp.encode(v!, writer.uint32(34).fork()).join();
    }
    for (const v of message.alternatives) {
      TranscriptionAlternative.encode(v!, writer.uint32(42).fork()).join();
    }
    if (message.metadata !== undefined) {
      TranscriptionMetadata.encode(message.metadata, writer.uint32(50).fork()).join();
    }
    if (message.languageCode !== undefined) {
      writer.uint32(58).string(message.languageCode);
    }
    if (message.timestampMs !== 0) {
      writer.uint32(64).int64(message.timestampMs);
    }
    if (message.durationMs !== 0) {
      writer.uint32(72).int64(message.durationMs);
    }
    for (const v of message.speakerIds) {
      writer.uint32(82).string(v!);
    }
    if (message.errorMessage !== undefined) {
      writer.uint32(90).string(message.errorMessage);
    }
    if (message.errorCode !== 0) {
      writer.uint32(96).int32(message.errorCode);
    }
    if (message.segmentIndex !== 0) {
      writer.uint32(104).int32(message.segmentIndex);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): STTOutput {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSTTOutput();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.text = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.language = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 29) {
            break;
          }

          message.confidence = reader.float();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.words.push(WordTimestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.alternatives.push(TranscriptionAlternative.decode(reader, reader.uint32()));
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.metadata = TranscriptionMetadata.decode(reader, reader.uint32());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.languageCode = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.timestampMs = longToNumber(reader.int64());
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.durationMs = longToNumber(reader.int64());
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.speakerIds.push(reader.string());
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.errorMessage = reader.string();
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.errorCode = reader.int32();
          continue;
        }
        case 13: {
          if (tag !== 104) {
            break;
          }

          message.segmentIndex = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): STTOutput {
    return {
      text: isSet(object.text) ? globalThis.String(object.text) : "",
      language: isSet(object.language) ? sTTLanguageFromJSON(object.language) : 0,
      confidence: isSet(object.confidence) ? globalThis.Number(object.confidence) : 0,
      words: globalThis.Array.isArray(object?.words) ? object.words.map((e: any) => WordTimestamp.fromJSON(e)) : [],
      alternatives: globalThis.Array.isArray(object?.alternatives)
        ? object.alternatives.map((e: any) => TranscriptionAlternative.fromJSON(e))
        : [],
      metadata: isSet(object.metadata) ? TranscriptionMetadata.fromJSON(object.metadata) : undefined,
      languageCode: isSet(object.languageCode)
        ? globalThis.String(object.languageCode)
        : isSet(object.language_code)
        ? globalThis.String(object.language_code)
        : undefined,
      timestampMs: isSet(object.timestampMs)
        ? globalThis.Number(object.timestampMs)
        : isSet(object.timestamp_ms)
        ? globalThis.Number(object.timestamp_ms)
        : 0,
      durationMs: isSet(object.durationMs)
        ? globalThis.Number(object.durationMs)
        : isSet(object.duration_ms)
        ? globalThis.Number(object.duration_ms)
        : 0,
      speakerIds: globalThis.Array.isArray(object?.speakerIds)
        ? object.speakerIds.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.speaker_ids)
        ? object.speaker_ids.map((e: any) => globalThis.String(e))
        : [],
      errorMessage: isSet(object.errorMessage)
        ? globalThis.String(object.errorMessage)
        : isSet(object.error_message)
        ? globalThis.String(object.error_message)
        : undefined,
      errorCode: isSet(object.errorCode)
        ? globalThis.Number(object.errorCode)
        : isSet(object.error_code)
        ? globalThis.Number(object.error_code)
        : 0,
      segmentIndex: isSet(object.segmentIndex)
        ? globalThis.Number(object.segmentIndex)
        : isSet(object.segment_index)
        ? globalThis.Number(object.segment_index)
        : 0,
    };
  },

  toJSON(message: STTOutput): unknown {
    const obj: any = {};
    if (message.text !== "") {
      obj.text = message.text;
    }
    if (message.language !== 0) {
      obj.language = sTTLanguageToJSON(message.language);
    }
    if (message.confidence !== 0) {
      obj.confidence = message.confidence;
    }
    if (message.words?.length) {
      obj.words = message.words.map((e) => WordTimestamp.toJSON(e));
    }
    if (message.alternatives?.length) {
      obj.alternatives = message.alternatives.map((e) => TranscriptionAlternative.toJSON(e));
    }
    if (message.metadata !== undefined) {
      obj.metadata = TranscriptionMetadata.toJSON(message.metadata);
    }
    if (message.languageCode !== undefined) {
      obj.languageCode = message.languageCode;
    }
    if (message.timestampMs !== 0) {
      obj.timestampMs = Math.round(message.timestampMs);
    }
    if (message.durationMs !== 0) {
      obj.durationMs = Math.round(message.durationMs);
    }
    if (message.speakerIds?.length) {
      obj.speakerIds = message.speakerIds;
    }
    if (message.errorMessage !== undefined) {
      obj.errorMessage = message.errorMessage;
    }
    if (message.errorCode !== 0) {
      obj.errorCode = Math.round(message.errorCode);
    }
    if (message.segmentIndex !== 0) {
      obj.segmentIndex = Math.round(message.segmentIndex);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<STTOutput>, I>>(base?: I): STTOutput {
    return STTOutput.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<STTOutput>, I>>(object: I): STTOutput {
    const message = createBaseSTTOutput();
    message.text = object.text ?? "";
    message.language = object.language ?? 0;
    message.confidence = object.confidence ?? 0;
    message.words = object.words?.map((e) => WordTimestamp.fromPartial(e)) || [];
    message.alternatives = object.alternatives?.map((e) => TranscriptionAlternative.fromPartial(e)) || [];
    message.metadata = (object.metadata !== undefined && object.metadata !== null)
      ? TranscriptionMetadata.fromPartial(object.metadata)
      : undefined;
    message.languageCode = object.languageCode ?? undefined;
    message.timestampMs = object.timestampMs ?? 0;
    message.durationMs = object.durationMs ?? 0;
    message.speakerIds = object.speakerIds?.map((e) => e) || [];
    message.errorMessage = object.errorMessage ?? undefined;
    message.errorCode = object.errorCode ?? 0;
    message.segmentIndex = object.segmentIndex ?? 0;
    return message;
  },
};

function createBaseSTTPartialResult(): STTPartialResult {
  return {
    text: "",
    isFinal: false,
    stability: 0,
    confidence: 0,
    language: 0,
    timestampMs: 0,
    alternatives: [],
    languageCode: undefined,
    requestId: "",
    segmentIndex: 0,
    audioStartMs: 0,
    audioEndMs: 0,
    finalOutput: undefined,
  };
}

export const STTPartialResult: MessageFns<STTPartialResult> = {
  encode(message: STTPartialResult, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.text !== "") {
      writer.uint32(10).string(message.text);
    }
    if (message.isFinal !== false) {
      writer.uint32(16).bool(message.isFinal);
    }
    if (message.stability !== 0) {
      writer.uint32(29).float(message.stability);
    }
    if (message.confidence !== 0) {
      writer.uint32(37).float(message.confidence);
    }
    if (message.language !== 0) {
      writer.uint32(40).int32(message.language);
    }
    if (message.timestampMs !== 0) {
      writer.uint32(48).int64(message.timestampMs);
    }
    for (const v of message.alternatives) {
      TranscriptionAlternative.encode(v!, writer.uint32(58).fork()).join();
    }
    if (message.languageCode !== undefined) {
      writer.uint32(66).string(message.languageCode);
    }
    if (message.requestId !== "") {
      writer.uint32(74).string(message.requestId);
    }
    if (message.segmentIndex !== 0) {
      writer.uint32(80).int32(message.segmentIndex);
    }
    if (message.audioStartMs !== 0) {
      writer.uint32(88).int64(message.audioStartMs);
    }
    if (message.audioEndMs !== 0) {
      writer.uint32(96).int64(message.audioEndMs);
    }
    if (message.finalOutput !== undefined) {
      STTOutput.encode(message.finalOutput, writer.uint32(106).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): STTPartialResult {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSTTPartialResult();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.text = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.isFinal = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 29) {
            break;
          }

          message.stability = reader.float();
          continue;
        }
        case 4: {
          if (tag !== 37) {
            break;
          }

          message.confidence = reader.float();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.language = reader.int32() as any;
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.timestampMs = longToNumber(reader.int64());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.alternatives.push(TranscriptionAlternative.decode(reader, reader.uint32()));
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.languageCode = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.segmentIndex = reader.int32();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.audioStartMs = longToNumber(reader.int64());
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.audioEndMs = longToNumber(reader.int64());
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.finalOutput = STTOutput.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): STTPartialResult {
    return {
      text: isSet(object.text) ? globalThis.String(object.text) : "",
      isFinal: isSet(object.isFinal)
        ? globalThis.Boolean(object.isFinal)
        : isSet(object.is_final)
        ? globalThis.Boolean(object.is_final)
        : false,
      stability: isSet(object.stability) ? globalThis.Number(object.stability) : 0,
      confidence: isSet(object.confidence) ? globalThis.Number(object.confidence) : 0,
      language: isSet(object.language) ? sTTLanguageFromJSON(object.language) : 0,
      timestampMs: isSet(object.timestampMs)
        ? globalThis.Number(object.timestampMs)
        : isSet(object.timestamp_ms)
        ? globalThis.Number(object.timestamp_ms)
        : 0,
      alternatives: globalThis.Array.isArray(object?.alternatives)
        ? object.alternatives.map((e: any) => TranscriptionAlternative.fromJSON(e))
        : [],
      languageCode: isSet(object.languageCode)
        ? globalThis.String(object.languageCode)
        : isSet(object.language_code)
        ? globalThis.String(object.language_code)
        : undefined,
      requestId: isSet(object.requestId)
        ? globalThis.String(object.requestId)
        : isSet(object.request_id)
        ? globalThis.String(object.request_id)
        : "",
      segmentIndex: isSet(object.segmentIndex)
        ? globalThis.Number(object.segmentIndex)
        : isSet(object.segment_index)
        ? globalThis.Number(object.segment_index)
        : 0,
      audioStartMs: isSet(object.audioStartMs)
        ? globalThis.Number(object.audioStartMs)
        : isSet(object.audio_start_ms)
        ? globalThis.Number(object.audio_start_ms)
        : 0,
      audioEndMs: isSet(object.audioEndMs)
        ? globalThis.Number(object.audioEndMs)
        : isSet(object.audio_end_ms)
        ? globalThis.Number(object.audio_end_ms)
        : 0,
      finalOutput: isSet(object.finalOutput)
        ? STTOutput.fromJSON(object.finalOutput)
        : isSet(object.final_output)
        ? STTOutput.fromJSON(object.final_output)
        : undefined,
    };
  },

  toJSON(message: STTPartialResult): unknown {
    const obj: any = {};
    if (message.text !== "") {
      obj.text = message.text;
    }
    if (message.isFinal !== false) {
      obj.isFinal = message.isFinal;
    }
    if (message.stability !== 0) {
      obj.stability = message.stability;
    }
    if (message.confidence !== 0) {
      obj.confidence = message.confidence;
    }
    if (message.language !== 0) {
      obj.language = sTTLanguageToJSON(message.language);
    }
    if (message.timestampMs !== 0) {
      obj.timestampMs = Math.round(message.timestampMs);
    }
    if (message.alternatives?.length) {
      obj.alternatives = message.alternatives.map((e) => TranscriptionAlternative.toJSON(e));
    }
    if (message.languageCode !== undefined) {
      obj.languageCode = message.languageCode;
    }
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.segmentIndex !== 0) {
      obj.segmentIndex = Math.round(message.segmentIndex);
    }
    if (message.audioStartMs !== 0) {
      obj.audioStartMs = Math.round(message.audioStartMs);
    }
    if (message.audioEndMs !== 0) {
      obj.audioEndMs = Math.round(message.audioEndMs);
    }
    if (message.finalOutput !== undefined) {
      obj.finalOutput = STTOutput.toJSON(message.finalOutput);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<STTPartialResult>, I>>(base?: I): STTPartialResult {
    return STTPartialResult.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<STTPartialResult>, I>>(object: I): STTPartialResult {
    const message = createBaseSTTPartialResult();
    message.text = object.text ?? "";
    message.isFinal = object.isFinal ?? false;
    message.stability = object.stability ?? 0;
    message.confidence = object.confidence ?? 0;
    message.language = object.language ?? 0;
    message.timestampMs = object.timestampMs ?? 0;
    message.alternatives = object.alternatives?.map((e) => TranscriptionAlternative.fromPartial(e)) || [];
    message.languageCode = object.languageCode ?? undefined;
    message.requestId = object.requestId ?? "";
    message.segmentIndex = object.segmentIndex ?? 0;
    message.audioStartMs = object.audioStartMs ?? 0;
    message.audioEndMs = object.audioEndMs ?? 0;
    message.finalOutput = (object.finalOutput !== undefined && object.finalOutput !== null)
      ? STTOutput.fromPartial(object.finalOutput)
      : undefined;
    return message;
  },
};

function createBaseSTTStreamEvent(): STTStreamEvent {
  return {
    seq: 0,
    timestampUs: 0,
    requestId: "",
    kind: 0,
    partial: undefined,
    finalOutput: undefined,
    errorMessage: undefined,
    errorCode: 0,
  };
}

export const STTStreamEvent: MessageFns<STTStreamEvent> = {
  encode(message: STTStreamEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.seq !== 0) {
      writer.uint32(8).uint64(message.seq);
    }
    if (message.timestampUs !== 0) {
      writer.uint32(16).int64(message.timestampUs);
    }
    if (message.requestId !== "") {
      writer.uint32(26).string(message.requestId);
    }
    if (message.kind !== 0) {
      writer.uint32(32).int32(message.kind);
    }
    if (message.partial !== undefined) {
      STTPartialResult.encode(message.partial, writer.uint32(42).fork()).join();
    }
    if (message.finalOutput !== undefined) {
      STTOutput.encode(message.finalOutput, writer.uint32(50).fork()).join();
    }
    if (message.errorMessage !== undefined) {
      writer.uint32(58).string(message.errorMessage);
    }
    if (message.errorCode !== 0) {
      writer.uint32(64).int32(message.errorCode);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): STTStreamEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSTTStreamEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.seq = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.timestampUs = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.kind = reader.int32() as any;
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.partial = STTPartialResult.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.finalOutput = STTOutput.decode(reader, reader.uint32());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.errorMessage = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.errorCode = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): STTStreamEvent {
    return {
      seq: isSet(object.seq) ? globalThis.Number(object.seq) : 0,
      timestampUs: isSet(object.timestampUs)
        ? globalThis.Number(object.timestampUs)
        : isSet(object.timestamp_us)
        ? globalThis.Number(object.timestamp_us)
        : 0,
      requestId: isSet(object.requestId)
        ? globalThis.String(object.requestId)
        : isSet(object.request_id)
        ? globalThis.String(object.request_id)
        : "",
      kind: isSet(object.kind) ? sTTStreamEventKindFromJSON(object.kind) : 0,
      partial: isSet(object.partial) ? STTPartialResult.fromJSON(object.partial) : undefined,
      finalOutput: isSet(object.finalOutput)
        ? STTOutput.fromJSON(object.finalOutput)
        : isSet(object.final_output)
        ? STTOutput.fromJSON(object.final_output)
        : undefined,
      errorMessage: isSet(object.errorMessage)
        ? globalThis.String(object.errorMessage)
        : isSet(object.error_message)
        ? globalThis.String(object.error_message)
        : undefined,
      errorCode: isSet(object.errorCode)
        ? globalThis.Number(object.errorCode)
        : isSet(object.error_code)
        ? globalThis.Number(object.error_code)
        : 0,
    };
  },

  toJSON(message: STTStreamEvent): unknown {
    const obj: any = {};
    if (message.seq !== 0) {
      obj.seq = Math.round(message.seq);
    }
    if (message.timestampUs !== 0) {
      obj.timestampUs = Math.round(message.timestampUs);
    }
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.kind !== 0) {
      obj.kind = sTTStreamEventKindToJSON(message.kind);
    }
    if (message.partial !== undefined) {
      obj.partial = STTPartialResult.toJSON(message.partial);
    }
    if (message.finalOutput !== undefined) {
      obj.finalOutput = STTOutput.toJSON(message.finalOutput);
    }
    if (message.errorMessage !== undefined) {
      obj.errorMessage = message.errorMessage;
    }
    if (message.errorCode !== 0) {
      obj.errorCode = Math.round(message.errorCode);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<STTStreamEvent>, I>>(base?: I): STTStreamEvent {
    return STTStreamEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<STTStreamEvent>, I>>(object: I): STTStreamEvent {
    const message = createBaseSTTStreamEvent();
    message.seq = object.seq ?? 0;
    message.timestampUs = object.timestampUs ?? 0;
    message.requestId = object.requestId ?? "";
    message.kind = object.kind ?? 0;
    message.partial = (object.partial !== undefined && object.partial !== null)
      ? STTPartialResult.fromPartial(object.partial)
      : undefined;
    message.finalOutput = (object.finalOutput !== undefined && object.finalOutput !== null)
      ? STTOutput.fromPartial(object.finalOutput)
      : undefined;
    message.errorMessage = object.errorMessage ?? undefined;
    message.errorCode = object.errorCode ?? 0;
    return message;
  },
};

function createBaseSTTServiceState(): STTServiceState {
  return {
    isReady: false,
    currentModel: undefined,
    supportsStreaming: false,
    supportedLanguageCodes: [],
    errorMessage: undefined,
    errorCode: 0,
  };
}

export const STTServiceState: MessageFns<STTServiceState> = {
  encode(message: STTServiceState, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.isReady !== false) {
      writer.uint32(8).bool(message.isReady);
    }
    if (message.currentModel !== undefined) {
      writer.uint32(18).string(message.currentModel);
    }
    if (message.supportsStreaming !== false) {
      writer.uint32(24).bool(message.supportsStreaming);
    }
    for (const v of message.supportedLanguageCodes) {
      writer.uint32(34).string(v!);
    }
    if (message.errorMessage !== undefined) {
      writer.uint32(42).string(message.errorMessage);
    }
    if (message.errorCode !== 0) {
      writer.uint32(48).int32(message.errorCode);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): STTServiceState {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSTTServiceState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.isReady = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.currentModel = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.supportsStreaming = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.supportedLanguageCodes.push(reader.string());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.errorMessage = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.errorCode = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): STTServiceState {
    return {
      isReady: isSet(object.isReady)
        ? globalThis.Boolean(object.isReady)
        : isSet(object.is_ready)
        ? globalThis.Boolean(object.is_ready)
        : false,
      currentModel: isSet(object.currentModel)
        ? globalThis.String(object.currentModel)
        : isSet(object.current_model)
        ? globalThis.String(object.current_model)
        : undefined,
      supportsStreaming: isSet(object.supportsStreaming)
        ? globalThis.Boolean(object.supportsStreaming)
        : isSet(object.supports_streaming)
        ? globalThis.Boolean(object.supports_streaming)
        : false,
      supportedLanguageCodes: globalThis.Array.isArray(object?.supportedLanguageCodes)
        ? object.supportedLanguageCodes.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.supported_language_codes)
        ? object.supported_language_codes.map((e: any) => globalThis.String(e))
        : [],
      errorMessage: isSet(object.errorMessage)
        ? globalThis.String(object.errorMessage)
        : isSet(object.error_message)
        ? globalThis.String(object.error_message)
        : undefined,
      errorCode: isSet(object.errorCode)
        ? globalThis.Number(object.errorCode)
        : isSet(object.error_code)
        ? globalThis.Number(object.error_code)
        : 0,
    };
  },

  toJSON(message: STTServiceState): unknown {
    const obj: any = {};
    if (message.isReady !== false) {
      obj.isReady = message.isReady;
    }
    if (message.currentModel !== undefined) {
      obj.currentModel = message.currentModel;
    }
    if (message.supportsStreaming !== false) {
      obj.supportsStreaming = message.supportsStreaming;
    }
    if (message.supportedLanguageCodes?.length) {
      obj.supportedLanguageCodes = message.supportedLanguageCodes;
    }
    if (message.errorMessage !== undefined) {
      obj.errorMessage = message.errorMessage;
    }
    if (message.errorCode !== 0) {
      obj.errorCode = Math.round(message.errorCode);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<STTServiceState>, I>>(base?: I): STTServiceState {
    return STTServiceState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<STTServiceState>, I>>(object: I): STTServiceState {
    const message = createBaseSTTServiceState();
    message.isReady = object.isReady ?? false;
    message.currentModel = object.currentModel ?? undefined;
    message.supportsStreaming = object.supportsStreaming ?? false;
    message.supportedLanguageCodes = object.supportedLanguageCodes?.map((e) => e) || [];
    message.errorMessage = object.errorMessage ?? undefined;
    message.errorCode = object.errorCode ?? 0;
    return message;
  },
};

function createBaseSTTLanguageDetectionResult(): STTLanguageDetectionResult {
  return { language: 0, languageCode: undefined, confidence: 0, alternatives: [] };
}

export const STTLanguageDetectionResult: MessageFns<STTLanguageDetectionResult> = {
  encode(message: STTLanguageDetectionResult, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.language !== 0) {
      writer.uint32(8).int32(message.language);
    }
    if (message.languageCode !== undefined) {
      writer.uint32(18).string(message.languageCode);
    }
    if (message.confidence !== 0) {
      writer.uint32(29).float(message.confidence);
    }
    for (const v of message.alternatives) {
      writer.uint32(34).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): STTLanguageDetectionResult {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSTTLanguageDetectionResult();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.language = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.languageCode = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 29) {
            break;
          }

          message.confidence = reader.float();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.alternatives.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): STTLanguageDetectionResult {
    return {
      language: isSet(object.language) ? sTTLanguageFromJSON(object.language) : 0,
      languageCode: isSet(object.languageCode)
        ? globalThis.String(object.languageCode)
        : isSet(object.language_code)
        ? globalThis.String(object.language_code)
        : undefined,
      confidence: isSet(object.confidence) ? globalThis.Number(object.confidence) : 0,
      alternatives: globalThis.Array.isArray(object?.alternatives)
        ? object.alternatives.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: STTLanguageDetectionResult): unknown {
    const obj: any = {};
    if (message.language !== 0) {
      obj.language = sTTLanguageToJSON(message.language);
    }
    if (message.languageCode !== undefined) {
      obj.languageCode = message.languageCode;
    }
    if (message.confidence !== 0) {
      obj.confidence = message.confidence;
    }
    if (message.alternatives?.length) {
      obj.alternatives = message.alternatives;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<STTLanguageDetectionResult>, I>>(base?: I): STTLanguageDetectionResult {
    return STTLanguageDetectionResult.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<STTLanguageDetectionResult>, I>>(object: I): STTLanguageDetectionResult {
    const message = createBaseSTTLanguageDetectionResult();
    message.language = object.language ?? 0;
    message.languageCode = object.languageCode ?? undefined;
    message.confidence = object.confidence ?? 0;
    message.alternatives = object.alternatives?.map((e) => e) || [];
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  const bin = globalThis.atob(b64);
  const arr = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; ++i) {
    arr[i] = bin.charCodeAt(i);
  }
  return arr;
}

function base64FromBytes(arr: Uint8Array): string {
  const bin: string[] = [];
  arr.forEach((byte) => {
    bin.push(globalThis.String.fromCharCode(byte));
  });
  return globalThis.btoa(bin.join(""));
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
