// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.35.1
// source: vad_options.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { InferenceFramework, inferenceFrameworkFromJSON, inferenceFrameworkToJSON } from "./model_types";

export const protobufPackage = "runanywhere.v1";

/**
 * ---------------------------------------------------------------------------
 * Speech-activity lifecycle kind.
 * Sources pre-IDL:
 *   Swift  VADTypes.swift:235               (started, ended)
 *   Kotlin VADTypes.kt:171                  (STARTED, ENDED)
 *   Dart   runanywhere_vad.dart:28          (started, ended)
 *   RN     VADTypes.ts:43                   ('started' | 'ended')
 *   Web    VADTypes.ts:8                    (Started, Ended, Ongoing)   ← only SDK with ONGOING
 *   C ABI  rac_vad_types.h:107              (RAC_SPEECH_STARTED, RAC_SPEECH_ENDED, RAC_SPEECH_ONGOING)
 * Canonical union: STARTED, ENDED, ONGOING.
 * ---------------------------------------------------------------------------
 */
export enum SpeechActivityKind {
  /** SPEECH_ACTIVITY_KIND_UNSPECIFIED - Reserved (proto3 default) */
  SPEECH_ACTIVITY_KIND_UNSPECIFIED = 0,
  SPEECH_ACTIVITY_KIND_SPEECH_STARTED = 1,
  SPEECH_ACTIVITY_KIND_SPEECH_ENDED = 2,
  SPEECH_ACTIVITY_KIND_ONGOING = 3,
  UNRECOGNIZED = -1,
}

export function speechActivityKindFromJSON(object: any): SpeechActivityKind {
  switch (object) {
    case 0:
    case "SPEECH_ACTIVITY_KIND_UNSPECIFIED":
      return SpeechActivityKind.SPEECH_ACTIVITY_KIND_UNSPECIFIED;
    case 1:
    case "SPEECH_ACTIVITY_KIND_SPEECH_STARTED":
      return SpeechActivityKind.SPEECH_ACTIVITY_KIND_SPEECH_STARTED;
    case 2:
    case "SPEECH_ACTIVITY_KIND_SPEECH_ENDED":
      return SpeechActivityKind.SPEECH_ACTIVITY_KIND_SPEECH_ENDED;
    case 3:
    case "SPEECH_ACTIVITY_KIND_ONGOING":
      return SpeechActivityKind.SPEECH_ACTIVITY_KIND_ONGOING;
    case -1:
    case "UNRECOGNIZED":
    default:
      return SpeechActivityKind.UNRECOGNIZED;
  }
}

export function speechActivityKindToJSON(object: SpeechActivityKind): string {
  switch (object) {
    case SpeechActivityKind.SPEECH_ACTIVITY_KIND_UNSPECIFIED:
      return "SPEECH_ACTIVITY_KIND_UNSPECIFIED";
    case SpeechActivityKind.SPEECH_ACTIVITY_KIND_SPEECH_STARTED:
      return "SPEECH_ACTIVITY_KIND_SPEECH_STARTED";
    case SpeechActivityKind.SPEECH_ACTIVITY_KIND_SPEECH_ENDED:
      return "SPEECH_ACTIVITY_KIND_SPEECH_ENDED";
    case SpeechActivityKind.SPEECH_ACTIVITY_KIND_ONGOING:
      return "SPEECH_ACTIVITY_KIND_ONGOING";
    case SpeechActivityKind.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum VADAudioEncoding {
  VAD_AUDIO_ENCODING_UNSPECIFIED = 0,
  VAD_AUDIO_ENCODING_PCM_F32_LE = 1,
  VAD_AUDIO_ENCODING_PCM_S16_LE = 2,
  UNRECOGNIZED = -1,
}

export function vADAudioEncodingFromJSON(object: any): VADAudioEncoding {
  switch (object) {
    case 0:
    case "VAD_AUDIO_ENCODING_UNSPECIFIED":
      return VADAudioEncoding.VAD_AUDIO_ENCODING_UNSPECIFIED;
    case 1:
    case "VAD_AUDIO_ENCODING_PCM_F32_LE":
      return VADAudioEncoding.VAD_AUDIO_ENCODING_PCM_F32_LE;
    case 2:
    case "VAD_AUDIO_ENCODING_PCM_S16_LE":
      return VADAudioEncoding.VAD_AUDIO_ENCODING_PCM_S16_LE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return VADAudioEncoding.UNRECOGNIZED;
  }
}

export function vADAudioEncodingToJSON(object: VADAudioEncoding): string {
  switch (object) {
    case VADAudioEncoding.VAD_AUDIO_ENCODING_UNSPECIFIED:
      return "VAD_AUDIO_ENCODING_UNSPECIFIED";
    case VADAudioEncoding.VAD_AUDIO_ENCODING_PCM_F32_LE:
      return "VAD_AUDIO_ENCODING_PCM_F32_LE";
    case VADAudioEncoding.VAD_AUDIO_ENCODING_PCM_S16_LE:
      return "VAD_AUDIO_ENCODING_PCM_S16_LE";
    case VADAudioEncoding.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum VADStreamEventKind {
  VAD_STREAM_EVENT_KIND_UNSPECIFIED = 0,
  VAD_STREAM_EVENT_KIND_STARTED = 1,
  VAD_STREAM_EVENT_KIND_FRAME = 2,
  VAD_STREAM_EVENT_KIND_SPEECH_ACTIVITY = 3,
  VAD_STREAM_EVENT_KIND_STATISTICS = 4,
  VAD_STREAM_EVENT_KIND_STOPPED = 5,
  VAD_STREAM_EVENT_KIND_ERROR = 6,
  /**
   * VAD_STREAM_EVENT_KIND_BARGE_IN - Pipeline-level barge-in signal previously carried by the
   * deleted VADEventType enum. Emitted when the VAD detects speech that
   * interrupts active assistant playback; downstream pipeline typically
   * routes this through InterruptedEvent/InterruptReason as well.
   */
  VAD_STREAM_EVENT_KIND_BARGE_IN = 7,
  UNRECOGNIZED = -1,
}

export function vADStreamEventKindFromJSON(object: any): VADStreamEventKind {
  switch (object) {
    case 0:
    case "VAD_STREAM_EVENT_KIND_UNSPECIFIED":
      return VADStreamEventKind.VAD_STREAM_EVENT_KIND_UNSPECIFIED;
    case 1:
    case "VAD_STREAM_EVENT_KIND_STARTED":
      return VADStreamEventKind.VAD_STREAM_EVENT_KIND_STARTED;
    case 2:
    case "VAD_STREAM_EVENT_KIND_FRAME":
      return VADStreamEventKind.VAD_STREAM_EVENT_KIND_FRAME;
    case 3:
    case "VAD_STREAM_EVENT_KIND_SPEECH_ACTIVITY":
      return VADStreamEventKind.VAD_STREAM_EVENT_KIND_SPEECH_ACTIVITY;
    case 4:
    case "VAD_STREAM_EVENT_KIND_STATISTICS":
      return VADStreamEventKind.VAD_STREAM_EVENT_KIND_STATISTICS;
    case 5:
    case "VAD_STREAM_EVENT_KIND_STOPPED":
      return VADStreamEventKind.VAD_STREAM_EVENT_KIND_STOPPED;
    case 6:
    case "VAD_STREAM_EVENT_KIND_ERROR":
      return VADStreamEventKind.VAD_STREAM_EVENT_KIND_ERROR;
    case 7:
    case "VAD_STREAM_EVENT_KIND_BARGE_IN":
      return VADStreamEventKind.VAD_STREAM_EVENT_KIND_BARGE_IN;
    case -1:
    case "UNRECOGNIZED":
    default:
      return VADStreamEventKind.UNRECOGNIZED;
  }
}

export function vADStreamEventKindToJSON(object: VADStreamEventKind): string {
  switch (object) {
    case VADStreamEventKind.VAD_STREAM_EVENT_KIND_UNSPECIFIED:
      return "VAD_STREAM_EVENT_KIND_UNSPECIFIED";
    case VADStreamEventKind.VAD_STREAM_EVENT_KIND_STARTED:
      return "VAD_STREAM_EVENT_KIND_STARTED";
    case VADStreamEventKind.VAD_STREAM_EVENT_KIND_FRAME:
      return "VAD_STREAM_EVENT_KIND_FRAME";
    case VADStreamEventKind.VAD_STREAM_EVENT_KIND_SPEECH_ACTIVITY:
      return "VAD_STREAM_EVENT_KIND_SPEECH_ACTIVITY";
    case VADStreamEventKind.VAD_STREAM_EVENT_KIND_STATISTICS:
      return "VAD_STREAM_EVENT_KIND_STATISTICS";
    case VADStreamEventKind.VAD_STREAM_EVENT_KIND_STOPPED:
      return "VAD_STREAM_EVENT_KIND_STOPPED";
    case VADStreamEventKind.VAD_STREAM_EVENT_KIND_ERROR:
      return "VAD_STREAM_EVENT_KIND_ERROR";
    case VADStreamEventKind.VAD_STREAM_EVENT_KIND_BARGE_IN:
      return "VAD_STREAM_EVENT_KIND_BARGE_IN";
    case VADStreamEventKind.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/**
 * ---------------------------------------------------------------------------
 * Compile-time / load-time configuration for a VAD instance.
 * Sources pre-IDL:
 *   Swift  VADTypes.swift:15                (energyThreshold, sampleRate, frameLength,
 *                                            enableAutoCalibration, calibrationMultiplier)
 *   Kotlin VADTypes.kt:26                   (same five fields, defaults match Swift)
 *   Dart   vad_configuration.dart:5         (same five fields)
 *   RN     VADTypes.ts:12                   (sampleRate, frameLength, energyThreshold;
 *                                            no calibration fields)
 *   Web    VADTypes.ts —                    (no VADConfiguration; per-backend in WebSDK)
 *   C ABI  rac_vad_types.h:63 (rac_vad_config_t)
 *                                           (model_id, preferred_framework, energy_threshold,
 *                                            sample_rate, frame_length, enable_auto_calibration,
 *                                            calibration_multiplier)
 *
 * `frame_length_ms` is the canonical wire field — Swift/Kotlin/Dart/C use
 * seconds (float), but ms is more interoperable across protobuf consumers.
 * Generators must convert when binding to per-platform types.
 * ---------------------------------------------------------------------------
 */
export interface VADConfiguration {
  /**
   * Optional model id; empty when using the built-in energy VAD.
   * C ABI: model_id (rac_vad_config_t::model_id, may be NULL).
   */
  modelId: string;
  /** PCM sample rate in Hz. Default 16000 (RAC_VAD_DEFAULT_SAMPLE_RATE). */
  sampleRate: number;
  /**
   * Frame length in milliseconds. Default 100 (Swift/Kotlin/Dart store
   * 0.1 seconds; we canonicalize to ms on the wire).
   */
  frameLengthMs: number;
  /**
   * Energy threshold in [0.0, 1.0] for voice detection.
   * Recommended range 0.01–0.05; default 0.015 across SDKs.
   */
  threshold: number;
  /**
   * When true, the VAD performs ambient-noise calibration and uses the
   * result as a multiplier on the threshold (see calibration_multiplier
   * in the C ABI). Defaults to false.
   */
  enableAutoCalibration: boolean;
  /**
   * Calibration multiplier (threshold = ambient noise * multiplier).
   * Present in Swift/Kotlin/Dart configs and rac_vad_config_t.
   */
  calibrationMultiplier: number;
  /** Preferred framework for VAD. Absent = auto. */
  preferredFramework?:
    | InferenceFramework
    | undefined;
  /** Optional model path for backend-specific VADs (e.g. Silero ONNX). */
  modelPath?:
    | string
    | undefined;
  /**
   * Window size in samples for frame-based neural VAD backends. 0 =
   * backend/default.
   */
  windowSizeSamples: number;
  /**
   * Maximum continuous speech segment duration in milliseconds. 0 =
   * backend/default.
   */
  maxSpeechDurationMs: number;
}

/**
 * ---------------------------------------------------------------------------
 * Runtime / per-call options applied to a VAD pass.
 * Sources pre-IDL:
 *   Swift  none — Swift uses raw arguments to detectSpeech().
 *   Kotlin none — same as Swift.
 *   Dart   runanywhere_vad.dart:99          (`detectSpeech` takes raw Float32List)
 *   RN     VADTypes.ts —                    (no per-call options struct)
 *   Web    VADTypes.ts —                    (no per-call options struct)
 *   C ABI  rac_vad_types.h:123 (rac_vad_input_t)
 *                                           (audio_samples, num_samples,
 *                                            energy_threshold_override)
 *
 * We canonicalize on the energy_threshold_override + the speech-duration
 * gates that already appear as constants in rac_vad_types.h:50-51:
 *   RAC_VAD_MIN_SPEECH_DURATION_MS  = 100
 *   RAC_VAD_MIN_SILENCE_DURATION_MS = 300
 * Surfacing them as fields lets callers tune debouncing without a rebuild.
 * ---------------------------------------------------------------------------
 */
export interface VADOptions {
  /**
   * Per-call energy threshold override. Use 0 (default) to keep the
   * configured threshold. Mirrors rac_vad_input_t::energy_threshold_override
   * (which uses -1 as the sentinel; on the wire we use 0 for proto3
   * default semantics — generators emit -1 when this is unset).
   */
  threshold: number;
  /**
   * Minimum continuous speech duration (ms) before SPEECH_STARTED fires.
   * Default 100 (RAC_VAD_MIN_SPEECH_DURATION_MS).
   */
  minSpeechDurationMs: number;
  /**
   * Minimum continuous silence duration (ms) before SPEECH_ENDED fires.
   * Default 300 (RAC_VAD_MIN_SILENCE_DURATION_MS).
   */
  minSilenceDurationMs: number;
  /**
   * Maximum continuous speech duration (ms) before forcing a segment split.
   * 0 = backend/default.
   */
  maxSpeechDurationMs: number;
  /** Whether to include VADStatistics in stream events when available. */
  includeStatistics: boolean;
}

export interface VADAudioSource {
  audioData?: Uint8Array | undefined;
  adapterHandle?: string | undefined;
  encoding: VADAudioEncoding;
  sampleRate: number;
  channels: number;
  frameOffsetMs: number;
}

export interface VADProcessRequest {
  requestId: string;
  audio?: VADAudioSource | undefined;
  options?: VADOptions | undefined;
  metadata: { [key: string]: string };
}

export interface VADProcessRequest_MetadataEntry {
  key: string;
  value: string;
}

/**
 * ---------------------------------------------------------------------------
 * Result of a single VAD pass over a chunk of PCM audio.
 * Sources pre-IDL:
 *   Swift  VADTypes.swift —                 (no struct; bool returned from detectSpeech())
 *   Kotlin VADTypes.kt:152                  (isSpeech, confidence, energyLevel,
 *                                            statistics, timestamp)
 *   Dart   dart_bridge_vad.dart:290         (isSpeech, energy, speechProbability)
 *   RN     VADTypes.ts:26                   (isSpeech, probability, startTime, endTime)
 *   Web    VADTypes.ts —                    (no VADResult; only SpeechSegment)
 *   C ABI  rac_vad_types.h:151 (rac_vad_output_t)
 *                                           (is_speech_detected, energy_level, timestamp_ms)
 *
 * Drift notes:
 *   - Kotlin's `confidence` and Dart's `speechProbability` and RN's
 *     `probability` collapse onto the canonical `confidence` field.
 *   - Kotlin/RN/C all carry timing — we encode duration_ms (length of the
 *     analyzed frame). Wall-clock timestamps belong on the carrying envelope
 *     (e.g. VoiceEvent.timestamp_us in voice_events.proto).
 * ---------------------------------------------------------------------------
 */
export interface VADResult {
  /**
   * Whether speech was detected in this frame.
   * Mirrors rac_vad_output_t::is_speech_detected.
   */
  isSpeech: boolean;
  /** Confidence / probability in [0.0, 1.0]. Backend-dependent. */
  confidence: number;
  /**
   * RMS energy level of the analyzed frame.
   * Mirrors rac_vad_output_t::energy_level.
   */
  energy: number;
  /** Length of the analyzed frame in milliseconds. */
  durationMs: number;
  /** Wall-clock timestamp for this frame/result, in milliseconds since epoch. */
  timestampMs: number;
  /** Optional detected segment start/end times, in milliseconds. 0 = unset. */
  startTimeMs: number;
  endTimeMs: number;
  /** Optional statistics snapshot and result-envelope error details. */
  statistics?: VADStatistics | undefined;
  errorMessage?: string | undefined;
  errorCode: number;
}

/**
 * ---------------------------------------------------------------------------
 * Internal VAD statistics, exposed for debugging / waveform UIs.
 * Sources pre-IDL:
 *   Swift  VADTypes.swift:174               (current, threshold, ambient,
 *                                            recentAvg, recentMax)
 *   Kotlin VADTypes.kt:123                  (same five fields)
 *   Dart   none — Dart bridge does not surface statistics yet.
 *   RN     VADTypes.ts —                    (none)
 *   Web    VADTypes.ts —                    (none)
 *   C ABI  rac_vad_types.h:194 (rac_vad_statistics_t)
 *                                           (current_threshold, ambient_noise_level,
 *                                            total_speech_segments, total_speech_duration_ms,
 *                                            average_energy, peak_energy)
 *
 * We canonicalize on the Swift/Kotlin shape because it is the most widely
 * used. The richer C ABI fields (segment counts, totals) belong on a future
 * VADAnalytics message and are intentionally NOT included here.
 * ---------------------------------------------------------------------------
 */
export interface VADStatistics {
  /** Current instantaneous energy level. (Swift/Kotlin: `current`) */
  currentEnergy: number;
  /**
   * Energy threshold currently in use. (Swift/Kotlin: `threshold`;
   * C ABI: rac_vad_statistics_t::current_threshold)
   */
  currentThreshold: number;
  /**
   * Ambient noise level captured by calibration. (Swift/Kotlin: `ambient`;
   * C ABI: rac_vad_statistics_t::ambient_noise_level)
   */
  ambientLevel: number;
  /** Recent moving-window average energy. (Swift/Kotlin: `recentAvg`) */
  recentAvg: number;
  /** Recent moving-window peak energy. (Swift/Kotlin: `recentMax`) */
  recentMax: number;
  /**
   * Richer service-level counters from rac_vad_statistics_t. Zero = unset
   * for energy-only implementations.
   */
  totalSpeechSegments: number;
  totalSpeechDurationMs: number;
  averageEnergy: number;
  peakEnergy: number;
}

/**
 * ---------------------------------------------------------------------------
 * Activity transition emitted by the VAD as it watches a stream.
 * Sources pre-IDL:
 *   Swift  VADTypes.swift:235               (SpeechActivityEvent enum: started/ended)
 *   Kotlin VADTypes.kt:171                  (SpeechActivityEvent enum: STARTED/ENDED)
 *   Dart   runanywhere_vad.dart:28          (SpeechActivityEvent enum: started/ended)
 *   RN     VADTypes.ts:43                   ('started' | 'ended' string union)
 *   Web    VADTypes.ts:8                    (SpeechActivity enum: Started/Ended/Ongoing)
 *   C ABI  rac_vad_types.h:107 (rac_speech_activity_t)
 *                                           (RAC_SPEECH_STARTED/ENDED/ONGOING)
 *
 * Distinct from voice_events.proto's `VADEvent`, which carries the broader
 * pipeline-level taxonomy (BARGE_IN, END_OF_UTTERANCE, etc) via
 * `VADStreamEventKind`. `SpeechActivityEvent` here is the narrow
 * component-level transition.
 * ---------------------------------------------------------------------------
 */
export interface SpeechActivityEvent {
  /** Which transition happened. */
  eventType: SpeechActivityKind;
  /**
   * Wall-clock time of the transition, in milliseconds since epoch.
   * Aligns with rac_vad_output_t::timestamp_ms.
   */
  timestampMs: number;
  /**
   * Optional duration of the speech / silence that triggered this event,
   * in milliseconds. Set on SPEECH_ENDED to communicate the just-finished
   * utterance length; left zero on SPEECH_STARTED.
   */
  durationMs: number;
  confidence: number;
  result?: VADResult | undefined;
  segmentId?: string | undefined;
}

export interface VADStreamEvent {
  seq: number;
  timestampUs: number;
  requestId: string;
  kind: VADStreamEventKind;
  result?: VADResult | undefined;
  activity?: SpeechActivityEvent | undefined;
  statistics?: VADStatistics | undefined;
  errorMessage?: string | undefined;
  errorCode: number;
}

export interface VADServiceState {
  isReady: boolean;
  isSpeechActive: boolean;
  energyThreshold: number;
  sampleRate: number;
  frameLengthMs: number;
  currentModel?: string | undefined;
  errorMessage?: string | undefined;
  errorCode: number;
}

function createBaseVADConfiguration(): VADConfiguration {
  return {
    modelId: "",
    sampleRate: 0,
    frameLengthMs: 0,
    threshold: 0,
    enableAutoCalibration: false,
    calibrationMultiplier: 0,
    preferredFramework: undefined,
    modelPath: undefined,
    windowSizeSamples: 0,
    maxSpeechDurationMs: 0,
  };
}

export const VADConfiguration: MessageFns<VADConfiguration> = {
  encode(message: VADConfiguration, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.modelId !== "") {
      writer.uint32(10).string(message.modelId);
    }
    if (message.sampleRate !== 0) {
      writer.uint32(16).int32(message.sampleRate);
    }
    if (message.frameLengthMs !== 0) {
      writer.uint32(24).int32(message.frameLengthMs);
    }
    if (message.threshold !== 0) {
      writer.uint32(37).float(message.threshold);
    }
    if (message.enableAutoCalibration !== false) {
      writer.uint32(40).bool(message.enableAutoCalibration);
    }
    if (message.calibrationMultiplier !== 0) {
      writer.uint32(53).float(message.calibrationMultiplier);
    }
    if (message.preferredFramework !== undefined) {
      writer.uint32(56).int32(message.preferredFramework);
    }
    if (message.modelPath !== undefined) {
      writer.uint32(66).string(message.modelPath);
    }
    if (message.windowSizeSamples !== 0) {
      writer.uint32(72).int32(message.windowSizeSamples);
    }
    if (message.maxSpeechDurationMs !== 0) {
      writer.uint32(80).int32(message.maxSpeechDurationMs);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VADConfiguration {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVADConfiguration();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.modelId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.sampleRate = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.frameLengthMs = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 37) {
            break;
          }

          message.threshold = reader.float();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.enableAutoCalibration = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 53) {
            break;
          }

          message.calibrationMultiplier = reader.float();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.preferredFramework = reader.int32() as any;
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.modelPath = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.windowSizeSamples = reader.int32();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.maxSpeechDurationMs = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VADConfiguration {
    return {
      modelId: isSet(object.modelId)
        ? globalThis.String(object.modelId)
        : isSet(object.model_id)
        ? globalThis.String(object.model_id)
        : "",
      sampleRate: isSet(object.sampleRate)
        ? globalThis.Number(object.sampleRate)
        : isSet(object.sample_rate)
        ? globalThis.Number(object.sample_rate)
        : 0,
      frameLengthMs: isSet(object.frameLengthMs)
        ? globalThis.Number(object.frameLengthMs)
        : isSet(object.frame_length_ms)
        ? globalThis.Number(object.frame_length_ms)
        : 0,
      threshold: isSet(object.threshold) ? globalThis.Number(object.threshold) : 0,
      enableAutoCalibration: isSet(object.enableAutoCalibration)
        ? globalThis.Boolean(object.enableAutoCalibration)
        : isSet(object.enable_auto_calibration)
        ? globalThis.Boolean(object.enable_auto_calibration)
        : false,
      calibrationMultiplier: isSet(object.calibrationMultiplier)
        ? globalThis.Number(object.calibrationMultiplier)
        : isSet(object.calibration_multiplier)
        ? globalThis.Number(object.calibration_multiplier)
        : 0,
      preferredFramework: isSet(object.preferredFramework)
        ? inferenceFrameworkFromJSON(object.preferredFramework)
        : isSet(object.preferred_framework)
        ? inferenceFrameworkFromJSON(object.preferred_framework)
        : undefined,
      modelPath: isSet(object.modelPath)
        ? globalThis.String(object.modelPath)
        : isSet(object.model_path)
        ? globalThis.String(object.model_path)
        : undefined,
      windowSizeSamples: isSet(object.windowSizeSamples)
        ? globalThis.Number(object.windowSizeSamples)
        : isSet(object.window_size_samples)
        ? globalThis.Number(object.window_size_samples)
        : 0,
      maxSpeechDurationMs: isSet(object.maxSpeechDurationMs)
        ? globalThis.Number(object.maxSpeechDurationMs)
        : isSet(object.max_speech_duration_ms)
        ? globalThis.Number(object.max_speech_duration_ms)
        : 0,
    };
  },

  toJSON(message: VADConfiguration): unknown {
    const obj: any = {};
    if (message.modelId !== "") {
      obj.modelId = message.modelId;
    }
    if (message.sampleRate !== 0) {
      obj.sampleRate = Math.round(message.sampleRate);
    }
    if (message.frameLengthMs !== 0) {
      obj.frameLengthMs = Math.round(message.frameLengthMs);
    }
    if (message.threshold !== 0) {
      obj.threshold = message.threshold;
    }
    if (message.enableAutoCalibration !== false) {
      obj.enableAutoCalibration = message.enableAutoCalibration;
    }
    if (message.calibrationMultiplier !== 0) {
      obj.calibrationMultiplier = message.calibrationMultiplier;
    }
    if (message.preferredFramework !== undefined) {
      obj.preferredFramework = inferenceFrameworkToJSON(message.preferredFramework);
    }
    if (message.modelPath !== undefined) {
      obj.modelPath = message.modelPath;
    }
    if (message.windowSizeSamples !== 0) {
      obj.windowSizeSamples = Math.round(message.windowSizeSamples);
    }
    if (message.maxSpeechDurationMs !== 0) {
      obj.maxSpeechDurationMs = Math.round(message.maxSpeechDurationMs);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VADConfiguration>, I>>(base?: I): VADConfiguration {
    return VADConfiguration.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VADConfiguration>, I>>(object: I): VADConfiguration {
    const message = createBaseVADConfiguration();
    message.modelId = object.modelId ?? "";
    message.sampleRate = object.sampleRate ?? 0;
    message.frameLengthMs = object.frameLengthMs ?? 0;
    message.threshold = object.threshold ?? 0;
    message.enableAutoCalibration = object.enableAutoCalibration ?? false;
    message.calibrationMultiplier = object.calibrationMultiplier ?? 0;
    message.preferredFramework = object.preferredFramework ?? undefined;
    message.modelPath = object.modelPath ?? undefined;
    message.windowSizeSamples = object.windowSizeSamples ?? 0;
    message.maxSpeechDurationMs = object.maxSpeechDurationMs ?? 0;
    return message;
  },
};

function createBaseVADOptions(): VADOptions {
  return {
    threshold: 0,
    minSpeechDurationMs: 0,
    minSilenceDurationMs: 0,
    maxSpeechDurationMs: 0,
    includeStatistics: false,
  };
}

export const VADOptions: MessageFns<VADOptions> = {
  encode(message: VADOptions, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.threshold !== 0) {
      writer.uint32(13).float(message.threshold);
    }
    if (message.minSpeechDurationMs !== 0) {
      writer.uint32(16).int32(message.minSpeechDurationMs);
    }
    if (message.minSilenceDurationMs !== 0) {
      writer.uint32(24).int32(message.minSilenceDurationMs);
    }
    if (message.maxSpeechDurationMs !== 0) {
      writer.uint32(32).int32(message.maxSpeechDurationMs);
    }
    if (message.includeStatistics !== false) {
      writer.uint32(40).bool(message.includeStatistics);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VADOptions {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVADOptions();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 13) {
            break;
          }

          message.threshold = reader.float();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.minSpeechDurationMs = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.minSilenceDurationMs = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.maxSpeechDurationMs = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.includeStatistics = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VADOptions {
    return {
      threshold: isSet(object.threshold) ? globalThis.Number(object.threshold) : 0,
      minSpeechDurationMs: isSet(object.minSpeechDurationMs)
        ? globalThis.Number(object.minSpeechDurationMs)
        : isSet(object.min_speech_duration_ms)
        ? globalThis.Number(object.min_speech_duration_ms)
        : 0,
      minSilenceDurationMs: isSet(object.minSilenceDurationMs)
        ? globalThis.Number(object.minSilenceDurationMs)
        : isSet(object.min_silence_duration_ms)
        ? globalThis.Number(object.min_silence_duration_ms)
        : 0,
      maxSpeechDurationMs: isSet(object.maxSpeechDurationMs)
        ? globalThis.Number(object.maxSpeechDurationMs)
        : isSet(object.max_speech_duration_ms)
        ? globalThis.Number(object.max_speech_duration_ms)
        : 0,
      includeStatistics: isSet(object.includeStatistics)
        ? globalThis.Boolean(object.includeStatistics)
        : isSet(object.include_statistics)
        ? globalThis.Boolean(object.include_statistics)
        : false,
    };
  },

  toJSON(message: VADOptions): unknown {
    const obj: any = {};
    if (message.threshold !== 0) {
      obj.threshold = message.threshold;
    }
    if (message.minSpeechDurationMs !== 0) {
      obj.minSpeechDurationMs = Math.round(message.minSpeechDurationMs);
    }
    if (message.minSilenceDurationMs !== 0) {
      obj.minSilenceDurationMs = Math.round(message.minSilenceDurationMs);
    }
    if (message.maxSpeechDurationMs !== 0) {
      obj.maxSpeechDurationMs = Math.round(message.maxSpeechDurationMs);
    }
    if (message.includeStatistics !== false) {
      obj.includeStatistics = message.includeStatistics;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VADOptions>, I>>(base?: I): VADOptions {
    return VADOptions.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VADOptions>, I>>(object: I): VADOptions {
    const message = createBaseVADOptions();
    message.threshold = object.threshold ?? 0;
    message.minSpeechDurationMs = object.minSpeechDurationMs ?? 0;
    message.minSilenceDurationMs = object.minSilenceDurationMs ?? 0;
    message.maxSpeechDurationMs = object.maxSpeechDurationMs ?? 0;
    message.includeStatistics = object.includeStatistics ?? false;
    return message;
  },
};

function createBaseVADAudioSource(): VADAudioSource {
  return { audioData: undefined, adapterHandle: undefined, encoding: 0, sampleRate: 0, channels: 0, frameOffsetMs: 0 };
}

export const VADAudioSource: MessageFns<VADAudioSource> = {
  encode(message: VADAudioSource, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.audioData !== undefined) {
      writer.uint32(10).bytes(message.audioData);
    }
    if (message.adapterHandle !== undefined) {
      writer.uint32(18).string(message.adapterHandle);
    }
    if (message.encoding !== 0) {
      writer.uint32(24).int32(message.encoding);
    }
    if (message.sampleRate !== 0) {
      writer.uint32(32).int32(message.sampleRate);
    }
    if (message.channels !== 0) {
      writer.uint32(40).int32(message.channels);
    }
    if (message.frameOffsetMs !== 0) {
      writer.uint32(48).int64(message.frameOffsetMs);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VADAudioSource {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVADAudioSource();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.audioData = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.adapterHandle = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.encoding = reader.int32() as any;
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.sampleRate = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.channels = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.frameOffsetMs = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VADAudioSource {
    return {
      audioData: isSet(object.audioData)
        ? bytesFromBase64(object.audioData)
        : isSet(object.audio_data)
        ? bytesFromBase64(object.audio_data)
        : undefined,
      adapterHandle: isSet(object.adapterHandle)
        ? globalThis.String(object.adapterHandle)
        : isSet(object.adapter_handle)
        ? globalThis.String(object.adapter_handle)
        : undefined,
      encoding: isSet(object.encoding) ? vADAudioEncodingFromJSON(object.encoding) : 0,
      sampleRate: isSet(object.sampleRate)
        ? globalThis.Number(object.sampleRate)
        : isSet(object.sample_rate)
        ? globalThis.Number(object.sample_rate)
        : 0,
      channels: isSet(object.channels) ? globalThis.Number(object.channels) : 0,
      frameOffsetMs: isSet(object.frameOffsetMs)
        ? globalThis.Number(object.frameOffsetMs)
        : isSet(object.frame_offset_ms)
        ? globalThis.Number(object.frame_offset_ms)
        : 0,
    };
  },

  toJSON(message: VADAudioSource): unknown {
    const obj: any = {};
    if (message.audioData !== undefined) {
      obj.audioData = base64FromBytes(message.audioData);
    }
    if (message.adapterHandle !== undefined) {
      obj.adapterHandle = message.adapterHandle;
    }
    if (message.encoding !== 0) {
      obj.encoding = vADAudioEncodingToJSON(message.encoding);
    }
    if (message.sampleRate !== 0) {
      obj.sampleRate = Math.round(message.sampleRate);
    }
    if (message.channels !== 0) {
      obj.channels = Math.round(message.channels);
    }
    if (message.frameOffsetMs !== 0) {
      obj.frameOffsetMs = Math.round(message.frameOffsetMs);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VADAudioSource>, I>>(base?: I): VADAudioSource {
    return VADAudioSource.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VADAudioSource>, I>>(object: I): VADAudioSource {
    const message = createBaseVADAudioSource();
    message.audioData = object.audioData ?? undefined;
    message.adapterHandle = object.adapterHandle ?? undefined;
    message.encoding = object.encoding ?? 0;
    message.sampleRate = object.sampleRate ?? 0;
    message.channels = object.channels ?? 0;
    message.frameOffsetMs = object.frameOffsetMs ?? 0;
    return message;
  },
};

function createBaseVADProcessRequest(): VADProcessRequest {
  return { requestId: "", audio: undefined, options: undefined, metadata: {} };
}

export const VADProcessRequest: MessageFns<VADProcessRequest> = {
  encode(message: VADProcessRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.requestId !== "") {
      writer.uint32(10).string(message.requestId);
    }
    if (message.audio !== undefined) {
      VADAudioSource.encode(message.audio, writer.uint32(18).fork()).join();
    }
    if (message.options !== undefined) {
      VADOptions.encode(message.options, writer.uint32(26).fork()).join();
    }
    globalThis.Object.entries(message.metadata).forEach(([key, value]: [string, string]) => {
      VADProcessRequest_MetadataEntry.encode({ key: key as any, value }, writer.uint32(34).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VADProcessRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVADProcessRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.audio = VADAudioSource.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.options = VADOptions.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          const entry4 = VADProcessRequest_MetadataEntry.decode(reader, reader.uint32());
          if (entry4.value !== undefined) {
            message.metadata[entry4.key] = entry4.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VADProcessRequest {
    return {
      requestId: isSet(object.requestId)
        ? globalThis.String(object.requestId)
        : isSet(object.request_id)
        ? globalThis.String(object.request_id)
        : "",
      audio: isSet(object.audio) ? VADAudioSource.fromJSON(object.audio) : undefined,
      options: isSet(object.options) ? VADOptions.fromJSON(object.options) : undefined,
      metadata: isObject(object.metadata)
        ? (globalThis.Object.entries(object.metadata) as [string, any][]).reduce(
          (acc: { [key: string]: string }, [key, value]: [string, any]) => {
            acc[key] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : {},
    };
  },

  toJSON(message: VADProcessRequest): unknown {
    const obj: any = {};
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.audio !== undefined) {
      obj.audio = VADAudioSource.toJSON(message.audio);
    }
    if (message.options !== undefined) {
      obj.options = VADOptions.toJSON(message.options);
    }
    if (message.metadata) {
      const entries = globalThis.Object.entries(message.metadata) as [string, string][];
      if (entries.length > 0) {
        obj.metadata = {};
        entries.forEach(([k, v]) => {
          obj.metadata[k] = v;
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VADProcessRequest>, I>>(base?: I): VADProcessRequest {
    return VADProcessRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VADProcessRequest>, I>>(object: I): VADProcessRequest {
    const message = createBaseVADProcessRequest();
    message.requestId = object.requestId ?? "";
    message.audio = (object.audio !== undefined && object.audio !== null)
      ? VADAudioSource.fromPartial(object.audio)
      : undefined;
    message.options = (object.options !== undefined && object.options !== null)
      ? VADOptions.fromPartial(object.options)
      : undefined;
    message.metadata = (globalThis.Object.entries(object.metadata ?? {}) as [string, string][]).reduce(
      (acc: { [key: string]: string }, [key, value]: [string, string]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    return message;
  },
};

function createBaseVADProcessRequest_MetadataEntry(): VADProcessRequest_MetadataEntry {
  return { key: "", value: "" };
}

export const VADProcessRequest_MetadataEntry: MessageFns<VADProcessRequest_MetadataEntry> = {
  encode(message: VADProcessRequest_MetadataEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VADProcessRequest_MetadataEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVADProcessRequest_MetadataEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VADProcessRequest_MetadataEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: VADProcessRequest_MetadataEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VADProcessRequest_MetadataEntry>, I>>(base?: I): VADProcessRequest_MetadataEntry {
    return VADProcessRequest_MetadataEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VADProcessRequest_MetadataEntry>, I>>(
    object: I,
  ): VADProcessRequest_MetadataEntry {
    const message = createBaseVADProcessRequest_MetadataEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseVADResult(): VADResult {
  return {
    isSpeech: false,
    confidence: 0,
    energy: 0,
    durationMs: 0,
    timestampMs: 0,
    startTimeMs: 0,
    endTimeMs: 0,
    statistics: undefined,
    errorMessage: undefined,
    errorCode: 0,
  };
}

export const VADResult: MessageFns<VADResult> = {
  encode(message: VADResult, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.isSpeech !== false) {
      writer.uint32(8).bool(message.isSpeech);
    }
    if (message.confidence !== 0) {
      writer.uint32(21).float(message.confidence);
    }
    if (message.energy !== 0) {
      writer.uint32(29).float(message.energy);
    }
    if (message.durationMs !== 0) {
      writer.uint32(32).int32(message.durationMs);
    }
    if (message.timestampMs !== 0) {
      writer.uint32(40).int64(message.timestampMs);
    }
    if (message.startTimeMs !== 0) {
      writer.uint32(48).int64(message.startTimeMs);
    }
    if (message.endTimeMs !== 0) {
      writer.uint32(56).int64(message.endTimeMs);
    }
    if (message.statistics !== undefined) {
      VADStatistics.encode(message.statistics, writer.uint32(66).fork()).join();
    }
    if (message.errorMessage !== undefined) {
      writer.uint32(74).string(message.errorMessage);
    }
    if (message.errorCode !== 0) {
      writer.uint32(80).int32(message.errorCode);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VADResult {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVADResult();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.isSpeech = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 21) {
            break;
          }

          message.confidence = reader.float();
          continue;
        }
        case 3: {
          if (tag !== 29) {
            break;
          }

          message.energy = reader.float();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.durationMs = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.timestampMs = longToNumber(reader.int64());
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.startTimeMs = longToNumber(reader.int64());
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.endTimeMs = longToNumber(reader.int64());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.statistics = VADStatistics.decode(reader, reader.uint32());
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.errorMessage = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.errorCode = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VADResult {
    return {
      isSpeech: isSet(object.isSpeech)
        ? globalThis.Boolean(object.isSpeech)
        : isSet(object.is_speech)
        ? globalThis.Boolean(object.is_speech)
        : false,
      confidence: isSet(object.confidence) ? globalThis.Number(object.confidence) : 0,
      energy: isSet(object.energy) ? globalThis.Number(object.energy) : 0,
      durationMs: isSet(object.durationMs)
        ? globalThis.Number(object.durationMs)
        : isSet(object.duration_ms)
        ? globalThis.Number(object.duration_ms)
        : 0,
      timestampMs: isSet(object.timestampMs)
        ? globalThis.Number(object.timestampMs)
        : isSet(object.timestamp_ms)
        ? globalThis.Number(object.timestamp_ms)
        : 0,
      startTimeMs: isSet(object.startTimeMs)
        ? globalThis.Number(object.startTimeMs)
        : isSet(object.start_time_ms)
        ? globalThis.Number(object.start_time_ms)
        : 0,
      endTimeMs: isSet(object.endTimeMs)
        ? globalThis.Number(object.endTimeMs)
        : isSet(object.end_time_ms)
        ? globalThis.Number(object.end_time_ms)
        : 0,
      statistics: isSet(object.statistics) ? VADStatistics.fromJSON(object.statistics) : undefined,
      errorMessage: isSet(object.errorMessage)
        ? globalThis.String(object.errorMessage)
        : isSet(object.error_message)
        ? globalThis.String(object.error_message)
        : undefined,
      errorCode: isSet(object.errorCode)
        ? globalThis.Number(object.errorCode)
        : isSet(object.error_code)
        ? globalThis.Number(object.error_code)
        : 0,
    };
  },

  toJSON(message: VADResult): unknown {
    const obj: any = {};
    if (message.isSpeech !== false) {
      obj.isSpeech = message.isSpeech;
    }
    if (message.confidence !== 0) {
      obj.confidence = message.confidence;
    }
    if (message.energy !== 0) {
      obj.energy = message.energy;
    }
    if (message.durationMs !== 0) {
      obj.durationMs = Math.round(message.durationMs);
    }
    if (message.timestampMs !== 0) {
      obj.timestampMs = Math.round(message.timestampMs);
    }
    if (message.startTimeMs !== 0) {
      obj.startTimeMs = Math.round(message.startTimeMs);
    }
    if (message.endTimeMs !== 0) {
      obj.endTimeMs = Math.round(message.endTimeMs);
    }
    if (message.statistics !== undefined) {
      obj.statistics = VADStatistics.toJSON(message.statistics);
    }
    if (message.errorMessage !== undefined) {
      obj.errorMessage = message.errorMessage;
    }
    if (message.errorCode !== 0) {
      obj.errorCode = Math.round(message.errorCode);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VADResult>, I>>(base?: I): VADResult {
    return VADResult.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VADResult>, I>>(object: I): VADResult {
    const message = createBaseVADResult();
    message.isSpeech = object.isSpeech ?? false;
    message.confidence = object.confidence ?? 0;
    message.energy = object.energy ?? 0;
    message.durationMs = object.durationMs ?? 0;
    message.timestampMs = object.timestampMs ?? 0;
    message.startTimeMs = object.startTimeMs ?? 0;
    message.endTimeMs = object.endTimeMs ?? 0;
    message.statistics = (object.statistics !== undefined && object.statistics !== null)
      ? VADStatistics.fromPartial(object.statistics)
      : undefined;
    message.errorMessage = object.errorMessage ?? undefined;
    message.errorCode = object.errorCode ?? 0;
    return message;
  },
};

function createBaseVADStatistics(): VADStatistics {
  return {
    currentEnergy: 0,
    currentThreshold: 0,
    ambientLevel: 0,
    recentAvg: 0,
    recentMax: 0,
    totalSpeechSegments: 0,
    totalSpeechDurationMs: 0,
    averageEnergy: 0,
    peakEnergy: 0,
  };
}

export const VADStatistics: MessageFns<VADStatistics> = {
  encode(message: VADStatistics, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.currentEnergy !== 0) {
      writer.uint32(13).float(message.currentEnergy);
    }
    if (message.currentThreshold !== 0) {
      writer.uint32(21).float(message.currentThreshold);
    }
    if (message.ambientLevel !== 0) {
      writer.uint32(29).float(message.ambientLevel);
    }
    if (message.recentAvg !== 0) {
      writer.uint32(37).float(message.recentAvg);
    }
    if (message.recentMax !== 0) {
      writer.uint32(45).float(message.recentMax);
    }
    if (message.totalSpeechSegments !== 0) {
      writer.uint32(48).int32(message.totalSpeechSegments);
    }
    if (message.totalSpeechDurationMs !== 0) {
      writer.uint32(56).int64(message.totalSpeechDurationMs);
    }
    if (message.averageEnergy !== 0) {
      writer.uint32(69).float(message.averageEnergy);
    }
    if (message.peakEnergy !== 0) {
      writer.uint32(77).float(message.peakEnergy);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VADStatistics {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVADStatistics();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 13) {
            break;
          }

          message.currentEnergy = reader.float();
          continue;
        }
        case 2: {
          if (tag !== 21) {
            break;
          }

          message.currentThreshold = reader.float();
          continue;
        }
        case 3: {
          if (tag !== 29) {
            break;
          }

          message.ambientLevel = reader.float();
          continue;
        }
        case 4: {
          if (tag !== 37) {
            break;
          }

          message.recentAvg = reader.float();
          continue;
        }
        case 5: {
          if (tag !== 45) {
            break;
          }

          message.recentMax = reader.float();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.totalSpeechSegments = reader.int32();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.totalSpeechDurationMs = longToNumber(reader.int64());
          continue;
        }
        case 8: {
          if (tag !== 69) {
            break;
          }

          message.averageEnergy = reader.float();
          continue;
        }
        case 9: {
          if (tag !== 77) {
            break;
          }

          message.peakEnergy = reader.float();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VADStatistics {
    return {
      currentEnergy: isSet(object.currentEnergy)
        ? globalThis.Number(object.currentEnergy)
        : isSet(object.current_energy)
        ? globalThis.Number(object.current_energy)
        : 0,
      currentThreshold: isSet(object.currentThreshold)
        ? globalThis.Number(object.currentThreshold)
        : isSet(object.current_threshold)
        ? globalThis.Number(object.current_threshold)
        : 0,
      ambientLevel: isSet(object.ambientLevel)
        ? globalThis.Number(object.ambientLevel)
        : isSet(object.ambient_level)
        ? globalThis.Number(object.ambient_level)
        : 0,
      recentAvg: isSet(object.recentAvg)
        ? globalThis.Number(object.recentAvg)
        : isSet(object.recent_avg)
        ? globalThis.Number(object.recent_avg)
        : 0,
      recentMax: isSet(object.recentMax)
        ? globalThis.Number(object.recentMax)
        : isSet(object.recent_max)
        ? globalThis.Number(object.recent_max)
        : 0,
      totalSpeechSegments: isSet(object.totalSpeechSegments)
        ? globalThis.Number(object.totalSpeechSegments)
        : isSet(object.total_speech_segments)
        ? globalThis.Number(object.total_speech_segments)
        : 0,
      totalSpeechDurationMs: isSet(object.totalSpeechDurationMs)
        ? globalThis.Number(object.totalSpeechDurationMs)
        : isSet(object.total_speech_duration_ms)
        ? globalThis.Number(object.total_speech_duration_ms)
        : 0,
      averageEnergy: isSet(object.averageEnergy)
        ? globalThis.Number(object.averageEnergy)
        : isSet(object.average_energy)
        ? globalThis.Number(object.average_energy)
        : 0,
      peakEnergy: isSet(object.peakEnergy)
        ? globalThis.Number(object.peakEnergy)
        : isSet(object.peak_energy)
        ? globalThis.Number(object.peak_energy)
        : 0,
    };
  },

  toJSON(message: VADStatistics): unknown {
    const obj: any = {};
    if (message.currentEnergy !== 0) {
      obj.currentEnergy = message.currentEnergy;
    }
    if (message.currentThreshold !== 0) {
      obj.currentThreshold = message.currentThreshold;
    }
    if (message.ambientLevel !== 0) {
      obj.ambientLevel = message.ambientLevel;
    }
    if (message.recentAvg !== 0) {
      obj.recentAvg = message.recentAvg;
    }
    if (message.recentMax !== 0) {
      obj.recentMax = message.recentMax;
    }
    if (message.totalSpeechSegments !== 0) {
      obj.totalSpeechSegments = Math.round(message.totalSpeechSegments);
    }
    if (message.totalSpeechDurationMs !== 0) {
      obj.totalSpeechDurationMs = Math.round(message.totalSpeechDurationMs);
    }
    if (message.averageEnergy !== 0) {
      obj.averageEnergy = message.averageEnergy;
    }
    if (message.peakEnergy !== 0) {
      obj.peakEnergy = message.peakEnergy;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VADStatistics>, I>>(base?: I): VADStatistics {
    return VADStatistics.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VADStatistics>, I>>(object: I): VADStatistics {
    const message = createBaseVADStatistics();
    message.currentEnergy = object.currentEnergy ?? 0;
    message.currentThreshold = object.currentThreshold ?? 0;
    message.ambientLevel = object.ambientLevel ?? 0;
    message.recentAvg = object.recentAvg ?? 0;
    message.recentMax = object.recentMax ?? 0;
    message.totalSpeechSegments = object.totalSpeechSegments ?? 0;
    message.totalSpeechDurationMs = object.totalSpeechDurationMs ?? 0;
    message.averageEnergy = object.averageEnergy ?? 0;
    message.peakEnergy = object.peakEnergy ?? 0;
    return message;
  },
};

function createBaseSpeechActivityEvent(): SpeechActivityEvent {
  return { eventType: 0, timestampMs: 0, durationMs: 0, confidence: 0, result: undefined, segmentId: undefined };
}

export const SpeechActivityEvent: MessageFns<SpeechActivityEvent> = {
  encode(message: SpeechActivityEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.eventType !== 0) {
      writer.uint32(8).int32(message.eventType);
    }
    if (message.timestampMs !== 0) {
      writer.uint32(16).int64(message.timestampMs);
    }
    if (message.durationMs !== 0) {
      writer.uint32(24).int32(message.durationMs);
    }
    if (message.confidence !== 0) {
      writer.uint32(37).float(message.confidence);
    }
    if (message.result !== undefined) {
      VADResult.encode(message.result, writer.uint32(42).fork()).join();
    }
    if (message.segmentId !== undefined) {
      writer.uint32(50).string(message.segmentId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SpeechActivityEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSpeechActivityEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.eventType = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.timestampMs = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.durationMs = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 37) {
            break;
          }

          message.confidence = reader.float();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.result = VADResult.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.segmentId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SpeechActivityEvent {
    return {
      eventType: isSet(object.eventType)
        ? speechActivityKindFromJSON(object.eventType)
        : isSet(object.event_type)
        ? speechActivityKindFromJSON(object.event_type)
        : 0,
      timestampMs: isSet(object.timestampMs)
        ? globalThis.Number(object.timestampMs)
        : isSet(object.timestamp_ms)
        ? globalThis.Number(object.timestamp_ms)
        : 0,
      durationMs: isSet(object.durationMs)
        ? globalThis.Number(object.durationMs)
        : isSet(object.duration_ms)
        ? globalThis.Number(object.duration_ms)
        : 0,
      confidence: isSet(object.confidence) ? globalThis.Number(object.confidence) : 0,
      result: isSet(object.result) ? VADResult.fromJSON(object.result) : undefined,
      segmentId: isSet(object.segmentId)
        ? globalThis.String(object.segmentId)
        : isSet(object.segment_id)
        ? globalThis.String(object.segment_id)
        : undefined,
    };
  },

  toJSON(message: SpeechActivityEvent): unknown {
    const obj: any = {};
    if (message.eventType !== 0) {
      obj.eventType = speechActivityKindToJSON(message.eventType);
    }
    if (message.timestampMs !== 0) {
      obj.timestampMs = Math.round(message.timestampMs);
    }
    if (message.durationMs !== 0) {
      obj.durationMs = Math.round(message.durationMs);
    }
    if (message.confidence !== 0) {
      obj.confidence = message.confidence;
    }
    if (message.result !== undefined) {
      obj.result = VADResult.toJSON(message.result);
    }
    if (message.segmentId !== undefined) {
      obj.segmentId = message.segmentId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SpeechActivityEvent>, I>>(base?: I): SpeechActivityEvent {
    return SpeechActivityEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SpeechActivityEvent>, I>>(object: I): SpeechActivityEvent {
    const message = createBaseSpeechActivityEvent();
    message.eventType = object.eventType ?? 0;
    message.timestampMs = object.timestampMs ?? 0;
    message.durationMs = object.durationMs ?? 0;
    message.confidence = object.confidence ?? 0;
    message.result = (object.result !== undefined && object.result !== null)
      ? VADResult.fromPartial(object.result)
      : undefined;
    message.segmentId = object.segmentId ?? undefined;
    return message;
  },
};

function createBaseVADStreamEvent(): VADStreamEvent {
  return {
    seq: 0,
    timestampUs: 0,
    requestId: "",
    kind: 0,
    result: undefined,
    activity: undefined,
    statistics: undefined,
    errorMessage: undefined,
    errorCode: 0,
  };
}

export const VADStreamEvent: MessageFns<VADStreamEvent> = {
  encode(message: VADStreamEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.seq !== 0) {
      writer.uint32(8).uint64(message.seq);
    }
    if (message.timestampUs !== 0) {
      writer.uint32(16).int64(message.timestampUs);
    }
    if (message.requestId !== "") {
      writer.uint32(26).string(message.requestId);
    }
    if (message.kind !== 0) {
      writer.uint32(32).int32(message.kind);
    }
    if (message.result !== undefined) {
      VADResult.encode(message.result, writer.uint32(42).fork()).join();
    }
    if (message.activity !== undefined) {
      SpeechActivityEvent.encode(message.activity, writer.uint32(50).fork()).join();
    }
    if (message.statistics !== undefined) {
      VADStatistics.encode(message.statistics, writer.uint32(58).fork()).join();
    }
    if (message.errorMessage !== undefined) {
      writer.uint32(66).string(message.errorMessage);
    }
    if (message.errorCode !== 0) {
      writer.uint32(72).int32(message.errorCode);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VADStreamEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVADStreamEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.seq = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.timestampUs = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.kind = reader.int32() as any;
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.result = VADResult.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.activity = SpeechActivityEvent.decode(reader, reader.uint32());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.statistics = VADStatistics.decode(reader, reader.uint32());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.errorMessage = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.errorCode = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VADStreamEvent {
    return {
      seq: isSet(object.seq) ? globalThis.Number(object.seq) : 0,
      timestampUs: isSet(object.timestampUs)
        ? globalThis.Number(object.timestampUs)
        : isSet(object.timestamp_us)
        ? globalThis.Number(object.timestamp_us)
        : 0,
      requestId: isSet(object.requestId)
        ? globalThis.String(object.requestId)
        : isSet(object.request_id)
        ? globalThis.String(object.request_id)
        : "",
      kind: isSet(object.kind) ? vADStreamEventKindFromJSON(object.kind) : 0,
      result: isSet(object.result) ? VADResult.fromJSON(object.result) : undefined,
      activity: isSet(object.activity) ? SpeechActivityEvent.fromJSON(object.activity) : undefined,
      statistics: isSet(object.statistics) ? VADStatistics.fromJSON(object.statistics) : undefined,
      errorMessage: isSet(object.errorMessage)
        ? globalThis.String(object.errorMessage)
        : isSet(object.error_message)
        ? globalThis.String(object.error_message)
        : undefined,
      errorCode: isSet(object.errorCode)
        ? globalThis.Number(object.errorCode)
        : isSet(object.error_code)
        ? globalThis.Number(object.error_code)
        : 0,
    };
  },

  toJSON(message: VADStreamEvent): unknown {
    const obj: any = {};
    if (message.seq !== 0) {
      obj.seq = Math.round(message.seq);
    }
    if (message.timestampUs !== 0) {
      obj.timestampUs = Math.round(message.timestampUs);
    }
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.kind !== 0) {
      obj.kind = vADStreamEventKindToJSON(message.kind);
    }
    if (message.result !== undefined) {
      obj.result = VADResult.toJSON(message.result);
    }
    if (message.activity !== undefined) {
      obj.activity = SpeechActivityEvent.toJSON(message.activity);
    }
    if (message.statistics !== undefined) {
      obj.statistics = VADStatistics.toJSON(message.statistics);
    }
    if (message.errorMessage !== undefined) {
      obj.errorMessage = message.errorMessage;
    }
    if (message.errorCode !== 0) {
      obj.errorCode = Math.round(message.errorCode);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VADStreamEvent>, I>>(base?: I): VADStreamEvent {
    return VADStreamEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VADStreamEvent>, I>>(object: I): VADStreamEvent {
    const message = createBaseVADStreamEvent();
    message.seq = object.seq ?? 0;
    message.timestampUs = object.timestampUs ?? 0;
    message.requestId = object.requestId ?? "";
    message.kind = object.kind ?? 0;
    message.result = (object.result !== undefined && object.result !== null)
      ? VADResult.fromPartial(object.result)
      : undefined;
    message.activity = (object.activity !== undefined && object.activity !== null)
      ? SpeechActivityEvent.fromPartial(object.activity)
      : undefined;
    message.statistics = (object.statistics !== undefined && object.statistics !== null)
      ? VADStatistics.fromPartial(object.statistics)
      : undefined;
    message.errorMessage = object.errorMessage ?? undefined;
    message.errorCode = object.errorCode ?? 0;
    return message;
  },
};

function createBaseVADServiceState(): VADServiceState {
  return {
    isReady: false,
    isSpeechActive: false,
    energyThreshold: 0,
    sampleRate: 0,
    frameLengthMs: 0,
    currentModel: undefined,
    errorMessage: undefined,
    errorCode: 0,
  };
}

export const VADServiceState: MessageFns<VADServiceState> = {
  encode(message: VADServiceState, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.isReady !== false) {
      writer.uint32(8).bool(message.isReady);
    }
    if (message.isSpeechActive !== false) {
      writer.uint32(16).bool(message.isSpeechActive);
    }
    if (message.energyThreshold !== 0) {
      writer.uint32(29).float(message.energyThreshold);
    }
    if (message.sampleRate !== 0) {
      writer.uint32(32).int32(message.sampleRate);
    }
    if (message.frameLengthMs !== 0) {
      writer.uint32(40).int32(message.frameLengthMs);
    }
    if (message.currentModel !== undefined) {
      writer.uint32(50).string(message.currentModel);
    }
    if (message.errorMessage !== undefined) {
      writer.uint32(58).string(message.errorMessage);
    }
    if (message.errorCode !== 0) {
      writer.uint32(64).int32(message.errorCode);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VADServiceState {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVADServiceState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.isReady = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.isSpeechActive = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 29) {
            break;
          }

          message.energyThreshold = reader.float();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.sampleRate = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.frameLengthMs = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.currentModel = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.errorMessage = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.errorCode = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VADServiceState {
    return {
      isReady: isSet(object.isReady)
        ? globalThis.Boolean(object.isReady)
        : isSet(object.is_ready)
        ? globalThis.Boolean(object.is_ready)
        : false,
      isSpeechActive: isSet(object.isSpeechActive)
        ? globalThis.Boolean(object.isSpeechActive)
        : isSet(object.is_speech_active)
        ? globalThis.Boolean(object.is_speech_active)
        : false,
      energyThreshold: isSet(object.energyThreshold)
        ? globalThis.Number(object.energyThreshold)
        : isSet(object.energy_threshold)
        ? globalThis.Number(object.energy_threshold)
        : 0,
      sampleRate: isSet(object.sampleRate)
        ? globalThis.Number(object.sampleRate)
        : isSet(object.sample_rate)
        ? globalThis.Number(object.sample_rate)
        : 0,
      frameLengthMs: isSet(object.frameLengthMs)
        ? globalThis.Number(object.frameLengthMs)
        : isSet(object.frame_length_ms)
        ? globalThis.Number(object.frame_length_ms)
        : 0,
      currentModel: isSet(object.currentModel)
        ? globalThis.String(object.currentModel)
        : isSet(object.current_model)
        ? globalThis.String(object.current_model)
        : undefined,
      errorMessage: isSet(object.errorMessage)
        ? globalThis.String(object.errorMessage)
        : isSet(object.error_message)
        ? globalThis.String(object.error_message)
        : undefined,
      errorCode: isSet(object.errorCode)
        ? globalThis.Number(object.errorCode)
        : isSet(object.error_code)
        ? globalThis.Number(object.error_code)
        : 0,
    };
  },

  toJSON(message: VADServiceState): unknown {
    const obj: any = {};
    if (message.isReady !== false) {
      obj.isReady = message.isReady;
    }
    if (message.isSpeechActive !== false) {
      obj.isSpeechActive = message.isSpeechActive;
    }
    if (message.energyThreshold !== 0) {
      obj.energyThreshold = message.energyThreshold;
    }
    if (message.sampleRate !== 0) {
      obj.sampleRate = Math.round(message.sampleRate);
    }
    if (message.frameLengthMs !== 0) {
      obj.frameLengthMs = Math.round(message.frameLengthMs);
    }
    if (message.currentModel !== undefined) {
      obj.currentModel = message.currentModel;
    }
    if (message.errorMessage !== undefined) {
      obj.errorMessage = message.errorMessage;
    }
    if (message.errorCode !== 0) {
      obj.errorCode = Math.round(message.errorCode);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VADServiceState>, I>>(base?: I): VADServiceState {
    return VADServiceState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VADServiceState>, I>>(object: I): VADServiceState {
    const message = createBaseVADServiceState();
    message.isReady = object.isReady ?? false;
    message.isSpeechActive = object.isSpeechActive ?? false;
    message.energyThreshold = object.energyThreshold ?? 0;
    message.sampleRate = object.sampleRate ?? 0;
    message.frameLengthMs = object.frameLengthMs ?? 0;
    message.currentModel = object.currentModel ?? undefined;
    message.errorMessage = object.errorMessage ?? undefined;
    message.errorCode = object.errorCode ?? 0;
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  const bin = globalThis.atob(b64);
  const arr = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; ++i) {
    arr[i] = bin.charCodeAt(i);
  }
  return arr;
}

function base64FromBytes(arr: Uint8Array): string {
  const bin: string[] = [];
  arr.forEach((byte) => {
    bin.push(globalThis.String.fromCharCode(byte));
  });
  return globalThis.btoa(bin.join(""));
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
