// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.35.1
// source: vlm_options.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { InferenceFramework, inferenceFrameworkFromJSON, inferenceFrameworkToJSON } from "./model_types";

export const protobufPackage = "runanywhere.v1";

/**
 * ---------------------------------------------------------------------------
 * VLM image input format — union across all SDKs and the C ABI.
 *
 * SDK ↔ proto enum mapping pre-IDL:
 *   C ABI  / Kotlin / RN / Web all expose three numeric formats (FILE_PATH=0,
 *          RGB_PIXELS=1, BASE64=2). Mapped to FILE_PATH, RAW_RGB, BASE64.
 *   Swift  Format enum adds Apple-only cases uiImage / pixelBuffer that are
 *          flattened to RAW_RGB before crossing the C ABI (see VLMTypes.swift
 *          lines 70-89). RAW_RGBA is reserved for SDKs that pass straight
 *          RGBA pixel buffers without the BGRA→RGB downsample step.
 *   Dart   sealed class with the same three formats (filePath / rgbPixels /
 *          base64); Flutter adapter passes RGB pixels through to the C ABI.
 *
 * JPEG / PNG / WEBP are container hints carried in the encoded `bytes`
 * payload (no current SDK declares these as enum cases — they are
 * reserved here so we can disambiguate decoded vs encoded sources without a
 * schema migration once a backend exposes container detection).
 * ---------------------------------------------------------------------------
 */
export enum VLMImageFormat {
  VLM_IMAGE_FORMAT_UNSPECIFIED = 0,
  /** VLM_IMAGE_FORMAT_JPEG - reserved — encoded JPEG bytes */
  VLM_IMAGE_FORMAT_JPEG = 1,
  /** VLM_IMAGE_FORMAT_PNG - reserved — encoded PNG bytes */
  VLM_IMAGE_FORMAT_PNG = 2,
  /** VLM_IMAGE_FORMAT_WEBP - reserved — encoded WebP bytes */
  VLM_IMAGE_FORMAT_WEBP = 3,
  /** VLM_IMAGE_FORMAT_RAW_RGB - Swift rgbPixels / Kotlin RGB_PIXELS / */
  VLM_IMAGE_FORMAT_RAW_RGB = 4,
  /**
   * VLM_IMAGE_FORMAT_RAW_RGBA - RN RGBPixels / Web RGBPixels /
   * C ABI RAC_VLM_IMAGE_FORMAT_RGB_PIXELS
   */
  VLM_IMAGE_FORMAT_RAW_RGBA = 5,
  /**
   * VLM_IMAGE_FORMAT_BASE64 - (Swift UIImage path produces RGBA
   * before downsample; pre-IDL no SDK
   * exposes RGBA over the C ABI)
   */
  VLM_IMAGE_FORMAT_BASE64 = 6,
  /**
   * VLM_IMAGE_FORMAT_FILE_PATH - Dart base64 / RN Base64 /
   * Web Base64 /
   * C ABI RAC_VLM_IMAGE_FORMAT_BASE64
   */
  VLM_IMAGE_FORMAT_FILE_PATH = 7,
  UNRECOGNIZED = -1,
}

export function vLMImageFormatFromJSON(object: any): VLMImageFormat {
  switch (object) {
    case 0:
    case "VLM_IMAGE_FORMAT_UNSPECIFIED":
      return VLMImageFormat.VLM_IMAGE_FORMAT_UNSPECIFIED;
    case 1:
    case "VLM_IMAGE_FORMAT_JPEG":
      return VLMImageFormat.VLM_IMAGE_FORMAT_JPEG;
    case 2:
    case "VLM_IMAGE_FORMAT_PNG":
      return VLMImageFormat.VLM_IMAGE_FORMAT_PNG;
    case 3:
    case "VLM_IMAGE_FORMAT_WEBP":
      return VLMImageFormat.VLM_IMAGE_FORMAT_WEBP;
    case 4:
    case "VLM_IMAGE_FORMAT_RAW_RGB":
      return VLMImageFormat.VLM_IMAGE_FORMAT_RAW_RGB;
    case 5:
    case "VLM_IMAGE_FORMAT_RAW_RGBA":
      return VLMImageFormat.VLM_IMAGE_FORMAT_RAW_RGBA;
    case 6:
    case "VLM_IMAGE_FORMAT_BASE64":
      return VLMImageFormat.VLM_IMAGE_FORMAT_BASE64;
    case 7:
    case "VLM_IMAGE_FORMAT_FILE_PATH":
      return VLMImageFormat.VLM_IMAGE_FORMAT_FILE_PATH;
    case -1:
    case "UNRECOGNIZED":
    default:
      return VLMImageFormat.UNRECOGNIZED;
  }
}

export function vLMImageFormatToJSON(object: VLMImageFormat): string {
  switch (object) {
    case VLMImageFormat.VLM_IMAGE_FORMAT_UNSPECIFIED:
      return "VLM_IMAGE_FORMAT_UNSPECIFIED";
    case VLMImageFormat.VLM_IMAGE_FORMAT_JPEG:
      return "VLM_IMAGE_FORMAT_JPEG";
    case VLMImageFormat.VLM_IMAGE_FORMAT_PNG:
      return "VLM_IMAGE_FORMAT_PNG";
    case VLMImageFormat.VLM_IMAGE_FORMAT_WEBP:
      return "VLM_IMAGE_FORMAT_WEBP";
    case VLMImageFormat.VLM_IMAGE_FORMAT_RAW_RGB:
      return "VLM_IMAGE_FORMAT_RAW_RGB";
    case VLMImageFormat.VLM_IMAGE_FORMAT_RAW_RGBA:
      return "VLM_IMAGE_FORMAT_RAW_RGBA";
    case VLMImageFormat.VLM_IMAGE_FORMAT_BASE64:
      return "VLM_IMAGE_FORMAT_BASE64";
    case VLMImageFormat.VLM_IMAGE_FORMAT_FILE_PATH:
      return "VLM_IMAGE_FORMAT_FILE_PATH";
    case VLMImageFormat.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/**
 * ---------------------------------------------------------------------------
 * VLM model family for chat-template selection.
 * Mirrors rac_vlm_model_family_t.
 * ---------------------------------------------------------------------------
 */
export enum VLMModelFamily {
  VLM_MODEL_FAMILY_UNSPECIFIED = 0,
  VLM_MODEL_FAMILY_AUTO = 1,
  VLM_MODEL_FAMILY_QWEN2_VL = 2,
  VLM_MODEL_FAMILY_SMOLVLM = 3,
  VLM_MODEL_FAMILY_LLAVA = 4,
  VLM_MODEL_FAMILY_CUSTOM = 99,
  UNRECOGNIZED = -1,
}

export function vLMModelFamilyFromJSON(object: any): VLMModelFamily {
  switch (object) {
    case 0:
    case "VLM_MODEL_FAMILY_UNSPECIFIED":
      return VLMModelFamily.VLM_MODEL_FAMILY_UNSPECIFIED;
    case 1:
    case "VLM_MODEL_FAMILY_AUTO":
      return VLMModelFamily.VLM_MODEL_FAMILY_AUTO;
    case 2:
    case "VLM_MODEL_FAMILY_QWEN2_VL":
      return VLMModelFamily.VLM_MODEL_FAMILY_QWEN2_VL;
    case 3:
    case "VLM_MODEL_FAMILY_SMOLVLM":
      return VLMModelFamily.VLM_MODEL_FAMILY_SMOLVLM;
    case 4:
    case "VLM_MODEL_FAMILY_LLAVA":
      return VLMModelFamily.VLM_MODEL_FAMILY_LLAVA;
    case 99:
    case "VLM_MODEL_FAMILY_CUSTOM":
      return VLMModelFamily.VLM_MODEL_FAMILY_CUSTOM;
    case -1:
    case "UNRECOGNIZED":
    default:
      return VLMModelFamily.UNRECOGNIZED;
  }
}

export function vLMModelFamilyToJSON(object: VLMModelFamily): string {
  switch (object) {
    case VLMModelFamily.VLM_MODEL_FAMILY_UNSPECIFIED:
      return "VLM_MODEL_FAMILY_UNSPECIFIED";
    case VLMModelFamily.VLM_MODEL_FAMILY_AUTO:
      return "VLM_MODEL_FAMILY_AUTO";
    case VLMModelFamily.VLM_MODEL_FAMILY_QWEN2_VL:
      return "VLM_MODEL_FAMILY_QWEN2_VL";
    case VLMModelFamily.VLM_MODEL_FAMILY_SMOLVLM:
      return "VLM_MODEL_FAMILY_SMOLVLM";
    case VLMModelFamily.VLM_MODEL_FAMILY_LLAVA:
      return "VLM_MODEL_FAMILY_LLAVA";
    case VLMModelFamily.VLM_MODEL_FAMILY_CUSTOM:
      return "VLM_MODEL_FAMILY_CUSTOM";
    case VLMModelFamily.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum VLMStreamEventKind {
  VLM_STREAM_EVENT_KIND_UNSPECIFIED = 0,
  VLM_STREAM_EVENT_KIND_STARTED = 1,
  VLM_STREAM_EVENT_KIND_IMAGE_ENCODED = 2,
  VLM_STREAM_EVENT_KIND_TOKEN = 3,
  VLM_STREAM_EVENT_KIND_COMPLETED = 4,
  VLM_STREAM_EVENT_KIND_ERROR = 5,
  UNRECOGNIZED = -1,
}

export function vLMStreamEventKindFromJSON(object: any): VLMStreamEventKind {
  switch (object) {
    case 0:
    case "VLM_STREAM_EVENT_KIND_UNSPECIFIED":
      return VLMStreamEventKind.VLM_STREAM_EVENT_KIND_UNSPECIFIED;
    case 1:
    case "VLM_STREAM_EVENT_KIND_STARTED":
      return VLMStreamEventKind.VLM_STREAM_EVENT_KIND_STARTED;
    case 2:
    case "VLM_STREAM_EVENT_KIND_IMAGE_ENCODED":
      return VLMStreamEventKind.VLM_STREAM_EVENT_KIND_IMAGE_ENCODED;
    case 3:
    case "VLM_STREAM_EVENT_KIND_TOKEN":
      return VLMStreamEventKind.VLM_STREAM_EVENT_KIND_TOKEN;
    case 4:
    case "VLM_STREAM_EVENT_KIND_COMPLETED":
      return VLMStreamEventKind.VLM_STREAM_EVENT_KIND_COMPLETED;
    case 5:
    case "VLM_STREAM_EVENT_KIND_ERROR":
      return VLMStreamEventKind.VLM_STREAM_EVENT_KIND_ERROR;
    case -1:
    case "UNRECOGNIZED":
    default:
      return VLMStreamEventKind.UNRECOGNIZED;
  }
}

export function vLMStreamEventKindToJSON(object: VLMStreamEventKind): string {
  switch (object) {
    case VLMStreamEventKind.VLM_STREAM_EVENT_KIND_UNSPECIFIED:
      return "VLM_STREAM_EVENT_KIND_UNSPECIFIED";
    case VLMStreamEventKind.VLM_STREAM_EVENT_KIND_STARTED:
      return "VLM_STREAM_EVENT_KIND_STARTED";
    case VLMStreamEventKind.VLM_STREAM_EVENT_KIND_IMAGE_ENCODED:
      return "VLM_STREAM_EVENT_KIND_IMAGE_ENCODED";
    case VLMStreamEventKind.VLM_STREAM_EVENT_KIND_TOKEN:
      return "VLM_STREAM_EVENT_KIND_TOKEN";
    case VLMStreamEventKind.VLM_STREAM_EVENT_KIND_COMPLETED:
      return "VLM_STREAM_EVENT_KIND_COMPLETED";
    case VLMStreamEventKind.VLM_STREAM_EVENT_KIND_ERROR:
      return "VLM_STREAM_EVENT_KIND_ERROR";
    case VLMStreamEventKind.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/**
 * ---------------------------------------------------------------------------
 * Custom VLM chat template.
 * Mirrors rac_vlm_chat_template_t.
 * ---------------------------------------------------------------------------
 */
export interface VLMChatTemplate {
  templateText: string;
  imageMarker?: string | undefined;
  defaultSystemPrompt?: string | undefined;
}

/**
 * ---------------------------------------------------------------------------
 * VLM image input.
 *
 * `source` is a oneof so that exactly one of {file_path, encoded, raw_rgb,
 * base64} can be supplied per request. `width` / `height` are required for
 * non-encoded formats (raw_rgb, raw_rgba) where the consumer cannot infer
 * dimensions from a container header. `format` disambiguates encoded `bytes`
 * payloads (JPEG / PNG / WEBP) and explicitly tags raw / file-path / base64
 * sources.
 * ---------------------------------------------------------------------------
 */
export interface VLMImage {
  /** VLM_IMAGE_FORMAT_FILE_PATH */
  filePath?:
    | string
    | undefined;
  /** VLM_IMAGE_FORMAT_{JPEG,PNG,WEBP} container bytes */
  encoded?:
    | Uint8Array
    | undefined;
  /** VLM_IMAGE_FORMAT_RAW_RGB / RAW_RGBA pixel buffer */
  rawRgb?:
    | Uint8Array
    | undefined;
  /** VLM_IMAGE_FORMAT_BASE64 (UTF-8 string) */
  base64?:
    | string
    | undefined;
  /**
   * Required for VLM_IMAGE_FORMAT_RAW_RGB and VLM_IMAGE_FORMAT_RAW_RGBA
   * (consumers cannot infer dimensions for raw pixel buffers). Optional
   * for encoded / file_path / base64 sources where the decoder reads
   * dimensions from the container.
   */
  width: number;
  height: number;
  format: VLMImageFormat;
  /**
   * Optional source metadata. Adapters may populate this after camera/file
   * picker capture without exposing native APIs to core.
   */
  mediaType?: string | undefined;
  name?: string | undefined;
  sizeBytes: number;
  metadata: { [key: string]: string };
}

export interface VLMImage_MetadataEntry {
  key: string;
  value: string;
}

/**
 * ---------------------------------------------------------------------------
 * VLM component configuration.
 * Sources pre-IDL:
 *   Kotlin VLMTypes.kt:163        (modelId, contextLength, temperature,
 *                                  maxTokens, systemPrompt, streamingEnabled,
 *                                  preferredFramework)
 *   C ABI  rac_vlm_types.h:224    (model_id, preferred_framework,
 *                                  context_length, temperature, max_tokens,
 *                                  system_prompt, streaming_enabled)
 *
 * Per the canonicalization brief, only the load-bearing identification +
 * limits cross the IDL boundary here: model_id, max_image_size_px, max_tokens.
 * Per-request sampling parameters live on VLMGenerationOptions; runtime
 * streaming toggles and chat-template selection stay backend-private.
 * ---------------------------------------------------------------------------
 */
export interface VLMConfiguration {
  modelId: string;
  /** Kotlin maxImageSize / C ABI max_image_size */
  maxImageSizePx: number;
  /** (0 = backend default) */
  maxTokens: number;
  /** Additional component-level fields from rac_vlm_config_t. */
  contextLength: number;
  temperature: number;
  systemPrompt?: string | undefined;
  streamingEnabled: boolean;
  preferredFramework?: InferenceFramework | undefined;
}

/**
 * ---------------------------------------------------------------------------
 * VLM generation options — per-request sampling + prompt parameters.
 * Sources pre-IDL:
 *   Kotlin VLMTypes.kt:103        (maxTokens, temperature, topP, systemPrompt,
 *                                  maxImageSize, nThreads, useGpu)
 *   Dart   vlm_types.dart:127     (maxTokens, temperature, topP, systemPrompt,
 *                                  maxImageSize, nThreads, useGpu)
 *   RN     VLMTypes.ts:21         (maxTokens, temperature, topP)
 *   Web    VLMTypes.ts:28         (maxTokens, temperature, topP, systemPrompt,
 *                                  modelFamily, streaming)
 *   C ABI  rac_vlm_types.h:143    (max_tokens, temperature, top_p,
 *                                  stop_sequences, num_stop_sequences,
 *                                  streaming_enabled, system_prompt,
 *                                  max_image_size, n_threads, use_gpu,
 *                                  model_family, custom_chat_template,
 *                                  image_marker_override)
 *
 * top_k is included to align with the other text generation services
 * (LLM / chat) even though no current VLM SDK exposes it; the C ABI's
 * llama.cpp backend already supports top_k internally.
 * ---------------------------------------------------------------------------
 */
export interface VLMGenerationOptions {
  prompt: string;
  maxTokens: number;
  temperature: number;
  topP: number;
  topK: number;
  /** Full rac_vlm_options_t coverage. */
  stopSequences: string[];
  streamingEnabled: boolean;
  systemPrompt?: string | undefined;
  maxImageSize: number;
  nThreads: number;
  useGpu: boolean;
  modelFamily: VLMModelFamily;
  customChatTemplate?: VLMChatTemplate | undefined;
  imageMarkerOverride?:
    | string
    | undefined;
  /** Additional llama.cpp sampling knobs and result controls. */
  seed: number;
  repetitionPenalty: number;
  minP: number;
  emitImageEmbeddings: boolean;
}

export interface VLMGenerationRequest {
  requestId: string;
  images: VLMImage[];
  options?: VLMGenerationOptions | undefined;
  modelId?: string | undefined;
  metadata: { [key: string]: string };
}

export interface VLMGenerationRequest_MetadataEntry {
  key: string;
  value: string;
}

/**
 * ---------------------------------------------------------------------------
 * VLM generation result.
 * Sources pre-IDL:
 *   Swift  VLMTypes.swift:208     (text, promptTokens, completionTokens,
 *                                  totalTimeMs as Double, tokensPerSecond)
 *   Kotlin VLMTypes.kt:120        (text, promptTokens, imageTokens,
 *                                  completionTokens, totalTokens,
 *                                  timeToFirstTokenMs, imageEncodeTimeMs,
 *                                  totalTimeMs, tokensPerSecond)
 *   Dart   vlm_types.dart:68      (text, promptTokens, completionTokens,
 *                                  totalTimeMs, tokensPerSecond)
 *   RN     VLMTypes.ts:28         (text, promptTokens, completionTokens,
 *                                  totalTimeMs, tokensPerSecond)
 *   Web    VLMTypes.ts:38         (VLMGenerationResult: text, promptTokens,
 *                                  imageTokens, completionTokens, totalTokens,
 *                                  timeToFirstTokenMs, imageEncodeTimeMs,
 *                                  totalTimeMs, tokensPerSecond, hardwareUsed)
 *   C ABI  rac_vlm_types.h:268    (text, prompt_tokens, image_tokens,
 *                                  completion_tokens, total_tokens,
 *                                  time_to_first_token_ms,
 *                                  image_encode_time_ms, total_time_ms,
 *                                  tokens_per_second)
 *
 * Streaming note: the VLM service emits VLMStreamEvent messages for
 * per-token deltas and terminal results; this aggregate result is carried on
 * the unary Generate RPC and on terminal stream events.
 * ---------------------------------------------------------------------------
 */
export interface VLMResult {
  text: string;
  promptTokens: number;
  completionTokens: number;
  totalTokens: number;
  /** Kotlin/C ABI total_time_ms; */
  processingTimeMs: number;
  /** Swift VLMResult totalTimeMs (Double ms). */
  tokensPerSecond: number;
  /** Detailed VLM metrics from Kotlin/Web/C ABI. */
  imageTokens: number;
  timeToFirstTokenMs: number;
  imageEncodeTimeMs: number;
  hardwareUsed?: string | undefined;
  errorMessage?: string | undefined;
  errorCode: number;
  finishReason: string;
  imagesProcessed: number;
}

export interface VLMStreamEvent {
  seq: number;
  timestampUs: number;
  requestId: string;
  kind: VLMStreamEventKind;
  token: string;
  tokenIndex: number;
  isFinal: boolean;
  tokensPerSecond: number;
  result?: VLMResult | undefined;
  errorMessage?: string | undefined;
  errorCode: number;
}

export interface VLMServiceState {
  isReady: boolean;
  currentModel?: string | undefined;
  contextLength: number;
  supportsStreaming: boolean;
  supportsMultipleImages: boolean;
  visionEncoderType?: string | undefined;
  errorMessage?: string | undefined;
  errorCode: number;
}

function createBaseVLMChatTemplate(): VLMChatTemplate {
  return { templateText: "", imageMarker: undefined, defaultSystemPrompt: undefined };
}

export const VLMChatTemplate: MessageFns<VLMChatTemplate> = {
  encode(message: VLMChatTemplate, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.templateText !== "") {
      writer.uint32(10).string(message.templateText);
    }
    if (message.imageMarker !== undefined) {
      writer.uint32(18).string(message.imageMarker);
    }
    if (message.defaultSystemPrompt !== undefined) {
      writer.uint32(26).string(message.defaultSystemPrompt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VLMChatTemplate {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVLMChatTemplate();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.templateText = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.imageMarker = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.defaultSystemPrompt = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VLMChatTemplate {
    return {
      templateText: isSet(object.templateText)
        ? globalThis.String(object.templateText)
        : isSet(object.template_text)
        ? globalThis.String(object.template_text)
        : "",
      imageMarker: isSet(object.imageMarker)
        ? globalThis.String(object.imageMarker)
        : isSet(object.image_marker)
        ? globalThis.String(object.image_marker)
        : undefined,
      defaultSystemPrompt: isSet(object.defaultSystemPrompt)
        ? globalThis.String(object.defaultSystemPrompt)
        : isSet(object.default_system_prompt)
        ? globalThis.String(object.default_system_prompt)
        : undefined,
    };
  },

  toJSON(message: VLMChatTemplate): unknown {
    const obj: any = {};
    if (message.templateText !== "") {
      obj.templateText = message.templateText;
    }
    if (message.imageMarker !== undefined) {
      obj.imageMarker = message.imageMarker;
    }
    if (message.defaultSystemPrompt !== undefined) {
      obj.defaultSystemPrompt = message.defaultSystemPrompt;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VLMChatTemplate>, I>>(base?: I): VLMChatTemplate {
    return VLMChatTemplate.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VLMChatTemplate>, I>>(object: I): VLMChatTemplate {
    const message = createBaseVLMChatTemplate();
    message.templateText = object.templateText ?? "";
    message.imageMarker = object.imageMarker ?? undefined;
    message.defaultSystemPrompt = object.defaultSystemPrompt ?? undefined;
    return message;
  },
};

function createBaseVLMImage(): VLMImage {
  return {
    filePath: undefined,
    encoded: undefined,
    rawRgb: undefined,
    base64: undefined,
    width: 0,
    height: 0,
    format: 0,
    mediaType: undefined,
    name: undefined,
    sizeBytes: 0,
    metadata: {},
  };
}

export const VLMImage: MessageFns<VLMImage> = {
  encode(message: VLMImage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.filePath !== undefined) {
      writer.uint32(10).string(message.filePath);
    }
    if (message.encoded !== undefined) {
      writer.uint32(18).bytes(message.encoded);
    }
    if (message.rawRgb !== undefined) {
      writer.uint32(26).bytes(message.rawRgb);
    }
    if (message.base64 !== undefined) {
      writer.uint32(34).string(message.base64);
    }
    if (message.width !== 0) {
      writer.uint32(40).int32(message.width);
    }
    if (message.height !== 0) {
      writer.uint32(48).int32(message.height);
    }
    if (message.format !== 0) {
      writer.uint32(56).int32(message.format);
    }
    if (message.mediaType !== undefined) {
      writer.uint32(66).string(message.mediaType);
    }
    if (message.name !== undefined) {
      writer.uint32(74).string(message.name);
    }
    if (message.sizeBytes !== 0) {
      writer.uint32(80).int64(message.sizeBytes);
    }
    globalThis.Object.entries(message.metadata).forEach(([key, value]: [string, string]) => {
      VLMImage_MetadataEntry.encode({ key: key as any, value }, writer.uint32(90).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VLMImage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVLMImage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.filePath = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.encoded = reader.bytes();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.rawRgb = reader.bytes();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.base64 = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.width = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.height = reader.int32();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.format = reader.int32() as any;
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.mediaType = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.sizeBytes = longToNumber(reader.int64());
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          const entry11 = VLMImage_MetadataEntry.decode(reader, reader.uint32());
          if (entry11.value !== undefined) {
            message.metadata[entry11.key] = entry11.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VLMImage {
    return {
      filePath: isSet(object.filePath)
        ? globalThis.String(object.filePath)
        : isSet(object.file_path)
        ? globalThis.String(object.file_path)
        : undefined,
      encoded: isSet(object.encoded) ? bytesFromBase64(object.encoded) : undefined,
      rawRgb: isSet(object.rawRgb)
        ? bytesFromBase64(object.rawRgb)
        : isSet(object.raw_rgb)
        ? bytesFromBase64(object.raw_rgb)
        : undefined,
      base64: isSet(object.base64) ? globalThis.String(object.base64) : undefined,
      width: isSet(object.width) ? globalThis.Number(object.width) : 0,
      height: isSet(object.height) ? globalThis.Number(object.height) : 0,
      format: isSet(object.format) ? vLMImageFormatFromJSON(object.format) : 0,
      mediaType: isSet(object.mediaType)
        ? globalThis.String(object.mediaType)
        : isSet(object.media_type)
        ? globalThis.String(object.media_type)
        : undefined,
      name: isSet(object.name) ? globalThis.String(object.name) : undefined,
      sizeBytes: isSet(object.sizeBytes)
        ? globalThis.Number(object.sizeBytes)
        : isSet(object.size_bytes)
        ? globalThis.Number(object.size_bytes)
        : 0,
      metadata: isObject(object.metadata)
        ? (globalThis.Object.entries(object.metadata) as [string, any][]).reduce(
          (acc: { [key: string]: string }, [key, value]: [string, any]) => {
            acc[key] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : {},
    };
  },

  toJSON(message: VLMImage): unknown {
    const obj: any = {};
    if (message.filePath !== undefined) {
      obj.filePath = message.filePath;
    }
    if (message.encoded !== undefined) {
      obj.encoded = base64FromBytes(message.encoded);
    }
    if (message.rawRgb !== undefined) {
      obj.rawRgb = base64FromBytes(message.rawRgb);
    }
    if (message.base64 !== undefined) {
      obj.base64 = message.base64;
    }
    if (message.width !== 0) {
      obj.width = Math.round(message.width);
    }
    if (message.height !== 0) {
      obj.height = Math.round(message.height);
    }
    if (message.format !== 0) {
      obj.format = vLMImageFormatToJSON(message.format);
    }
    if (message.mediaType !== undefined) {
      obj.mediaType = message.mediaType;
    }
    if (message.name !== undefined) {
      obj.name = message.name;
    }
    if (message.sizeBytes !== 0) {
      obj.sizeBytes = Math.round(message.sizeBytes);
    }
    if (message.metadata) {
      const entries = globalThis.Object.entries(message.metadata) as [string, string][];
      if (entries.length > 0) {
        obj.metadata = {};
        entries.forEach(([k, v]) => {
          obj.metadata[k] = v;
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VLMImage>, I>>(base?: I): VLMImage {
    return VLMImage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VLMImage>, I>>(object: I): VLMImage {
    const message = createBaseVLMImage();
    message.filePath = object.filePath ?? undefined;
    message.encoded = object.encoded ?? undefined;
    message.rawRgb = object.rawRgb ?? undefined;
    message.base64 = object.base64 ?? undefined;
    message.width = object.width ?? 0;
    message.height = object.height ?? 0;
    message.format = object.format ?? 0;
    message.mediaType = object.mediaType ?? undefined;
    message.name = object.name ?? undefined;
    message.sizeBytes = object.sizeBytes ?? 0;
    message.metadata = (globalThis.Object.entries(object.metadata ?? {}) as [string, string][]).reduce(
      (acc: { [key: string]: string }, [key, value]: [string, string]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    return message;
  },
};

function createBaseVLMImage_MetadataEntry(): VLMImage_MetadataEntry {
  return { key: "", value: "" };
}

export const VLMImage_MetadataEntry: MessageFns<VLMImage_MetadataEntry> = {
  encode(message: VLMImage_MetadataEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VLMImage_MetadataEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVLMImage_MetadataEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VLMImage_MetadataEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: VLMImage_MetadataEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VLMImage_MetadataEntry>, I>>(base?: I): VLMImage_MetadataEntry {
    return VLMImage_MetadataEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VLMImage_MetadataEntry>, I>>(object: I): VLMImage_MetadataEntry {
    const message = createBaseVLMImage_MetadataEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseVLMConfiguration(): VLMConfiguration {
  return {
    modelId: "",
    maxImageSizePx: 0,
    maxTokens: 0,
    contextLength: 0,
    temperature: 0,
    systemPrompt: undefined,
    streamingEnabled: false,
    preferredFramework: undefined,
  };
}

export const VLMConfiguration: MessageFns<VLMConfiguration> = {
  encode(message: VLMConfiguration, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.modelId !== "") {
      writer.uint32(10).string(message.modelId);
    }
    if (message.maxImageSizePx !== 0) {
      writer.uint32(16).int32(message.maxImageSizePx);
    }
    if (message.maxTokens !== 0) {
      writer.uint32(24).int32(message.maxTokens);
    }
    if (message.contextLength !== 0) {
      writer.uint32(32).int32(message.contextLength);
    }
    if (message.temperature !== 0) {
      writer.uint32(45).float(message.temperature);
    }
    if (message.systemPrompt !== undefined) {
      writer.uint32(50).string(message.systemPrompt);
    }
    if (message.streamingEnabled !== false) {
      writer.uint32(56).bool(message.streamingEnabled);
    }
    if (message.preferredFramework !== undefined) {
      writer.uint32(64).int32(message.preferredFramework);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VLMConfiguration {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVLMConfiguration();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.modelId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.maxImageSizePx = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.maxTokens = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.contextLength = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 45) {
            break;
          }

          message.temperature = reader.float();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.systemPrompt = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.streamingEnabled = reader.bool();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.preferredFramework = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VLMConfiguration {
    return {
      modelId: isSet(object.modelId)
        ? globalThis.String(object.modelId)
        : isSet(object.model_id)
        ? globalThis.String(object.model_id)
        : "",
      maxImageSizePx: isSet(object.maxImageSizePx)
        ? globalThis.Number(object.maxImageSizePx)
        : isSet(object.max_image_size_px)
        ? globalThis.Number(object.max_image_size_px)
        : 0,
      maxTokens: isSet(object.maxTokens)
        ? globalThis.Number(object.maxTokens)
        : isSet(object.max_tokens)
        ? globalThis.Number(object.max_tokens)
        : 0,
      contextLength: isSet(object.contextLength)
        ? globalThis.Number(object.contextLength)
        : isSet(object.context_length)
        ? globalThis.Number(object.context_length)
        : 0,
      temperature: isSet(object.temperature) ? globalThis.Number(object.temperature) : 0,
      systemPrompt: isSet(object.systemPrompt)
        ? globalThis.String(object.systemPrompt)
        : isSet(object.system_prompt)
        ? globalThis.String(object.system_prompt)
        : undefined,
      streamingEnabled: isSet(object.streamingEnabled)
        ? globalThis.Boolean(object.streamingEnabled)
        : isSet(object.streaming_enabled)
        ? globalThis.Boolean(object.streaming_enabled)
        : false,
      preferredFramework: isSet(object.preferredFramework)
        ? inferenceFrameworkFromJSON(object.preferredFramework)
        : isSet(object.preferred_framework)
        ? inferenceFrameworkFromJSON(object.preferred_framework)
        : undefined,
    };
  },

  toJSON(message: VLMConfiguration): unknown {
    const obj: any = {};
    if (message.modelId !== "") {
      obj.modelId = message.modelId;
    }
    if (message.maxImageSizePx !== 0) {
      obj.maxImageSizePx = Math.round(message.maxImageSizePx);
    }
    if (message.maxTokens !== 0) {
      obj.maxTokens = Math.round(message.maxTokens);
    }
    if (message.contextLength !== 0) {
      obj.contextLength = Math.round(message.contextLength);
    }
    if (message.temperature !== 0) {
      obj.temperature = message.temperature;
    }
    if (message.systemPrompt !== undefined) {
      obj.systemPrompt = message.systemPrompt;
    }
    if (message.streamingEnabled !== false) {
      obj.streamingEnabled = message.streamingEnabled;
    }
    if (message.preferredFramework !== undefined) {
      obj.preferredFramework = inferenceFrameworkToJSON(message.preferredFramework);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VLMConfiguration>, I>>(base?: I): VLMConfiguration {
    return VLMConfiguration.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VLMConfiguration>, I>>(object: I): VLMConfiguration {
    const message = createBaseVLMConfiguration();
    message.modelId = object.modelId ?? "";
    message.maxImageSizePx = object.maxImageSizePx ?? 0;
    message.maxTokens = object.maxTokens ?? 0;
    message.contextLength = object.contextLength ?? 0;
    message.temperature = object.temperature ?? 0;
    message.systemPrompt = object.systemPrompt ?? undefined;
    message.streamingEnabled = object.streamingEnabled ?? false;
    message.preferredFramework = object.preferredFramework ?? undefined;
    return message;
  },
};

function createBaseVLMGenerationOptions(): VLMGenerationOptions {
  return {
    prompt: "",
    maxTokens: 0,
    temperature: 0,
    topP: 0,
    topK: 0,
    stopSequences: [],
    streamingEnabled: false,
    systemPrompt: undefined,
    maxImageSize: 0,
    nThreads: 0,
    useGpu: false,
    modelFamily: 0,
    customChatTemplate: undefined,
    imageMarkerOverride: undefined,
    seed: 0,
    repetitionPenalty: 0,
    minP: 0,
    emitImageEmbeddings: false,
  };
}

export const VLMGenerationOptions: MessageFns<VLMGenerationOptions> = {
  encode(message: VLMGenerationOptions, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.prompt !== "") {
      writer.uint32(10).string(message.prompt);
    }
    if (message.maxTokens !== 0) {
      writer.uint32(16).int32(message.maxTokens);
    }
    if (message.temperature !== 0) {
      writer.uint32(29).float(message.temperature);
    }
    if (message.topP !== 0) {
      writer.uint32(37).float(message.topP);
    }
    if (message.topK !== 0) {
      writer.uint32(40).int32(message.topK);
    }
    for (const v of message.stopSequences) {
      writer.uint32(50).string(v!);
    }
    if (message.streamingEnabled !== false) {
      writer.uint32(56).bool(message.streamingEnabled);
    }
    if (message.systemPrompt !== undefined) {
      writer.uint32(66).string(message.systemPrompt);
    }
    if (message.maxImageSize !== 0) {
      writer.uint32(72).int32(message.maxImageSize);
    }
    if (message.nThreads !== 0) {
      writer.uint32(80).int32(message.nThreads);
    }
    if (message.useGpu !== false) {
      writer.uint32(88).bool(message.useGpu);
    }
    if (message.modelFamily !== 0) {
      writer.uint32(96).int32(message.modelFamily);
    }
    if (message.customChatTemplate !== undefined) {
      VLMChatTemplate.encode(message.customChatTemplate, writer.uint32(106).fork()).join();
    }
    if (message.imageMarkerOverride !== undefined) {
      writer.uint32(114).string(message.imageMarkerOverride);
    }
    if (message.seed !== 0) {
      writer.uint32(120).int64(message.seed);
    }
    if (message.repetitionPenalty !== 0) {
      writer.uint32(133).float(message.repetitionPenalty);
    }
    if (message.minP !== 0) {
      writer.uint32(141).float(message.minP);
    }
    if (message.emitImageEmbeddings !== false) {
      writer.uint32(144).bool(message.emitImageEmbeddings);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VLMGenerationOptions {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVLMGenerationOptions();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.prompt = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.maxTokens = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 29) {
            break;
          }

          message.temperature = reader.float();
          continue;
        }
        case 4: {
          if (tag !== 37) {
            break;
          }

          message.topP = reader.float();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.topK = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.stopSequences.push(reader.string());
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.streamingEnabled = reader.bool();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.systemPrompt = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.maxImageSize = reader.int32();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.nThreads = reader.int32();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.useGpu = reader.bool();
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.modelFamily = reader.int32() as any;
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.customChatTemplate = VLMChatTemplate.decode(reader, reader.uint32());
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          message.imageMarkerOverride = reader.string();
          continue;
        }
        case 15: {
          if (tag !== 120) {
            break;
          }

          message.seed = longToNumber(reader.int64());
          continue;
        }
        case 16: {
          if (tag !== 133) {
            break;
          }

          message.repetitionPenalty = reader.float();
          continue;
        }
        case 17: {
          if (tag !== 141) {
            break;
          }

          message.minP = reader.float();
          continue;
        }
        case 18: {
          if (tag !== 144) {
            break;
          }

          message.emitImageEmbeddings = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VLMGenerationOptions {
    return {
      prompt: isSet(object.prompt) ? globalThis.String(object.prompt) : "",
      maxTokens: isSet(object.maxTokens)
        ? globalThis.Number(object.maxTokens)
        : isSet(object.max_tokens)
        ? globalThis.Number(object.max_tokens)
        : 0,
      temperature: isSet(object.temperature) ? globalThis.Number(object.temperature) : 0,
      topP: isSet(object.topP)
        ? globalThis.Number(object.topP)
        : isSet(object.top_p)
        ? globalThis.Number(object.top_p)
        : 0,
      topK: isSet(object.topK)
        ? globalThis.Number(object.topK)
        : isSet(object.top_k)
        ? globalThis.Number(object.top_k)
        : 0,
      stopSequences: globalThis.Array.isArray(object?.stopSequences)
        ? object.stopSequences.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.stop_sequences)
        ? object.stop_sequences.map((e: any) => globalThis.String(e))
        : [],
      streamingEnabled: isSet(object.streamingEnabled)
        ? globalThis.Boolean(object.streamingEnabled)
        : isSet(object.streaming_enabled)
        ? globalThis.Boolean(object.streaming_enabled)
        : false,
      systemPrompt: isSet(object.systemPrompt)
        ? globalThis.String(object.systemPrompt)
        : isSet(object.system_prompt)
        ? globalThis.String(object.system_prompt)
        : undefined,
      maxImageSize: isSet(object.maxImageSize)
        ? globalThis.Number(object.maxImageSize)
        : isSet(object.max_image_size)
        ? globalThis.Number(object.max_image_size)
        : 0,
      nThreads: isSet(object.nThreads)
        ? globalThis.Number(object.nThreads)
        : isSet(object.n_threads)
        ? globalThis.Number(object.n_threads)
        : 0,
      useGpu: isSet(object.useGpu)
        ? globalThis.Boolean(object.useGpu)
        : isSet(object.use_gpu)
        ? globalThis.Boolean(object.use_gpu)
        : false,
      modelFamily: isSet(object.modelFamily)
        ? vLMModelFamilyFromJSON(object.modelFamily)
        : isSet(object.model_family)
        ? vLMModelFamilyFromJSON(object.model_family)
        : 0,
      customChatTemplate: isSet(object.customChatTemplate)
        ? VLMChatTemplate.fromJSON(object.customChatTemplate)
        : isSet(object.custom_chat_template)
        ? VLMChatTemplate.fromJSON(object.custom_chat_template)
        : undefined,
      imageMarkerOverride: isSet(object.imageMarkerOverride)
        ? globalThis.String(object.imageMarkerOverride)
        : isSet(object.image_marker_override)
        ? globalThis.String(object.image_marker_override)
        : undefined,
      seed: isSet(object.seed) ? globalThis.Number(object.seed) : 0,
      repetitionPenalty: isSet(object.repetitionPenalty)
        ? globalThis.Number(object.repetitionPenalty)
        : isSet(object.repetition_penalty)
        ? globalThis.Number(object.repetition_penalty)
        : 0,
      minP: isSet(object.minP)
        ? globalThis.Number(object.minP)
        : isSet(object.min_p)
        ? globalThis.Number(object.min_p)
        : 0,
      emitImageEmbeddings: isSet(object.emitImageEmbeddings)
        ? globalThis.Boolean(object.emitImageEmbeddings)
        : isSet(object.emit_image_embeddings)
        ? globalThis.Boolean(object.emit_image_embeddings)
        : false,
    };
  },

  toJSON(message: VLMGenerationOptions): unknown {
    const obj: any = {};
    if (message.prompt !== "") {
      obj.prompt = message.prompt;
    }
    if (message.maxTokens !== 0) {
      obj.maxTokens = Math.round(message.maxTokens);
    }
    if (message.temperature !== 0) {
      obj.temperature = message.temperature;
    }
    if (message.topP !== 0) {
      obj.topP = message.topP;
    }
    if (message.topK !== 0) {
      obj.topK = Math.round(message.topK);
    }
    if (message.stopSequences?.length) {
      obj.stopSequences = message.stopSequences;
    }
    if (message.streamingEnabled !== false) {
      obj.streamingEnabled = message.streamingEnabled;
    }
    if (message.systemPrompt !== undefined) {
      obj.systemPrompt = message.systemPrompt;
    }
    if (message.maxImageSize !== 0) {
      obj.maxImageSize = Math.round(message.maxImageSize);
    }
    if (message.nThreads !== 0) {
      obj.nThreads = Math.round(message.nThreads);
    }
    if (message.useGpu !== false) {
      obj.useGpu = message.useGpu;
    }
    if (message.modelFamily !== 0) {
      obj.modelFamily = vLMModelFamilyToJSON(message.modelFamily);
    }
    if (message.customChatTemplate !== undefined) {
      obj.customChatTemplate = VLMChatTemplate.toJSON(message.customChatTemplate);
    }
    if (message.imageMarkerOverride !== undefined) {
      obj.imageMarkerOverride = message.imageMarkerOverride;
    }
    if (message.seed !== 0) {
      obj.seed = Math.round(message.seed);
    }
    if (message.repetitionPenalty !== 0) {
      obj.repetitionPenalty = message.repetitionPenalty;
    }
    if (message.minP !== 0) {
      obj.minP = message.minP;
    }
    if (message.emitImageEmbeddings !== false) {
      obj.emitImageEmbeddings = message.emitImageEmbeddings;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VLMGenerationOptions>, I>>(base?: I): VLMGenerationOptions {
    return VLMGenerationOptions.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VLMGenerationOptions>, I>>(object: I): VLMGenerationOptions {
    const message = createBaseVLMGenerationOptions();
    message.prompt = object.prompt ?? "";
    message.maxTokens = object.maxTokens ?? 0;
    message.temperature = object.temperature ?? 0;
    message.topP = object.topP ?? 0;
    message.topK = object.topK ?? 0;
    message.stopSequences = object.stopSequences?.map((e) => e) || [];
    message.streamingEnabled = object.streamingEnabled ?? false;
    message.systemPrompt = object.systemPrompt ?? undefined;
    message.maxImageSize = object.maxImageSize ?? 0;
    message.nThreads = object.nThreads ?? 0;
    message.useGpu = object.useGpu ?? false;
    message.modelFamily = object.modelFamily ?? 0;
    message.customChatTemplate = (object.customChatTemplate !== undefined && object.customChatTemplate !== null)
      ? VLMChatTemplate.fromPartial(object.customChatTemplate)
      : undefined;
    message.imageMarkerOverride = object.imageMarkerOverride ?? undefined;
    message.seed = object.seed ?? 0;
    message.repetitionPenalty = object.repetitionPenalty ?? 0;
    message.minP = object.minP ?? 0;
    message.emitImageEmbeddings = object.emitImageEmbeddings ?? false;
    return message;
  },
};

function createBaseVLMGenerationRequest(): VLMGenerationRequest {
  return { requestId: "", images: [], options: undefined, modelId: undefined, metadata: {} };
}

export const VLMGenerationRequest: MessageFns<VLMGenerationRequest> = {
  encode(message: VLMGenerationRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.requestId !== "") {
      writer.uint32(10).string(message.requestId);
    }
    for (const v of message.images) {
      VLMImage.encode(v!, writer.uint32(18).fork()).join();
    }
    if (message.options !== undefined) {
      VLMGenerationOptions.encode(message.options, writer.uint32(26).fork()).join();
    }
    if (message.modelId !== undefined) {
      writer.uint32(34).string(message.modelId);
    }
    globalThis.Object.entries(message.metadata).forEach(([key, value]: [string, string]) => {
      VLMGenerationRequest_MetadataEntry.encode({ key: key as any, value }, writer.uint32(42).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VLMGenerationRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVLMGenerationRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.images.push(VLMImage.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.options = VLMGenerationOptions.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.modelId = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          const entry5 = VLMGenerationRequest_MetadataEntry.decode(reader, reader.uint32());
          if (entry5.value !== undefined) {
            message.metadata[entry5.key] = entry5.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VLMGenerationRequest {
    return {
      requestId: isSet(object.requestId)
        ? globalThis.String(object.requestId)
        : isSet(object.request_id)
        ? globalThis.String(object.request_id)
        : "",
      images: globalThis.Array.isArray(object?.images) ? object.images.map((e: any) => VLMImage.fromJSON(e)) : [],
      options: isSet(object.options) ? VLMGenerationOptions.fromJSON(object.options) : undefined,
      modelId: isSet(object.modelId)
        ? globalThis.String(object.modelId)
        : isSet(object.model_id)
        ? globalThis.String(object.model_id)
        : undefined,
      metadata: isObject(object.metadata)
        ? (globalThis.Object.entries(object.metadata) as [string, any][]).reduce(
          (acc: { [key: string]: string }, [key, value]: [string, any]) => {
            acc[key] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : {},
    };
  },

  toJSON(message: VLMGenerationRequest): unknown {
    const obj: any = {};
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.images?.length) {
      obj.images = message.images.map((e) => VLMImage.toJSON(e));
    }
    if (message.options !== undefined) {
      obj.options = VLMGenerationOptions.toJSON(message.options);
    }
    if (message.modelId !== undefined) {
      obj.modelId = message.modelId;
    }
    if (message.metadata) {
      const entries = globalThis.Object.entries(message.metadata) as [string, string][];
      if (entries.length > 0) {
        obj.metadata = {};
        entries.forEach(([k, v]) => {
          obj.metadata[k] = v;
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VLMGenerationRequest>, I>>(base?: I): VLMGenerationRequest {
    return VLMGenerationRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VLMGenerationRequest>, I>>(object: I): VLMGenerationRequest {
    const message = createBaseVLMGenerationRequest();
    message.requestId = object.requestId ?? "";
    message.images = object.images?.map((e) => VLMImage.fromPartial(e)) || [];
    message.options = (object.options !== undefined && object.options !== null)
      ? VLMGenerationOptions.fromPartial(object.options)
      : undefined;
    message.modelId = object.modelId ?? undefined;
    message.metadata = (globalThis.Object.entries(object.metadata ?? {}) as [string, string][]).reduce(
      (acc: { [key: string]: string }, [key, value]: [string, string]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    return message;
  },
};

function createBaseVLMGenerationRequest_MetadataEntry(): VLMGenerationRequest_MetadataEntry {
  return { key: "", value: "" };
}

export const VLMGenerationRequest_MetadataEntry: MessageFns<VLMGenerationRequest_MetadataEntry> = {
  encode(message: VLMGenerationRequest_MetadataEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VLMGenerationRequest_MetadataEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVLMGenerationRequest_MetadataEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VLMGenerationRequest_MetadataEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: VLMGenerationRequest_MetadataEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VLMGenerationRequest_MetadataEntry>, I>>(
    base?: I,
  ): VLMGenerationRequest_MetadataEntry {
    return VLMGenerationRequest_MetadataEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VLMGenerationRequest_MetadataEntry>, I>>(
    object: I,
  ): VLMGenerationRequest_MetadataEntry {
    const message = createBaseVLMGenerationRequest_MetadataEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseVLMResult(): VLMResult {
  return {
    text: "",
    promptTokens: 0,
    completionTokens: 0,
    totalTokens: 0,
    processingTimeMs: 0,
    tokensPerSecond: 0,
    imageTokens: 0,
    timeToFirstTokenMs: 0,
    imageEncodeTimeMs: 0,
    hardwareUsed: undefined,
    errorMessage: undefined,
    errorCode: 0,
    finishReason: "",
    imagesProcessed: 0,
  };
}

export const VLMResult: MessageFns<VLMResult> = {
  encode(message: VLMResult, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.text !== "") {
      writer.uint32(10).string(message.text);
    }
    if (message.promptTokens !== 0) {
      writer.uint32(16).int32(message.promptTokens);
    }
    if (message.completionTokens !== 0) {
      writer.uint32(24).int32(message.completionTokens);
    }
    if (message.totalTokens !== 0) {
      writer.uint32(32).int64(message.totalTokens);
    }
    if (message.processingTimeMs !== 0) {
      writer.uint32(40).int64(message.processingTimeMs);
    }
    if (message.tokensPerSecond !== 0) {
      writer.uint32(53).float(message.tokensPerSecond);
    }
    if (message.imageTokens !== 0) {
      writer.uint32(56).int32(message.imageTokens);
    }
    if (message.timeToFirstTokenMs !== 0) {
      writer.uint32(64).int64(message.timeToFirstTokenMs);
    }
    if (message.imageEncodeTimeMs !== 0) {
      writer.uint32(72).int64(message.imageEncodeTimeMs);
    }
    if (message.hardwareUsed !== undefined) {
      writer.uint32(82).string(message.hardwareUsed);
    }
    if (message.errorMessage !== undefined) {
      writer.uint32(90).string(message.errorMessage);
    }
    if (message.errorCode !== 0) {
      writer.uint32(96).int32(message.errorCode);
    }
    if (message.finishReason !== "") {
      writer.uint32(106).string(message.finishReason);
    }
    if (message.imagesProcessed !== 0) {
      writer.uint32(112).int32(message.imagesProcessed);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VLMResult {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVLMResult();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.text = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.promptTokens = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.completionTokens = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.totalTokens = longToNumber(reader.int64());
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.processingTimeMs = longToNumber(reader.int64());
          continue;
        }
        case 6: {
          if (tag !== 53) {
            break;
          }

          message.tokensPerSecond = reader.float();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.imageTokens = reader.int32();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.timeToFirstTokenMs = longToNumber(reader.int64());
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.imageEncodeTimeMs = longToNumber(reader.int64());
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.hardwareUsed = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.errorMessage = reader.string();
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.errorCode = reader.int32();
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.finishReason = reader.string();
          continue;
        }
        case 14: {
          if (tag !== 112) {
            break;
          }

          message.imagesProcessed = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VLMResult {
    return {
      text: isSet(object.text) ? globalThis.String(object.text) : "",
      promptTokens: isSet(object.promptTokens)
        ? globalThis.Number(object.promptTokens)
        : isSet(object.prompt_tokens)
        ? globalThis.Number(object.prompt_tokens)
        : 0,
      completionTokens: isSet(object.completionTokens)
        ? globalThis.Number(object.completionTokens)
        : isSet(object.completion_tokens)
        ? globalThis.Number(object.completion_tokens)
        : 0,
      totalTokens: isSet(object.totalTokens)
        ? globalThis.Number(object.totalTokens)
        : isSet(object.total_tokens)
        ? globalThis.Number(object.total_tokens)
        : 0,
      processingTimeMs: isSet(object.processingTimeMs)
        ? globalThis.Number(object.processingTimeMs)
        : isSet(object.processing_time_ms)
        ? globalThis.Number(object.processing_time_ms)
        : 0,
      tokensPerSecond: isSet(object.tokensPerSecond)
        ? globalThis.Number(object.tokensPerSecond)
        : isSet(object.tokens_per_second)
        ? globalThis.Number(object.tokens_per_second)
        : 0,
      imageTokens: isSet(object.imageTokens)
        ? globalThis.Number(object.imageTokens)
        : isSet(object.image_tokens)
        ? globalThis.Number(object.image_tokens)
        : 0,
      timeToFirstTokenMs: isSet(object.timeToFirstTokenMs)
        ? globalThis.Number(object.timeToFirstTokenMs)
        : isSet(object.time_to_first_token_ms)
        ? globalThis.Number(object.time_to_first_token_ms)
        : 0,
      imageEncodeTimeMs: isSet(object.imageEncodeTimeMs)
        ? globalThis.Number(object.imageEncodeTimeMs)
        : isSet(object.image_encode_time_ms)
        ? globalThis.Number(object.image_encode_time_ms)
        : 0,
      hardwareUsed: isSet(object.hardwareUsed)
        ? globalThis.String(object.hardwareUsed)
        : isSet(object.hardware_used)
        ? globalThis.String(object.hardware_used)
        : undefined,
      errorMessage: isSet(object.errorMessage)
        ? globalThis.String(object.errorMessage)
        : isSet(object.error_message)
        ? globalThis.String(object.error_message)
        : undefined,
      errorCode: isSet(object.errorCode)
        ? globalThis.Number(object.errorCode)
        : isSet(object.error_code)
        ? globalThis.Number(object.error_code)
        : 0,
      finishReason: isSet(object.finishReason)
        ? globalThis.String(object.finishReason)
        : isSet(object.finish_reason)
        ? globalThis.String(object.finish_reason)
        : "",
      imagesProcessed: isSet(object.imagesProcessed)
        ? globalThis.Number(object.imagesProcessed)
        : isSet(object.images_processed)
        ? globalThis.Number(object.images_processed)
        : 0,
    };
  },

  toJSON(message: VLMResult): unknown {
    const obj: any = {};
    if (message.text !== "") {
      obj.text = message.text;
    }
    if (message.promptTokens !== 0) {
      obj.promptTokens = Math.round(message.promptTokens);
    }
    if (message.completionTokens !== 0) {
      obj.completionTokens = Math.round(message.completionTokens);
    }
    if (message.totalTokens !== 0) {
      obj.totalTokens = Math.round(message.totalTokens);
    }
    if (message.processingTimeMs !== 0) {
      obj.processingTimeMs = Math.round(message.processingTimeMs);
    }
    if (message.tokensPerSecond !== 0) {
      obj.tokensPerSecond = message.tokensPerSecond;
    }
    if (message.imageTokens !== 0) {
      obj.imageTokens = Math.round(message.imageTokens);
    }
    if (message.timeToFirstTokenMs !== 0) {
      obj.timeToFirstTokenMs = Math.round(message.timeToFirstTokenMs);
    }
    if (message.imageEncodeTimeMs !== 0) {
      obj.imageEncodeTimeMs = Math.round(message.imageEncodeTimeMs);
    }
    if (message.hardwareUsed !== undefined) {
      obj.hardwareUsed = message.hardwareUsed;
    }
    if (message.errorMessage !== undefined) {
      obj.errorMessage = message.errorMessage;
    }
    if (message.errorCode !== 0) {
      obj.errorCode = Math.round(message.errorCode);
    }
    if (message.finishReason !== "") {
      obj.finishReason = message.finishReason;
    }
    if (message.imagesProcessed !== 0) {
      obj.imagesProcessed = Math.round(message.imagesProcessed);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VLMResult>, I>>(base?: I): VLMResult {
    return VLMResult.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VLMResult>, I>>(object: I): VLMResult {
    const message = createBaseVLMResult();
    message.text = object.text ?? "";
    message.promptTokens = object.promptTokens ?? 0;
    message.completionTokens = object.completionTokens ?? 0;
    message.totalTokens = object.totalTokens ?? 0;
    message.processingTimeMs = object.processingTimeMs ?? 0;
    message.tokensPerSecond = object.tokensPerSecond ?? 0;
    message.imageTokens = object.imageTokens ?? 0;
    message.timeToFirstTokenMs = object.timeToFirstTokenMs ?? 0;
    message.imageEncodeTimeMs = object.imageEncodeTimeMs ?? 0;
    message.hardwareUsed = object.hardwareUsed ?? undefined;
    message.errorMessage = object.errorMessage ?? undefined;
    message.errorCode = object.errorCode ?? 0;
    message.finishReason = object.finishReason ?? "";
    message.imagesProcessed = object.imagesProcessed ?? 0;
    return message;
  },
};

function createBaseVLMStreamEvent(): VLMStreamEvent {
  return {
    seq: 0,
    timestampUs: 0,
    requestId: "",
    kind: 0,
    token: "",
    tokenIndex: 0,
    isFinal: false,
    tokensPerSecond: 0,
    result: undefined,
    errorMessage: undefined,
    errorCode: 0,
  };
}

export const VLMStreamEvent: MessageFns<VLMStreamEvent> = {
  encode(message: VLMStreamEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.seq !== 0) {
      writer.uint32(8).uint64(message.seq);
    }
    if (message.timestampUs !== 0) {
      writer.uint32(16).int64(message.timestampUs);
    }
    if (message.requestId !== "") {
      writer.uint32(26).string(message.requestId);
    }
    if (message.kind !== 0) {
      writer.uint32(32).int32(message.kind);
    }
    if (message.token !== "") {
      writer.uint32(42).string(message.token);
    }
    if (message.tokenIndex !== 0) {
      writer.uint32(48).int32(message.tokenIndex);
    }
    if (message.isFinal !== false) {
      writer.uint32(56).bool(message.isFinal);
    }
    if (message.tokensPerSecond !== 0) {
      writer.uint32(69).float(message.tokensPerSecond);
    }
    if (message.result !== undefined) {
      VLMResult.encode(message.result, writer.uint32(74).fork()).join();
    }
    if (message.errorMessage !== undefined) {
      writer.uint32(82).string(message.errorMessage);
    }
    if (message.errorCode !== 0) {
      writer.uint32(88).int32(message.errorCode);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VLMStreamEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVLMStreamEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.seq = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.timestampUs = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.kind = reader.int32() as any;
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.token = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.tokenIndex = reader.int32();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.isFinal = reader.bool();
          continue;
        }
        case 8: {
          if (tag !== 69) {
            break;
          }

          message.tokensPerSecond = reader.float();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.result = VLMResult.decode(reader, reader.uint32());
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.errorMessage = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.errorCode = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VLMStreamEvent {
    return {
      seq: isSet(object.seq) ? globalThis.Number(object.seq) : 0,
      timestampUs: isSet(object.timestampUs)
        ? globalThis.Number(object.timestampUs)
        : isSet(object.timestamp_us)
        ? globalThis.Number(object.timestamp_us)
        : 0,
      requestId: isSet(object.requestId)
        ? globalThis.String(object.requestId)
        : isSet(object.request_id)
        ? globalThis.String(object.request_id)
        : "",
      kind: isSet(object.kind) ? vLMStreamEventKindFromJSON(object.kind) : 0,
      token: isSet(object.token) ? globalThis.String(object.token) : "",
      tokenIndex: isSet(object.tokenIndex)
        ? globalThis.Number(object.tokenIndex)
        : isSet(object.token_index)
        ? globalThis.Number(object.token_index)
        : 0,
      isFinal: isSet(object.isFinal)
        ? globalThis.Boolean(object.isFinal)
        : isSet(object.is_final)
        ? globalThis.Boolean(object.is_final)
        : false,
      tokensPerSecond: isSet(object.tokensPerSecond)
        ? globalThis.Number(object.tokensPerSecond)
        : isSet(object.tokens_per_second)
        ? globalThis.Number(object.tokens_per_second)
        : 0,
      result: isSet(object.result) ? VLMResult.fromJSON(object.result) : undefined,
      errorMessage: isSet(object.errorMessage)
        ? globalThis.String(object.errorMessage)
        : isSet(object.error_message)
        ? globalThis.String(object.error_message)
        : undefined,
      errorCode: isSet(object.errorCode)
        ? globalThis.Number(object.errorCode)
        : isSet(object.error_code)
        ? globalThis.Number(object.error_code)
        : 0,
    };
  },

  toJSON(message: VLMStreamEvent): unknown {
    const obj: any = {};
    if (message.seq !== 0) {
      obj.seq = Math.round(message.seq);
    }
    if (message.timestampUs !== 0) {
      obj.timestampUs = Math.round(message.timestampUs);
    }
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.kind !== 0) {
      obj.kind = vLMStreamEventKindToJSON(message.kind);
    }
    if (message.token !== "") {
      obj.token = message.token;
    }
    if (message.tokenIndex !== 0) {
      obj.tokenIndex = Math.round(message.tokenIndex);
    }
    if (message.isFinal !== false) {
      obj.isFinal = message.isFinal;
    }
    if (message.tokensPerSecond !== 0) {
      obj.tokensPerSecond = message.tokensPerSecond;
    }
    if (message.result !== undefined) {
      obj.result = VLMResult.toJSON(message.result);
    }
    if (message.errorMessage !== undefined) {
      obj.errorMessage = message.errorMessage;
    }
    if (message.errorCode !== 0) {
      obj.errorCode = Math.round(message.errorCode);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VLMStreamEvent>, I>>(base?: I): VLMStreamEvent {
    return VLMStreamEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VLMStreamEvent>, I>>(object: I): VLMStreamEvent {
    const message = createBaseVLMStreamEvent();
    message.seq = object.seq ?? 0;
    message.timestampUs = object.timestampUs ?? 0;
    message.requestId = object.requestId ?? "";
    message.kind = object.kind ?? 0;
    message.token = object.token ?? "";
    message.tokenIndex = object.tokenIndex ?? 0;
    message.isFinal = object.isFinal ?? false;
    message.tokensPerSecond = object.tokensPerSecond ?? 0;
    message.result = (object.result !== undefined && object.result !== null)
      ? VLMResult.fromPartial(object.result)
      : undefined;
    message.errorMessage = object.errorMessage ?? undefined;
    message.errorCode = object.errorCode ?? 0;
    return message;
  },
};

function createBaseVLMServiceState(): VLMServiceState {
  return {
    isReady: false,
    currentModel: undefined,
    contextLength: 0,
    supportsStreaming: false,
    supportsMultipleImages: false,
    visionEncoderType: undefined,
    errorMessage: undefined,
    errorCode: 0,
  };
}

export const VLMServiceState: MessageFns<VLMServiceState> = {
  encode(message: VLMServiceState, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.isReady !== false) {
      writer.uint32(8).bool(message.isReady);
    }
    if (message.currentModel !== undefined) {
      writer.uint32(18).string(message.currentModel);
    }
    if (message.contextLength !== 0) {
      writer.uint32(24).int32(message.contextLength);
    }
    if (message.supportsStreaming !== false) {
      writer.uint32(32).bool(message.supportsStreaming);
    }
    if (message.supportsMultipleImages !== false) {
      writer.uint32(40).bool(message.supportsMultipleImages);
    }
    if (message.visionEncoderType !== undefined) {
      writer.uint32(50).string(message.visionEncoderType);
    }
    if (message.errorMessage !== undefined) {
      writer.uint32(58).string(message.errorMessage);
    }
    if (message.errorCode !== 0) {
      writer.uint32(64).int32(message.errorCode);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VLMServiceState {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVLMServiceState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.isReady = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.currentModel = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.contextLength = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.supportsStreaming = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.supportsMultipleImages = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.visionEncoderType = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.errorMessage = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.errorCode = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VLMServiceState {
    return {
      isReady: isSet(object.isReady)
        ? globalThis.Boolean(object.isReady)
        : isSet(object.is_ready)
        ? globalThis.Boolean(object.is_ready)
        : false,
      currentModel: isSet(object.currentModel)
        ? globalThis.String(object.currentModel)
        : isSet(object.current_model)
        ? globalThis.String(object.current_model)
        : undefined,
      contextLength: isSet(object.contextLength)
        ? globalThis.Number(object.contextLength)
        : isSet(object.context_length)
        ? globalThis.Number(object.context_length)
        : 0,
      supportsStreaming: isSet(object.supportsStreaming)
        ? globalThis.Boolean(object.supportsStreaming)
        : isSet(object.supports_streaming)
        ? globalThis.Boolean(object.supports_streaming)
        : false,
      supportsMultipleImages: isSet(object.supportsMultipleImages)
        ? globalThis.Boolean(object.supportsMultipleImages)
        : isSet(object.supports_multiple_images)
        ? globalThis.Boolean(object.supports_multiple_images)
        : false,
      visionEncoderType: isSet(object.visionEncoderType)
        ? globalThis.String(object.visionEncoderType)
        : isSet(object.vision_encoder_type)
        ? globalThis.String(object.vision_encoder_type)
        : undefined,
      errorMessage: isSet(object.errorMessage)
        ? globalThis.String(object.errorMessage)
        : isSet(object.error_message)
        ? globalThis.String(object.error_message)
        : undefined,
      errorCode: isSet(object.errorCode)
        ? globalThis.Number(object.errorCode)
        : isSet(object.error_code)
        ? globalThis.Number(object.error_code)
        : 0,
    };
  },

  toJSON(message: VLMServiceState): unknown {
    const obj: any = {};
    if (message.isReady !== false) {
      obj.isReady = message.isReady;
    }
    if (message.currentModel !== undefined) {
      obj.currentModel = message.currentModel;
    }
    if (message.contextLength !== 0) {
      obj.contextLength = Math.round(message.contextLength);
    }
    if (message.supportsStreaming !== false) {
      obj.supportsStreaming = message.supportsStreaming;
    }
    if (message.supportsMultipleImages !== false) {
      obj.supportsMultipleImages = message.supportsMultipleImages;
    }
    if (message.visionEncoderType !== undefined) {
      obj.visionEncoderType = message.visionEncoderType;
    }
    if (message.errorMessage !== undefined) {
      obj.errorMessage = message.errorMessage;
    }
    if (message.errorCode !== 0) {
      obj.errorCode = Math.round(message.errorCode);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VLMServiceState>, I>>(base?: I): VLMServiceState {
    return VLMServiceState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VLMServiceState>, I>>(object: I): VLMServiceState {
    const message = createBaseVLMServiceState();
    message.isReady = object.isReady ?? false;
    message.currentModel = object.currentModel ?? undefined;
    message.contextLength = object.contextLength ?? 0;
    message.supportsStreaming = object.supportsStreaming ?? false;
    message.supportsMultipleImages = object.supportsMultipleImages ?? false;
    message.visionEncoderType = object.visionEncoderType ?? undefined;
    message.errorMessage = object.errorMessage ?? undefined;
    message.errorCode = object.errorCode ?? 0;
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  const bin = globalThis.atob(b64);
  const arr = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; ++i) {
    arr[i] = bin.charCodeAt(i);
  }
  return arr;
}

function base64FromBytes(arr: Uint8Array): string {
  const bin: string[] = [];
  arr.forEach((byte) => {
    bin.push(globalThis.String.fromCharCode(byte));
  });
  return globalThis.btoa(bin.join(""));
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
