/**
 * @file rac_backend_onnx_jni.cpp
 * @brief RunAnywhere Core - ONNX Backend JNI Bridge
 *
 * Self-contained JNI layer for the ONNX backend.
 *
 * Package: com.runanywhere.sdk.core.onnx
 * Class: ONNXBridge
 *
 * The JNI_OnLoad + nativeRegister/nativeUnregister/nativeIsRegistered/
 * nativeGetVersion quartet is generated by the shared
 * RAC_DEFINE_ENGINE_JNI_BRIDGE macro (engines/common/rac_engine_jni_bridge.h);
 * only ONNX's sibling-backend cross-registration is hand-written here and passed
 * to the macro as its after-register statement.
 */

#include <jni.h>

#include <cstddef>
#include <cstring>
#include <string>

#include "rac/core/rac_core.h"
#include "rac/core/rac_error.h"
#include "rac/core/rac_logger.h"
#include "rac/plugin/rac_engine_vtable.h"
#include "rac/plugin/rac_plugin_entry.h"
#include "rac/plugin/rac_primitive.h"

// Shared engine JNI helpers (header-only). The ".." chain is relative to this
// source file's own directory (engines/onnx/jni/), so it resolves without any
// extra -I wiring on the JNI target: ../../common/ == engines/common/.
#include "../../common/rac_engine_jni_bridge.h"
#include "../../common/rac_engine_sibling_loader.h"

// Stamp the LOG_TAG the shared LOGi/LOGe/LOGw macros (from rac_engine_jni_bridge.h)
// route through. Mirrors the tag the bridge declared by hand before extraction.
RAC_DEFINE_ENGINE_JNI_LOG_TAG("JNI.ONNX");

// Forward declarations
extern "C" rac_result_t rac_backend_onnx_register(void);
extern "C" rac_result_t rac_backend_onnx_unregister(void);

// ONNX-specific work run inside nativeRegister AFTER rac_backend_onnx_register()
// succeeds (or reports already-registered), BEFORE the success return. Passed to
// RAC_DEFINE_ENGINE_JNI_BRIDGE as its AFTER_REGISTER_STMT argument, which expands
// `rac_backend_onnx_jni_after_register(env, clazz)` at that point — keeping the
// engine-specific logic out of the shared macro.
static inline void rac_backend_onnx_jni_after_register(JNIEnv* env, jclass clazz) {
    (void)env;
    (void)clazz;

    // Opportunistically register the Sherpa backend when
    // librac_backend_sherpa.so is present in-process. On Android, libraries
    // loaded by System.loadLibrary from a non-bootclassloader live in a
    // per-class-loader linker namespace, so `dlsym(RTLD_DEFAULT, …)` cannot see
    // symbols in `librac_backend_sherpa.so` even though Kotlin's ONNXBridge
    // already System.loadLibrary'd it. The shared sibling loader dlopen()s the
    // .so by name to obtain a handle in the current namespace, then dlsym()s
    // from it (falling back to RTLD_DEFAULT for already-global hosts). Static
    // hosts (RAC_STATIC_PLUGINS=ON) still go through RAC_STATIC_PLUGIN_REGISTER
    // from rac_static_register_sherpa.cpp.
    rac_engine_register_sibling("librac_backend_sherpa.so", "rac_backend_sherpa_register");

    // List EMBED plugins for debug visibility.
    const rac_engine_vtable_t* plugins[16] = {};
    size_t plugin_count = 0;
    rac_result_t list_result = rac_plugin_list(RAC_PRIMITIVE_EMBED, plugins, 16, &plugin_count);
    LOGi("After ONNX registration - EMBED plugins: count=%zu, result=%d", plugin_count,
         list_result);
}

extern "C" {

// =============================================================================
// JNI_OnLoad + Backend Registration quartet (generated)
// =============================================================================
//
// Emits, with C linkage and EXACT JNI symbol parity:
//   Java_com_runanywhere_sdk_core_onnx_ONNXBridge_nativeRegister
//   Java_com_runanywhere_sdk_core_onnx_ONNXBridge_nativeUnregister
//   Java_com_runanywhere_sdk_core_onnx_ONNXBridge_nativeIsRegistered
//   Java_com_runanywhere_sdk_core_onnx_ONNXBridge_nativeGetVersion
// nativeIsRegistered scans the EMBED plugin registry for the plugin named
// "onnx"; nativeGetVersion reports the linked ONNX Runtime version.
#ifdef RAC_ONNXRUNTIME_VERSION
#define RAC_ONNX_JNI_VERSION_STR RAC_ONNXRUNTIME_VERSION
#else
#define RAC_ONNX_JNI_VERSION_STR "unknown"
#endif

RAC_DEFINE_ENGINE_JNI_BRIDGE(com_runanywhere_sdk_core_onnx_ONNXBridge, rac_backend_onnx_register,
                             rac_backend_onnx_unregister, "ONNX", " (generic ONNX services)",
                             rac_backend_onnx_jni_after_register, RAC_PRIMITIVE_EMBED, "onnx",
                             RAC_ONNX_JNI_VERSION_STR)

JNIEXPORT jint JNICALL
Java_com_runanywhere_sdk_core_onnx_ONNXBridge_nativeRegisterSherpa(JNIEnv* env, jclass clazz) {
    (void)env;
    (void)clazz;
    return static_cast<jint>(
        rac_engine_register_sibling("librac_backend_sherpa.so", "rac_backend_sherpa_register"));
}

JNIEXPORT jint JNICALL
Java_com_runanywhere_sdk_core_onnx_ONNXBridge_nativeUnregisterSherpa(JNIEnv* env, jclass clazz) {
    (void)env;
    (void)clazz;
    return static_cast<jint>(
        rac_engine_register_sibling("librac_backend_sherpa.so", "rac_backend_sherpa_unregister"));
}

}  // extern "C"
