/**
 * HybridVoiceAgent.hpp
 *
 * Nitro HybridObject that wraps the
 * commons `rac_voice_agent_set_proto_callback` C ABI as a
 * subscribe-style JS function returning an unsubscribe closure.
 *
 * One instance maps to exactly one voice agent handle (the handle is
 * passed per-call to `subscribeProtoEvents` rather than captured at
 * construction, so a single HybridObject singleton can serve multiple
 * handles over time). Each `subscribeProtoEvents` call creates an
 * independent C-side registration; the returned JS function deregisters.
 *
 * The HybridVoiceAgentSpec base class is auto-generated by Nitrogen
 * from `src/specs/VoiceAgent.nitro.ts`.
 */

#pragma once

// Generated Nitro spec (emitted by `npx nitrogen`). Dev builds fall back
// to the checked-in location under `nitrogen/generated/`.
#if __has_include(<NitroModules/HybridObject.hpp>)
#include "HybridVoiceAgentSpec.hpp"
#else
#include "../nitrogen/generated/shared/c++/HybridVoiceAgentSpec.hpp"
#endif

#include <cstdint>
#include <memory>
#include <mutex>

namespace margelo::nitro::runanywhere {

/**
 * HybridVoiceAgent - RN native implementation for voice-agent streaming.
 *
 * Implements the `VoiceAgent` interface defined in VoiceAgent.nitro.ts.
 * The entire impl is in `HybridVoiceAgent.cpp` (header is thin so both
 * iOS autolinking and Android CMakeLists see the same signature).
 */
class HybridVoiceAgent : public HybridVoiceAgentSpec {
 public:
  HybridVoiceAgent();
  ~HybridVoiceAgent() override;

  /**
   * Register a proto-byte callback on a voice agent handle.
   *
   * @param handle  Reinterpreted as `rac_voice_agent_handle_t` on the C side.
   * @param onBytes Fires once per `VoiceEvent` with serialized proto bytes
   *                (copied out of the C arena before JS dispatch).
   * @param onDone  Fires on agent termination. Called at most once.
   * @param onError Fires on transport errors. Called at most once with
   *                the `rac_result_t` code.
   *
   * @returns A JS-callable unsubscribe function that, when invoked,
   *          clears the C-side callback and releases the JSI references.
   */
  std::function<void()> subscribeProtoEvents(
      double handle,
      const std::function<void(const std::shared_ptr<ArrayBuffer>&)>& onBytes,
      const std::function<void()>& onDone,
      const std::function<void(const std::string&)>& onError) override;
};

}  // namespace margelo::nitro::runanywhere
