/**
 * HybridRunAnywhereQHexRT.hpp
 *
 * Nitrogen HybridObject implementation for the RunAnywhere QHexRT backend.
 * QHexRT is Qualcomm-only; the Nitro spec targets Android (c++) exclusively,
 * so this hybrid is only ever instantiated on Android arm64.
 *
 * QHexRT-specific implementation:
 * - Backend registration hook (single call covers LLM, VLM, STT, TTS)
 * - Pre-flight Hexagon NPU capability probe (no QNN load)
 *
 * The HybridRunAnywhereQHexRTSpec base class is auto-generated by Nitrogen
 * from src/specs/RunAnywhereQHexRT.nitro.ts
 */

#pragma once

// Include the generated spec header (created by nitrogen)
#if __has_include(<NitroModules/HybridObject.hpp>)
#include "HybridRunAnywhereQHexRTSpec.hpp"
#else
// Fallback include path during development
#include "../nitrogen/generated/shared/c++/HybridRunAnywhereQHexRTSpec.hpp"
#endif

#include <string>

namespace margelo::nitro::runanywhere::qhexrt {

/**
 * HybridRunAnywhereQHexRT - QHexRT backend native implementation
 *
 * Implements the RunAnywhereQHexRT interface defined in
 * RunAnywhereQHexRT.nitro.ts. Registers native providers only; core owns
 * lifecycle and inference.
 */
class HybridRunAnywhereQHexRT : public HybridRunAnywhereQHexRTSpec {
public:
  HybridRunAnywhereQHexRT();
  ~HybridRunAnywhereQHexRT();

  // ============================================================================
  // Backend Registration
  // ============================================================================

  std::shared_ptr<Promise<bool>> registerBackend() override;
  std::shared_ptr<Promise<bool>> unregisterBackend() override;
  std::shared_ptr<Promise<bool>> isBackendRegistered() override;

  // ============================================================================
  // NPU Capability Probe
  // ============================================================================

  std::shared_ptr<Promise<std::shared_ptr<ArrayBuffer>>>
  probeNpuProto() override;
  bool isArchitectureSupported(double arch) override;
  bool modelSupportsArchitecture(const std::string &modelId,
                                 double arch) override;
  bool modelRequiresHfAuth(const std::string &modelId) override;
  std::shared_ptr<Promise<std::shared_ptr<ArrayBuffer>>>
  catalogRegisterModelProto(
      const std::shared_ptr<ArrayBuffer> &requestBytes) override;

private:
  bool isRegistered_ = false;
};

} // namespace margelo::nitro::runanywhere::qhexrt
