/**
 * LlamaCPP Backend JNI Bridge
 *
 * JNI layer for the LlamaCPP backend. Links against rac_commons for the
 * full service registry and infrastructure support.
 *
 * This JNI library is linked by:
 *   Kotlin: runanywhere-kotlin/modules/runanywhere-core-llamacpp
 *
 * Package: com.runanywhere.sdk.llm.llamacpp
 * Class: LlamaCPPBridge
 *
 * The JNI_OnLoad + nativeRegister/nativeUnregister/nativeIsRegistered/
 * nativeGetVersion quartet is generated by the shared
 * RAC_DEFINE_ENGINE_JNI_BRIDGE macro (engines/common/rac_engine_jni_bridge.h);
 * LlamaCPP cross-registers no sibling backend, so it passes the no-op
 * after-register statement. The extra LLM nativeCreate / nativeDestroy /
 * nativeGenerate / nativeCancel / nativeGetModelInfo methods stay hand-written
 * below the macro.
 */

#include <jni.h>

#include <cstring>
#include <string>

// Include LlamaCPP backend header (direct API)
#include "rac_llm_llamacpp.h"

// Include commons for registration and service lookup
#include "rac/core/rac_core.h"
#include "rac/core/rac_error.h"
#include "rac/core/rac_logger.h"

// Shared engine JNI helpers (header-only). The ".." chain is relative to this
// source file's own directory (engines/llamacpp/jni/), so it resolves without
// any extra -I wiring on the JNI target: ../../common/ == engines/common/.
#include "../../common/rac_engine_jni_bridge.h"

// Stamp the LOG_TAG the shared LOGi/LOGe/LOGw macros (from rac_engine_jni_bridge.h)
// route through. Mirrors the tag the bridge declared by hand before extraction.
RAC_DEFINE_ENGINE_JNI_LOG_TAG("JNI.LlamaCpp");

// Forward declaration for the unified registration function. After the
// LLM/VLM plugin unification, llama.cpp publishes ONE plugin that fills
// both `llm_ops` and `vlm_ops` slots; there is no separate VLM register.
extern "C" rac_result_t rac_backend_llamacpp_register(void);
extern "C" rac_result_t rac_backend_llamacpp_unregister(void);

extern "C" {

// =============================================================================
// JNI_OnLoad + Backend Registration quartet (generated)
// =============================================================================
//
// Emits, with C linkage and EXACT JNI symbol parity:
//   Java_com_runanywhere_sdk_llm_llamacpp_LlamaCPPBridge_nativeRegister
//   Java_com_runanywhere_sdk_llm_llamacpp_LlamaCPPBridge_nativeUnregister
//   Java_com_runanywhere_sdk_llm_llamacpp_LlamaCPPBridge_nativeIsRegistered
//   Java_com_runanywhere_sdk_llm_llamacpp_LlamaCPPBridge_nativeGetVersion
// LlamaCPP cross-registers no sibling backend, so it passes the no-op
// after-register statement. nativeIsRegistered scans the GENERATE_TEXT plugin
// registry for the plugin named "llamacpp"; nativeGetVersion reports the linked
// llama.cpp upstream tag (RAC_LLAMACPP_VERSION, injected by CMake).
RAC_DEFINE_ENGINE_JNI_BRIDGE(com_runanywhere_sdk_llm_llamacpp_LlamaCPPBridge,
                             rac_backend_llamacpp_register, rac_backend_llamacpp_unregister,
                             "LlamaCPP", "", RAC_ENGINE_JNI_NO_AFTER_REGISTER,
                             RAC_PRIMITIVE_GENERATE_TEXT, "llamacpp", RAC_LLAMACPP_VERSION)

// =============================================================================
// LLM Operations - Direct API calls
// =============================================================================
// Note: VLM registration is no longer a separate JNI call. After the LLM/VLM
// plugin unification, `rac_backend_llamacpp_register()` registers ONE plugin
// vtable with both LLM and VLM ops filled. Kotlin's `LlamaCPP.register()`
// calls `nativeRegister()` once; both modalities light up together.

/**
 * Create a LlamaCPP instance and load a model
 */
JNIEXPORT jlong JNICALL Java_com_runanywhere_sdk_llm_llamacpp_LlamaCPPBridge_nativeCreate(
    JNIEnv* env, jclass clazz, jstring modelPath, jint contextSize, jint numThreads,
    jint gpuLayers) {
    (void)clazz;

    const char* path = env->GetStringUTFChars(modelPath, nullptr);
    if (!path) {
        LOGe("nativeCreate: Failed to get model path");
        return 0;
    }

    LOGi("nativeCreate: model=%s, ctx=%d, threads=%d, gpu=%d", path, contextSize, numThreads,
         gpuLayers);

    rac_llm_llamacpp_config_t config = RAC_LLM_LLAMACPP_CONFIG_DEFAULT;
    config.context_size = contextSize;
    config.num_threads = numThreads;
    config.gpu_layers = gpuLayers;

    rac_handle_t handle = nullptr;
    rac_result_t result = rac_llm_llamacpp_create(path, &config, &handle);

    env->ReleaseStringUTFChars(modelPath, path);

    if (result != RAC_SUCCESS) {
        LOGe("nativeCreate: Failed with result %d", result);
        return 0;
    }

    LOGi("nativeCreate: Success, handle=%p", handle);
    return reinterpret_cast<jlong>(handle);
}

/**
 * Destroy a LlamaCPP instance
 */
JNIEXPORT void JNICALL Java_com_runanywhere_sdk_llm_llamacpp_LlamaCPPBridge_nativeDestroy(
    JNIEnv* env, jclass clazz, jlong handle) {
    (void)env;
    (void)clazz;

    if (handle == 0)
        return;

    LOGi("nativeDestroy: handle=%p", reinterpret_cast<void*>(handle));
    rac_llm_llamacpp_destroy(reinterpret_cast<rac_handle_t>(handle));
}

/**
 * Generate text (blocking)
 */
JNIEXPORT jstring JNICALL Java_com_runanywhere_sdk_llm_llamacpp_LlamaCPPBridge_nativeGenerate(
    JNIEnv* env, jclass clazz, jlong handle, jstring prompt, jint maxTokens, jfloat temperature) {
    (void)clazz;

    if (handle == 0) {
        LOGe("nativeGenerate: Invalid handle");
        return nullptr;
    }

    const char* promptStr = env->GetStringUTFChars(prompt, nullptr);
    if (!promptStr) {
        LOGe("nativeGenerate: Failed to get prompt");
        return nullptr;
    }

    LOGi("nativeGenerate: prompt_len=%zu, max_tokens=%d, temp=%.2f", strlen(promptStr), maxTokens,
         temperature);

    rac_llm_options_t options = RAC_LLM_OPTIONS_DEFAULT;
    options.max_tokens = maxTokens;
    options.temperature = temperature;

    rac_llm_result_t result = {};
    rac_result_t status = rac_llm_llamacpp_generate(reinterpret_cast<rac_handle_t>(handle),
                                                    promptStr, &options, &result);

    env->ReleaseStringUTFChars(prompt, promptStr);

    if (status != RAC_SUCCESS) {
        LOGe("nativeGenerate: Failed with status %d", status);
        return nullptr;
    }

    jstring output = nullptr;
    if (result.text) {
        output = env->NewStringUTF(result.text);
        LOGi("nativeGenerate: Success, output_len=%zu", strlen(result.text));
        // Free the allocated text
        free((void*)result.text);
    }

    return output;
}

/**
 * Cancel ongoing generation
 */
JNIEXPORT void JNICALL Java_com_runanywhere_sdk_llm_llamacpp_LlamaCPPBridge_nativeCancel(
    JNIEnv* env, jclass clazz, jlong handle) {
    (void)env;
    (void)clazz;

    if (handle == 0)
        return;

    LOGi("nativeCancel: handle=%p", reinterpret_cast<void*>(handle));
    rac_llm_llamacpp_cancel(reinterpret_cast<rac_handle_t>(handle));
}

/**
 * Get model info as JSON
 */
JNIEXPORT jstring JNICALL Java_com_runanywhere_sdk_llm_llamacpp_LlamaCPPBridge_nativeGetModelInfo(
    JNIEnv* env, jclass clazz, jlong handle) {
    (void)clazz;

    if (handle == 0)
        return nullptr;

    char* json = nullptr;
    rac_result_t status =
        rac_llm_llamacpp_get_model_info(reinterpret_cast<rac_handle_t>(handle), &json);

    if (status != RAC_SUCCESS || !json) {
        return nullptr;
    }

    jstring result = env->NewStringUTF(json);
    free(json);

    return result;
}

}  // extern "C"
