/**
 * HybridRunAnywhereLlama.hpp
 *
 * Nitrogen HybridObject implementation for RunAnywhere Llama backend.
 * This single C++ file works on both iOS and Android.
 *
 * Llama-specific implementation:
 * - Backend registration hook (single call covers both LLM and VLM modalities)
 *
 * Matches Swift SDK: LlamaCPPRuntime/LlamaCPP.swift
 *
 * The HybridRunAnywhereLlamaSpec base class is auto-generated by Nitrogen
 * from src/specs/RunAnywhereLlama.nitro.ts
 */

#pragma once

// Include the generated spec header (created by nitrogen)
#if __has_include(<NitroModules/HybridObject.hpp>)
#include "HybridRunAnywhereLlamaSpec.hpp"
#else
// Fallback include path during development
#include "../nitrogen/generated/shared/c++/HybridRunAnywhereLlamaSpec.hpp"
#endif

namespace margelo::nitro::runanywhere::llama {

/**
 * HybridRunAnywhereLlama - Llama backend native implementation
 *
 * Implements the RunAnywhereLlama interface defined in RunAnywhereLlama.nitro.ts
 * Registers native providers only. Core owns lifecycle and inference.
 */
class HybridRunAnywhereLlama : public HybridRunAnywhereLlamaSpec {
public:
  HybridRunAnywhereLlama();
  ~HybridRunAnywhereLlama();

  // ============================================================================
  // Backend Registration
  // ============================================================================

  std::shared_ptr<Promise<bool>> registerBackend() override;
  std::shared_ptr<Promise<bool>> unregisterBackend() override;
  std::shared_ptr<Promise<bool>> isBackendRegistered() override;

private:
  bool isRegistered_ = false;
};

} // namespace margelo::nitro::runanywhere::llama
