#!/usr/bin/env bash
# Exercises the public Flutter plugins' remote Android download path against a
# local release fixture, including a fail-closed checksum corruption case.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../../.." && pwd)"
FLUTTER_PACKAGES="${REPO_ROOT}/sdk/runanywhere-flutter/packages"
ANDROID_PROJECT="${REPO_ROOT}/examples/flutter/RunAnywhereAI/android"
VERSION="$(tr -d '[:space:]' < "${REPO_ROOT}/sdk/runanywhere-commons/VERSION")"
FIXTURE="$(mktemp -d "${TMPDIR:-/tmp}/rac-flutter-release.XXXXXX")"
trap 'rm -rf "${FIXTURE}"' EXIT

release_dir="${FIXTURE}/v${VERSION}"
mkdir -p "${release_dir}"

for abi in arm64-v8a armeabi-v7a x86_64; do
    stage="${FIXTURE}/stage-${abi}"
    mkdir -p "${stage}/${abi}"/{jni,llamacpp,onnx}
    for component in jni llamacpp onnx; do
        # Natives are staged into the FLUTTER package layouts by package-sdk.sh
        # (run immediately before this script), NOT the Kotlin SDK's jniLibs —
        # those don't exist in the validate_consumer_flutter job's clean checkout.
        case "${component}" in
            jni) source_dir="${FLUTTER_PACKAGES}/runanywhere/android/src/main/jniLibs/${abi}" ;;
            llamacpp) source_dir="${FLUTTER_PACKAGES}/runanywhere_llamacpp/android/src/main/jniLibs/${abi}" ;;
            onnx) source_dir="${FLUTTER_PACKAGES}/runanywhere_onnx/android/src/main/jniLibs/${abi}" ;;
        esac
        if ! find "${source_dir}" -maxdepth 1 -type f -name '*.so' -print -quit | grep -q .; then
            echo "error: no staged ${component}/${abi} native libraries at ${source_dir}" >&2
            exit 1
        fi
        cp "${source_dir}/"*.so "${stage}/${abi}/${component}/"
    done

    archive="RACommons-android-${abi}-v${VERSION}.zip"
    (
        cd "${stage}"
        zip -X -q -r "${release_dir}/${archive}" "${abi}"
    )
    (
        cd "${release_dir}"
        shasum -a 256 "${archive}" > "${archive}.sha256"
    )
done

# The example's Flutter plugin gradle subprojects (:runanywhere,
# :runanywhere_llamacpp, :runanywhere_onnx) are registered by
# dev.flutter.flutter-plugin-loader, which reads .flutter-plugins-dependencies.
# That file (and local.properties) is generated by `flutter pub get`. This script
# runs BEFORE the CI job's own `flutter pub get` (release.yml stages natives
# first), so on a clean checkout the plugin subprojects don't exist yet ->
# ":runanywhere not found in root project 'android'". Run pub get here so the
# plugin subprojects (and local.properties) exist before gradlew is invoked.
EXAMPLE_DIR="$(cd "${ANDROID_PROJECT}/.." && pwd)"
if [ ! -f "${EXAMPLE_DIR}/.flutter-plugins-dependencies" ]; then
    (cd "${EXAMPLE_DIR}" && flutter pub get)
fi

# The example's Android gradle build hard-reads local.properties (sdk.dir +
# flutter.sdk). It is gitignored and normally generated by `flutter build`/`run`
# or `flutter pub get`, but if that file is somehow present without
# local.properties, this script calls gradlew before the CI job's own flutter
# commands, so on a clean checkout it is absent -> "local.properties (No such
# file or directory)". Generate it here so the script is self-sufficient.
if [ ! -f "${ANDROID_PROJECT}/local.properties" ]; then
    _sdk_dir="${ANDROID_SDK_ROOT:-${ANDROID_HOME:-}}"
    _flutter_sdk="$(cd "$(dirname "$(command -v flutter)")/.." 2>/dev/null && pwd || true)"
    {
        [ -n "${_sdk_dir}" ] && echo "sdk.dir=${_sdk_dir}"
        [ -n "${_flutter_sdk}" ] && echo "flutter.sdk=${_flutter_sdk}"
    } > "${ANDROID_PROJECT}/local.properties"
fi

gradle=(
    "${ANDROID_PROJECT}/gradlew"
    -p "${ANDROID_PROJECT}"
    -Prunanywhere.useLocalNatives=false
    "-Prunanywhere.releaseBaseUrl=file://${FIXTURE}"
    --no-daemon
)

"${gradle[@]}" \
    :runanywhere:downloadNativeLibs \
    :runanywhere_llamacpp:downloadNativeLibs \
    :runanywhere_onnx:downloadNativeLibs

core_libs=(
    libc++_shared.so libomp.so librac_backend_cloud.so librac_commons.so
    librunanywhere_jni.so
)
llamacpp_libs=(
    libc++_shared.so librac_backend_llamacpp.so
    librac_backend_llamacpp_jni.so librunanywhere_llamacpp.so
)
onnx_libs=(
    libc++_shared.so libonnxruntime.so librac_backend_onnx.so
    librac_backend_onnx_jni.so librac_backend_sherpa.so
    librunanywhere_onnx.so librunanywhere_sherpa.so
    libsherpa-onnx-c-api.so libsherpa-onnx-jni.so
)

assert_inventory() {
    local dir="$1"
    shift
    local lib actual
    for lib in "$@"; do
        test -f "$dir/$lib"
    done
    actual="$(find "$dir" -maxdepth 1 -type f -name '*.so' | wc -l | tr -d ' ')"
    if [ "$actual" -ne "$#" ]; then
        echo "error: unexpected remote native inventory in $dir (expected $#, found $actual)" >&2
        exit 1
    fi
}

for abi in arm64-v8a armeabi-v7a x86_64; do
    assert_inventory \
        "${FLUTTER_PACKAGES}/runanywhere/android/build/jniLibs/${abi}" \
        "${core_libs[@]}"
    assert_inventory \
        "${FLUTTER_PACKAGES}/runanywhere_llamacpp/android/build/jniLibs/${abi}" \
        "${llamacpp_libs[@]}"
    assert_inventory \
        "${FLUTTER_PACKAGES}/runanywhere_onnx/android/build/jniLibs/${abi}" \
        "${onnx_libs[@]}"
done

bad_archive="RACommons-android-arm64-v8a-v${VERSION}.zip"
printf '%064d  %s\n' 0 "${bad_archive}" > "${release_dir}/${bad_archive}.sha256"
negative_log="${FIXTURE}/checksum-negative.log"
if "${gradle[@]}" :runanywhere:downloadNativeLibs --rerun-tasks >"${negative_log}" 2>&1; then
    echo "error: corrupted Flutter release checksum was accepted" >&2
    exit 1
fi
if ! grep -q "Checksum mismatch" "${negative_log}"; then
    echo "error: corrupted checksum failed for an unexpected reason" >&2
    cat "${negative_log}" >&2
    exit 1
fi

echo "Flutter remote Android downloads: checksum success + corruption rejection passed"
