# frozen_string_literal: true

# Adds the MCP Agent strings to every Android and iOS locale without changing
# existing translations. Safe to run repeatedly.

translations = {
  "en" => ["MCP settings", "MCP Tools", "Connect MCP servers and let Agent use their tools.", "Transport", "Termux stdio", "Remote HTTP", "MCP server command", "Runs the MCP server through Termux stdio. Install its required packages first.", "Server URL", "Bearer token (optional)", "Every MCP tool call requires your approval before it runs.", "Connecting…", "%d tools connected", "MCP error: %@", "Connect", "Disconnect", "MCP tool: %@", "Allow", "Deny", "Approval required", "Denied by user", "Status", "Termux shell command"],
  "es" => ["Ajustes de MCP", "Herramientas MCP", "Conecta servidores MCP y permite que el Agente use sus herramientas.", "Transporte", "stdio de Termux", "HTTP remoto", "Comando del servidor MCP", "Ejecuta el servidor MCP mediante stdio de Termux. Instala primero los paquetes necesarios.", "URL del servidor", "Token Bearer (opcional)", "Cada llamada a una herramienta MCP requiere tu aprobación antes de ejecutarse.", "Conectando…", "%d herramientas conectadas", "Error de MCP: %@", "Conectar", "Desconectar", "Herramienta MCP: %@", "Permitir", "Denegar", "Se requiere aprobación", "Denegado por el usuario", "Estado", "Comando de shell de Termux"],
  "pt" => ["Definições de MCP", "Ferramentas MCP", "Ligue servidores MCP e permita que o Agente use as suas ferramentas.", "Transporte", "stdio do Termux", "HTTP remoto", "Comando do servidor MCP", "Executa o servidor MCP através do stdio do Termux. Instale primeiro os pacotes necessários.", "URL do servidor", "Token Bearer (opcional)", "Cada chamada de ferramenta MCP requer a sua aprovação antes da execução.", "A ligar…", "%d ferramentas ligadas", "Erro de MCP: %@", "Ligar", "Desligar", "Ferramenta MCP: %@", "Permitir", "Negar", "Aprovação necessária", "Negado pelo utilizador", "Estado", "Comando shell do Termux"],
  "de" => ["MCP-Einstellungen", "MCP-Werkzeuge", "MCP-Server verbinden und dem Agenten die Nutzung ihrer Werkzeuge erlauben.", "Transport", "Termux-stdio", "Remote-HTTP", "MCP-Serverbefehl", "Führt den MCP-Server über Termux-stdio aus. Installiere zuerst die erforderlichen Pakete.", "Server-URL", "Bearer-Token (optional)", "Jeder MCP-Werkzeugaufruf benötigt vor der Ausführung deine Zustimmung.", "Verbindung wird hergestellt…", "%d Werkzeuge verbunden", "MCP-Fehler: %@", "Verbinden", "Trennen", "MCP-Werkzeug: %@", "Erlauben", "Ablehnen", "Zustimmung erforderlich", "Vom Benutzer abgelehnt", "Status", "Termux-Shell-Befehl"],
  "fr" => ["Réglages MCP", "Outils MCP", "Connectez des serveurs MCP et autorisez l’Agent à utiliser leurs outils.", "Transport", "stdio Termux", "HTTP distant", "Commande du serveur MCP", "Exécute le serveur MCP via stdio dans Termux. Installez d’abord les paquets requis.", "URL du serveur", "Jeton Bearer (facultatif)", "Chaque appel d’outil MCP nécessite votre autorisation avant son exécution.", "Connexion…", "%d outils connectés", "Erreur MCP : %@", "Connecter", "Déconnecter", "Outil MCP : %@", "Autoriser", "Refuser", "Autorisation requise", "Refusé par l’utilisateur", "État", "Commande shell Termux"],
  "it" => ["Impostazioni MCP", "Strumenti MCP", "Connetti server MCP e consenti all’Agente di usarne gli strumenti.", "Trasporto", "stdio Termux", "HTTP remoto", "Comando server MCP", "Esegue il server MCP tramite stdio di Termux. Installa prima i pacchetti richiesti.", "URL del server", "Token Bearer (facoltativo)", "Ogni chiamata a uno strumento MCP richiede la tua approvazione prima dell’esecuzione.", "Connessione…", "%d strumenti connessi", "Errore MCP: %@", "Connetti", "Disconnetti", "Strumento MCP: %@", "Consenti", "Nega", "Approvazione richiesta", "Negato dall’utente", "Stato", "Comando shell Termux"],
  "tr" => ["MCP ayarları", "MCP Araçları", "MCP sunucularına bağlanın ve Aracının araçlarını kullanmasına izin verin.", "Aktarım", "Termux stdio", "Uzak HTTP", "MCP sunucu komutu", "MCP sunucusunu Termux stdio üzerinden çalıştırır. Önce gerekli paketleri kurun.", "Sunucu URL’si", "Bearer belirteci (isteğe bağlı)", "Her MCP araç çağrısı çalışmadan önce onayınızı gerektirir.", "Bağlanıyor…", "%d araç bağlandı", "MCP hatası: %@", "Bağlan", "Bağlantıyı kes", "MCP aracı: %@", "İzin ver", "Reddet", "Onay gerekli", "Kullanıcı tarafından reddedildi", "Durum", "Termux kabuk komutu"],
  "pl" => ["Ustawienia MCP", "Narzędzia MCP", "Połącz serwery MCP i pozwól Agentowi korzystać z ich narzędzi.", "Transport", "stdio Termux", "Zdalne HTTP", "Polecenie serwera MCP", "Uruchamia serwer MCP przez stdio Termux. Najpierw zainstaluj wymagane pakiety.", "URL serwera", "Token Bearer (opcjonalny)", "Każde wywołanie narzędzia MCP wymaga zatwierdzenia przed uruchomieniem.", "Łączenie…", "Połączono narzędzia: %d", "Błąd MCP: %@", "Połącz", "Rozłącz", "Narzędzie MCP: %@", "Zezwól", "Odmów", "Wymagane zatwierdzenie", "Odrzucone przez użytkownika", "Stan", "Polecenie powłoki Termux"],
  "ru" => ["Настройки MCP", "Инструменты MCP", "Подключайте серверы MCP и разрешайте Агенту использовать их инструменты.", "Транспорт", "stdio Termux", "Удалённый HTTP", "Команда сервера MCP", "Запускает сервер MCP через stdio Termux. Сначала установите необходимые пакеты.", "URL сервера", "Токен Bearer (необязательно)", "Для каждого вызова инструмента MCP требуется ваше подтверждение.", "Подключение…", "Подключено инструментов: %d", "Ошибка MCP: %@", "Подключить", "Отключить", "Инструмент MCP: %@", "Разрешить", "Отклонить", "Требуется подтверждение", "Отклонено пользователем", "Статус", "Команда оболочки Termux"],
  "uk" => ["Налаштування MCP", "Інструменти MCP", "Підключайте сервери MCP і дозволяйте Агенту використовувати їхні інструменти.", "Транспорт", "stdio Termux", "Віддалений HTTP", "Команда сервера MCP", "Запускає сервер MCP через stdio Termux. Спочатку встановіть потрібні пакети.", "URL сервера", "Токен Bearer (необов’язково)", "Кожен виклик інструмента MCP потребує вашого схвалення перед запуском.", "Підключення…", "Підключено інструментів: %d", "Помилка MCP: %@", "Підключити", "Відключити", "Інструмент MCP: %@", "Дозволити", "Відхилити", "Потрібне схвалення", "Відхилено користувачем", "Стан", "Команда оболонки Termux"],
  "ar" => ["إعدادات MCP", "أدوات MCP", "اتصل بخوادم MCP واسمح للوكيل باستخدام أدواتها.", "النقل", "stdio عبر Termux", "HTTP بعيد", "أمر خادم MCP", "يشغّل خادم MCP عبر stdio في Termux. ثبّت الحزم المطلوبة أولاً.", "عنوان URL للخادم", "رمز Bearer (اختياري)", "تتطلب كل عملية استدعاء لأداة MCP موافقتك قبل تشغيلها.", "جارٍ الاتصال…", "تم توصيل %d من الأدوات", "خطأ MCP: %@", "اتصال", "قطع الاتصال", "أداة MCP: %@", "سماح", "رفض", "الموافقة مطلوبة", "رفضه المستخدم", "الحالة", "أمر صدفة Termux"],
  "fa" => ["تنظیمات MCP", "ابزارهای MCP", "به سرورهای MCP متصل شوید و به عامل اجازه دهید از ابزارهای آن‌ها استفاده کند.", "انتقال", "stdio ترموکس", "HTTP راه‌دور", "فرمان سرور MCP", "سرور MCP را از طریق stdio ترموکس اجرا می‌کند. ابتدا بسته‌های لازم را نصب کنید.", "نشانی سرور", "توکن Bearer (اختیاری)", "هر فراخوانی ابزار MCP پیش از اجرا به تأیید شما نیاز دارد.", "در حال اتصال…", "%d ابزار متصل شد", "خطای MCP: %@", "اتصال", "قطع اتصال", "ابزار MCP: %@", "اجازه", "رد", "تأیید لازم است", "توسط کاربر رد شد", "وضعیت", "فرمان پوسته ترموکس"],
  "he" => ["הגדרות MCP", "כלי MCP", "התחברו לשרתי MCP ואפשרו לסוכן להשתמש בכלים שלהם.", "תעבורה", "stdio של Termux", "HTTP מרוחק", "פקודת שרת MCP", "מפעיל את שרת MCP דרך stdio של Termux. יש להתקין תחילה את החבילות הנדרשות.", "כתובת השרת", "אסימון Bearer (אופציונלי)", "כל הפעלת כלי MCP דורשת את אישורך לפני ההרצה.", "מתחבר…", "%d כלים מחוברים", "שגיאת MCP: %@", "התחברות", "ניתוק", "כלי MCP: %@", "אישור", "דחייה", "נדרש אישור", "נדחה על ידי המשתמש", "מצב", "פקודת מעטפת Termux"],
  "hi" => ["MCP सेटिंग", "MCP टूल", "MCP सर्वर कनेक्ट करें और एजेंट को उनके टूल इस्तेमाल करने दें।", "ट्रांसपोर्ट", "Termux stdio", "रिमोट HTTP", "MCP सर्वर कमांड", "Termux stdio के जरिए MCP सर्वर चलाता है। पहले जरूरी पैकेज इंस्टॉल करें।", "सर्वर URL", "Bearer टोकन (वैकल्पिक)", "हर MCP टूल कॉल चलने से पहले आपकी मंजूरी मांगती है।", "कनेक्ट हो रहा है…", "%d टूल कनेक्ट हैं", "MCP त्रुटि: %@", "कनेक्ट करें", "डिस्कनेक्ट करें", "MCP टूल: %@", "अनुमति दें", "अस्वीकार करें", "मंजूरी जरूरी", "उपयोगकर्ता ने अस्वीकार किया", "स्थिति", "Termux शेल कमांड"],
  "id" => ["Pengaturan MCP", "Alat MCP", "Hubungkan server MCP dan izinkan Agen menggunakan alatnya.", "Transport", "stdio Termux", "HTTP jarak jauh", "Perintah server MCP", "Menjalankan server MCP melalui stdio Termux. Instal paket yang diperlukan terlebih dahulu.", "URL server", "Token Bearer (opsional)", "Setiap panggilan alat MCP memerlukan persetujuan Anda sebelum dijalankan.", "Menghubungkan…", "%d alat terhubung", "Kesalahan MCP: %@", "Hubungkan", "Putuskan", "Alat MCP: %@", "Izinkan", "Tolak", "Persetujuan diperlukan", "Ditolak oleh pengguna", "Status", "Perintah shell Termux"],
  "ja" => ["MCP設定", "MCPツール", "MCPサーバーに接続し、エージェントがそのツールを使用できるようにします。", "トランスポート", "Termux stdio", "リモートHTTP", "MCPサーバーコマンド", "Termux stdio経由でMCPサーバーを実行します。必要なパッケージを先にインストールしてください。", "サーバーURL", "Bearerトークン（任意）", "すべてのMCPツール呼び出しは、実行前に承認が必要です。", "接続中…", "%d個のツールに接続済み", "MCPエラー: %@", "接続", "切断", "MCPツール: %@", "許可", "拒否", "承認が必要", "ユーザーが拒否しました", "状態", "Termuxシェルコマンド"],
  "ko" => ["MCP 설정", "MCP 도구", "MCP 서버를 연결하고 에이전트가 해당 도구를 사용하도록 허용합니다.", "전송", "Termux stdio", "원격 HTTP", "MCP 서버 명령", "Termux stdio를 통해 MCP 서버를 실행합니다. 필요한 패키지를 먼저 설치하세요.", "서버 URL", "Bearer 토큰(선택 사항)", "모든 MCP 도구 호출은 실행 전에 승인이 필요합니다.", "연결 중…", "%d개 도구 연결됨", "MCP 오류: %@", "연결", "연결 해제", "MCP 도구: %@", "허용", "거부", "승인 필요", "사용자가 거부함", "상태", "Termux 셸 명령"],
  "zh-TW" => ["MCP 設定", "MCP 工具", "連接 MCP 伺服器並允許代理程式使用其工具。", "傳輸方式", "Termux stdio", "遠端 HTTP", "MCP 伺服器命令", "透過 Termux stdio 執行 MCP 伺服器。請先安裝必要的套件。", "伺服器 URL", "Bearer 權杖（選填）", "每次 MCP 工具呼叫都必須在執行前取得您的核准。", "連接中…", "已連接 %d 個工具", "MCP 錯誤：%@", "連接", "中斷連接", "MCP 工具：%@", "允許", "拒絕", "需要核准", "使用者已拒絕", "狀態", "Termux Shell 命令"],
  "nl" => ["MCP-instellingen", "MCP-tools", "Verbind MCP-servers en laat Agent hun tools gebruiken.", "Transport", "Termux-stdio", "Externe HTTP", "MCP-serveropdracht", "Voert de MCP-server uit via Termux-stdio. Installeer eerst de vereiste pakketten.", "Server-URL", "Bearer-token (optioneel)", "Elke MCP-tooloproep vereist je goedkeuring voordat deze wordt uitgevoerd.", "Verbinden…", "%d tools verbonden", "MCP-fout: %@", "Verbinden", "Verbinding verbreken", "MCP-tool: %@", "Toestaan", "Weigeren", "Goedkeuring vereist", "Geweigerd door gebruiker", "Status", "Termux-shellopdracht"],
  "da" => ["MCP-indstillinger", "MCP-værktøjer", "Forbind MCP-servere, og lad Agent bruge deres værktøjer.", "Transport", "Termux-stdio", "Ekstern HTTP", "MCP-serverkommando", "Kører MCP-serveren via Termux-stdio. Installer først de nødvendige pakker.", "Server-URL", "Bearer-token (valgfrit)", "Hvert MCP-værktøjskald kræver din godkendelse, før det køres.", "Opretter forbindelse…", "%d værktøjer forbundet", "MCP-fejl: %@", "Forbind", "Afbryd", "MCP-værktøj: %@", "Tillad", "Afvis", "Godkendelse påkrævet", "Afvist af brugeren", "Status", "Termux-shellkommando"],
  "th" => ["การตั้งค่า MCP", "เครื่องมือ MCP", "เชื่อมต่อเซิร์ฟเวอร์ MCP และอนุญาตให้เอเจนต์ใช้เครื่องมือของเซิร์ฟเวอร์", "การรับส่ง", "Termux stdio", "HTTP ระยะไกล", "คำสั่งเซิร์ฟเวอร์ MCP", "เรียกใช้เซิร์ฟเวอร์ MCP ผ่าน Termux stdio โปรดติดตั้งแพ็กเกจที่จำเป็นก่อน", "URL เซิร์ฟเวอร์", "โทเค็น Bearer (ไม่บังคับ)", "การเรียกใช้เครื่องมือ MCP ทุกครั้งต้องได้รับอนุมัติจากคุณก่อนทำงาน", "กำลังเชื่อมต่อ…", "เชื่อมต่อเครื่องมือ %d รายการ", "ข้อผิดพลาด MCP: %@", "เชื่อมต่อ", "ยกเลิกการเชื่อมต่อ", "เครื่องมือ MCP: %@", "อนุญาต", "ปฏิเสธ", "ต้องได้รับอนุมัติ", "ผู้ใช้ปฏิเสธ", "สถานะ", "คำสั่งเชลล์ Termux"],
  "vi" => ["Cài đặt MCP", "Công cụ MCP", "Kết nối máy chủ MCP và cho phép Tác nhân sử dụng công cụ của chúng.", "Phương thức truyền", "Termux stdio", "HTTP từ xa", "Lệnh máy chủ MCP", "Chạy máy chủ MCP qua Termux stdio. Hãy cài đặt các gói cần thiết trước.", "URL máy chủ", "Mã Bearer (tùy chọn)", "Mỗi lần gọi công cụ MCP đều cần bạn phê duyệt trước khi chạy.", "Đang kết nối…", "Đã kết nối %d công cụ", "Lỗi MCP: %@", "Kết nối", "Ngắt kết nối", "Công cụ MCP: %@", "Cho phép", "Từ chối", "Cần phê duyệt", "Người dùng đã từ chối", "Trạng thái", "Lệnh shell Termux"]
}

keys = %w[
  agent_mcp_settings agent_mcp_title agent_mcp_description agent_mcp_transport
  agent_mcp_termux_stdio agent_mcp_remote_http agent_mcp_command agent_mcp_termux_help
  agent_mcp_server_url agent_mcp_bearer_token agent_mcp_approval_notice agent_mcp_connecting
  agent_mcp_connected_tools agent_mcp_error agent_mcp_connect agent_mcp_disconnect
  agent_mcp_tool_request agent_mcp_allow agent_mcp_deny agent_mcp_approval_required
  agent_mcp_denied agent_mcp_status agent_termux_tool_title
]

root = File.expand_path("..", __dir__)

Dir.glob(File.join(root, "ios/LLMHub/Sources/LLMHub/*.lproj/Localizable.strings")).each do |path|
  locale = File.basename(File.dirname(path), ".lproj")
  values = translations.fetch(locale)
  existing = File.read(path)
  additions = keys.zip(values).reject { |key, _| existing.include?("\"#{key}\"") }.map do |key, value|
    escaped = value.gsub("\\", "\\\\").gsub('"', '\\"').gsub("\n", "\\n")
    "\"#{key}\" = \"#{escaped}\";"
  end
  File.open(path, "a") { |file| file.write("\n\n/* MCP Agent */\n#{additions.join("\n")}\n") } unless additions.empty?
end

android_locale_map = { "values" => "en", "values-in" => "id", "values-iw" => "he", "values-zh" => "zh-TW" }
Dir.glob(File.join(root, "android/app/src/main/res/values*/strings.xml")).each do |path|
  folder = File.basename(File.dirname(path))
  locale = android_locale_map[folder] || folder.delete_prefix("values-")
  values = translations.fetch(locale)
  existing = File.read(path)
  additions = keys.zip(values).reject { |key, _| existing.include?("name=\"#{key}\"") }.map do |key, value|
    android_value = value.gsub("%@", "%1$s").gsub("%d", "%1$d")
      .gsub("&", "&amp;").gsub("<", "&lt;").gsub(">", "&gt;").gsub("'", "\\\\'")
    "    <string name=\"#{key}\">#{android_value}</string>"
  end
  next if additions.empty?
  updated = existing.sub(%r{\s*</resources>\s*\z}, "\n\n    <!-- MCP Agent -->\n#{additions.join("\n")}\n</resources>\n")
  File.write(path, updated)
end
